### ISSUE TITLE
Create Whitepaper for the State of ChaosEngineering in Cloud Native

### ISSUE THREAD

**Issue by ksatchit** [cncf/tag-app-delivery#108]
This is an initiative to document the state of chaos engineering in the Cloud Native world, and trace the evolution of the discipline, capture trends, learnings from end-user experiences, and present a summary of the architecture/approaches adopted by the CNCF projects in this space. It is also expected to contain some best practices/recommendations for those looking at adding chaos engineering as part of their software delivery lifecycle.  

The paper is being developed as a joint/collaborative effort of the LitmusChaos & ChaosMesh projects - which are sandbox projects within the SIG-App-Delivery & Sig-Network purview - with feedback and contributions welcomed from other projects and end-users/practitioners of chaos. 

Thanks to @AloisReitbauer for suggesting the idea of writing up this document. 

This issue is intended to track the progress, thoughts, and inputs as we go along, and serve as a reference for any other items/issues around this topic

**Comment by ksatchit** [comment]
A working draft is available here: https://docs.google.com/document/d/10l262yuX_Zj8ht1pqKlSZAk4-KxY1tc-PaVmbqIsoDw/edit

**Comment by ksatchit** [comment]
There is a working group being formed with interest from different TAGs (app-delivery, observability, security, network). The charter is available here: https://docs.google.com/document/d/1scr9uuvG1g1xpIHPs3314FqeFufE31ustTVnRMrX3gI/edit#

**Comment by ksatchit** [comment]
The agenda and notes/minutes for the WG meetings are recorded here: https://docs.google.com/document/d/12h9PEJ-4X-KWAlFGlZNiDhRvkKGBtyLf_i-uDw8DpEc/edit#

**Comment by hongchaodeng** [comment]
Involving engineers from Chaos Mesh project for the whitepaper.
@cwen0 @milasuperstar @dcalvin

**Comment by joshgav** [comment]
@prithvi1307 @umamukkara @ksatchit do you still intend to pursue the Chaos Engg working group and this paper? If not we'll close this issue shortly. Thanks!

**Comment by joshgav** [comment]
Related: #415 discussing the future of the Chaos WG.

**Comment by joshgav** [comment]
As per the latest comments in #415 we will archive the chaos engineering working group and stop work on this paper.

If others are interested in starting this work again please let us know in our mailing lists and Slack channels and we'll work together. Thanks!
