### ISSUE TITLE
Logo update for TAG App Delivery

### ISSUE THREAD

**Issue by amye** [cncf/tag-app-delivery#117]
Updated designs are in, let me know on feedback. 
![TAG-app-delivery](https://user-images.githubusercontent.com/107161/122128402-7d686600-cde9-11eb-87d2-94c780ce3c7f.jpeg)

**Comment by AloisReitbauer** [comment]
New name, same Kanguru

**Comment by amye** [comment]
That was the plan. Good with?

**Comment by thschue** [comment]
Thank you for providing the new Logo!
