### ISSUE TITLE
[Public comment] Add Monolith/"Everything Operator" Use case

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#118]
https://github.com/cncf/tag-app-delivery/pull/114#pullrequestreview-674419644

"Furthermore I wonder if there is any stance on merging those functionalities/characteristics together (aka "Monolith Operator"). I am really a fan of making sure things have a single purpose instead of "EverythingOperator". It's common to see multi-micro service application (e.g Thanos or Cortex) and operator deploying all of the components (despite all but one are stateless)."

**Comment by Jenniferstrej** [comment]
@AlexsJones (While I can't assign you directly)

**Comment by thschue** [comment]
@AlexsJones: I think this issue is already solved, isn't it?
