### ISSUE TITLE
Add footnote on umbrella operator pattern use case

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#120]
Action for https://github.com/cncf/tag-app-delivery/pull/114#issuecomment-853342607

**Comment by Jenniferstrej** [comment]
@AlexsJones

**Comment by AlexsJones** [comment]
I thought about this and it's not necessarily a related comment specifically to umbrella operator patterns, rather the growing complexity of the ecosystem. I will add a little stanza around around the future of operators.
