### ISSUE TITLE
Changes in Kubernetes Controllers section

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#121]
Action for comment https://github.com/cncf/tag-app-delivery/pull/114#issuecomment-855957513

Action: Add response from this comment to [Kubernetes Controllers section](https://github.com/cncf/tag-app-delivery/blob/dc766683b88954f09cffa6120e23e4b6764f595c/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#kubernetes-controllers)

**Comment by thschue** [comment]
Added to the White Paper
