### ISSUE TITLE
dapr incubation review

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#129]
dapr applied for incubation.

DD Document: https://docs.google.com/document/d/1GknuJk8Z26KhvFJiblbMSopWbX27nihpxkEG0_TpkCw/edit#heading=h.1zhs5uoq2h7e
TOC PR: https://github.com/cncf/toc/pull/617

**Comment by thschue** [comment]
#130

**Comment by msfussell** [comment]
@hongchaodeng - I put a section into the DD doc for your review and recommendation.

**Comment by hongchaodeng** [comment]
@msfussell Awesome! I will discuss my recommendation first inside the TAG committee and put it into the doc next week.

**Comment by thschue** [comment]
Finished
