### ISSUE TITLE
keptn incubation review

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#131]
Due diligence document: <https://docs.google.com/document/d/14qFAc6kxhWX_JLMUKddgELcymaRw6jmhsq0OYxrHtc0>
TOC PR: https://github.com/cncf/toc/pull/670
Presentation to TAG App Delivery: <https://github.com/cncf/tag-app-delivery/issues/132#issuecomment-901242290>

**Comment by thschue** [comment]
#132

**Comment by oleg-nenashev** [comment]
I will send the update once I have the new version of Due Diligence fully ready for review.
Any feedback is always welcome! https://docs.google.com/document/d/14qFAc6kxhWX_JLMUKddgELcymaRw6jmhsq0OYxrHtc0/edit
