### ISSUE TITLE
Create a Working Group for Cooperative Delivery

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#133]
As infrastructure and application configuration might diverge in multi-staged environments, it might be the case that there is not enough infrastructure for operating an application properly, when promoting it to the next stage. 

The working group should provide insights and successful patterns for this problem. Furthermore, examples and end-user experiences should be provided.

Initial presentation: https://docs.google.com/presentation/d/19xxTAFZFEsY89EL09POMnzeAjbAdJI8FOwybC0aJqDo/edit#slide=id.gcad1332ca5_0_15

Draft of the Charter: https://docs.google.com/document/d/1n8AtfQQGJIJrsU-F-oGN6DVXE76E8OVCXsPpXkWgmBo

**Comment by roberthstrand** [comment]
We could probably close this one, I guess?
