### ISSUE TITLE
[WG Operators] Wrong use of CRD, Custom Resource and Custom Resource Instance/object in the (really good) CNCF Operator White Paper - Final version doc

### ISSUE THREAD

**Issue by antaloala** [cncf/tag-app-delivery#141]
This a great document (thanks for it).
It could be improved if solving some wrong usage of these terms (CRD, Custom Resource, Custom Resource Instance/object).
Some examples:

- (from [https://github.com/cncf/tag-app-delivery/blob/master/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#custom-resources-and-custom-resource-definitions](https://github.com/cncf/tag-app-delivery/blob/master/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#custom-resources-and-custom-resource-definitions)):
   "_In the case of an operator, a custom resource contains the desired state of the resource (e.g. application) but does not contain the implementation logic_"
   Here it really refers to a custom resource instance (or custom object) but not to the Custom Resource

- (from [https://github.com/cncf/tag-app-delivery/blob/master/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#control-loop](https://github.com/cncf/tag-app-delivery/blob/master/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#control-loop)):
  "_The control (reconciliation) loop in a Kubernetes controller ensures that the state that the user declares using a CRD matches the state of the application, but also that the transition between the states works as intended._"
  Here the usage of CRD really refers to the Custom Resource Instance (or Custom object) ... for the Custom Resource created though a CRD object (of course) but using CRD here is really confusing.

As said above, great document !

**Comment by hongchaodeng** [comment]
@antaloala Would you submit a PR to fix it?

**Comment by joshgav** [comment]
Hi @antaloala if you'd still like to improve the paper please submit change requests against this directory: <https://github.com/cncf/tag-app-delivery/tree/main/operator-whitepaper/latest>.

Thanks!
