### ISSUE TITLE
Nocalhost as CNCF Sandbox project

### ISSUE THREAD

**Issue by lyzhang1999** [cncf/tag-app-delivery#142]
Website: https://nocalhost.dev
GitHub: https://github.com/nocalhost/nocalhost
Slides: https://docs.google.com/presentation/d/1E1N-WGpwJRRUiE3U5kcqE5blaMH8Oi9BTzOsaNwOFao

request for Sig presentation.

**Comment by hongchaodeng** [comment]
Awesome! You are warmly welcome to present and participate in the SIG.

You can pick a meeting date and put your presentation into the agenda: https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#

We have regular meetings on 1st and 3rd Wednesdays at 8 am Pacific, 11 am Eastern, which is 11pm in China.

Please don't hesitate to ping us in the Slack (#tag-app-delivery) for any questions you have. I look forward to more dev experience collaboration in the SIG and even a WG for it in the future!

**Comment by thschue** [comment]
Just for clarification: To get into the sandbox, you have to fill out this form: https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true. A SIG presentation is not mandatory for the sandbox. Nevertheless, we'd be very happy to get a presentation of your product in one of the next TAG meetings.

**Comment by lyzhang1999** [comment]
> Just for clarification: To get into the sandbox, you have to fill out this form: https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true. A TAG presentation is not mandatory for the sandbox. Nevertheless, we'd be very happy to get a presentation of your product in one of the next TAG meetings.

Thanks, we have already filled this form.

**Comment by joshgav** [comment]
Notes from today's presentation ([original](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs)):

- Slides: https://docs.google.com/presentation/d/1E1N-WGpwJRRUiE3U5kcqE5blaMH8Oi9BTzOsaNwOFao
- Motivation: Kubernetes user experience is oriented to operators, want better "inner loop" (build, run, test, debug) process for app developers
  - today's Kubernetes "inner loop" development process: code, build, push, run
  - desire to schedule in k8s alongside services _not_ in development,  but in K8s we use configmaps, secrets, volumes; these are not available in localhost
- Proposal:
  - Build and run local container as host connected to in-cluster pods and services
  - Use local connected container to build, test, and run services connected to in-cluster services
  - Example: exec into dev container and run `go run main.go` to replace the running process
- Open source
  - https://github.com/nocalhost/nocalhost
  - https://nocalhost.dev/
- Q's
  - Can you build images in Nocalhost? A: No, use other processes.

**Comment by lyzhang1999** [comment]
Additional.

Nocalhost provides an additional Server side, which is optional and used to unify the management of users, clusters, applications and development spaces (based on Namespace isolation).
Developers can connect and login to the Server side from the Nocalhost IDE plug-in for easy application deployment and development.

**Comment by thschue** [comment]
closing this as the presentation already took place and there are no more action items for us
