### ISSUE TITLE
go-zero as CNCF Sandbox project

### ISSUE THREAD

**Issue by kevwan** [cncf/tag-app-delivery#144]
Website: https://go-zero.dev
GitHub: https://github.com/tal-tech/go-zero
Slides: https://docs.google.com/presentation/d/e/2PACX-1vR3ldtUlfIpKy04gbgzWQRl2GYNMzzaLGFK6NQJswJs8tKALhNuGUDl89A4Fs7SRW3ud6aOX1a6VIqn/pub?slide=id.ge058179339_6_65

Request for SIG presentation, thanks!

**Comment by hongchaodeng** [comment]
Hi @kevwan .
This is awesome! You are warmly welcome to present and participate in the SIG.

You can pick a meeting date at your earliest convenience and put a presentation request into the agenda: https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#

We have regular meetings on 1st and 3rd Wednesdays at 8 am Pacific, 11 am Eastern, which is 11pm in China.

Please don't hesitate to ping us in the Slack (#tag-app-delivery) for any questions you have. I look forward to more collaboration on this area in the TAG and even a new WG for it in the future.

**Comment by thschue** [comment]
Will close this issue as there are no further action items associated with it.
