### ISSUE TITLE
[cooperative-delivery-wg] give WG chairs access to create events on CNCF community tag-app-delivery group

### ISSUE THREAD

**Issue by scottrigby** [cncf/tag-app-delivery#151]
Can [Cooperative Delivery WG](https://github.com/cncf/tag-app-delivery/tree/master/cooperative-delivery-wg) chairs please be granted access to creating events on https://community.cncf.io/tag-app-delivery/?

Chairs are @roberthstrand and @joshgav

See #152

**Comment by thschue** [comment]
We added the wg meetings for the next 6 months to the community page. If you need additional events, please reach out.
