### ISSUE TITLE
[cooperative-delivery-wg] Update CODEOWNERS file to allow chairs to manage WG dir

### ISSUE THREAD

**Issue by scottrigby** [cncf/tag-app-delivery#153]
See #152 

Chairs are @roberthstrand and @joshgav

- [x] Add @roberthstrand and @joshgav to [CODEOWNERS](https://github.com/cncf/tag-app-delivery/blob/master/CODEOWNERS) in this repo for `/cooperative-delivery-wg`
- [x] Ensure they have write access to this repo (this can be done either as external collaborators, or a team in the org) see this note on [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):
    > The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

**Comment by AlexsJones** [comment]
https://github.com/cncf/tag-app-delivery/pull/162

**Comment by roberthstrand** [comment]
While codeowners looks good, we (or at least me, not sure about @joshgav) don't have any write access which still would mean that we have to rely on others to get stuff merged. The only difference would be that one would get asked to approve requests, nothing more. As long as there is a default codeowner and the branch protection is set to require codeowner approval, giving write access shouldn't be that dangerous. Personally, I'd set up teams on organizational level then you would have an easy way of managing who has access. But that might be difficult as it's under CNCF jurisdiction. 

Is there anything blocking giving that kind of access out to us, anything we need to sign or what-have-you?

**Comment by roberthstrand** [comment]
Example from #165: I would still have to wait for everyone to approve instead of having a team as code owner and just require one approval, and then @joshgav or me could have been added to that team which has write access so that we could speed up the approval process.
