### ISSUE TITLE
[gitops-wg] Grant WG maintainers+chairs write access to repo so CODEOWNERS file allows managing WG dir

### ISSUE THREAD

**Issue by scottrigby** [cncf/tag-app-delivery#154]
See https://github.com/cncf/tag-app-delivery/pull/146

GitOps WG chairs: @murillodigital @scottrigby @todaywasawesome
GitOps WG maintainers: @chrispat @csand-msft @todaywasawesome @jlbutler @murillodigital @scottrigby

- [ ] Ensure WG maintainers have write access to this repo (this can be done either as external collaborators, or a team in the org) see this note on [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):
    > The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

**Comment by AlexsJones** [comment]
Can you confirm this has been done for you @scottrigby ?

**Comment by AlexsJones** [comment]
I will add chairs with write access in the good faith you'll manage the `/gitops/` directory
