### ISSUE TITLE
Demo OAM & KubeVela at sig-app-delivery meeting 

### ISSUE THREAD

**Issue by suhuruli** [cncf/tag-app-delivery#16]
Hello! 

We recently announced [OAM & Rudr](https://openappmodel.io) as open source projects and would love the opportunity to demo it at the upcoming sig-app-delivery meeting. 

OAM is a spec for building cloud native applications and Rudr is an implementation on Kubernetes that accepts this specification. These projects fit in nicely with [Topic 1](https://docs.google.com/document/d/1gMhRz4vEwiHa3uD8DqFKHGTSxrVJNgkLG2WZWvi9lXo/edit#) for this sig and feedback from this group especially would be amazing in these early stages of the release. 

The agenda would be: 

5 minutes: Introduction to OAM and the goals 
10 minutes: Demo how to author the spec and deploy to Rudr 

Look forward to this opportunity!

**Comment by AloisReitbauer** [comment]
What would you see as follow up items here?

**Comment by tomkerkhove** [comment]
Any input on this @suhuruli?

**Comment by suhuruli** [comment]
Hi! Sorry for the late reply here. I think the follow up items here should be to help the SIG nail down the paper we were authoring and then from there see if OAM is the right project to solve problems identified by the SIG.

**Comment by thschue** [comment]
Did this presentation take place? Otherwise (and even if it already happened), it might be exciting to get a demonstration of the OAM (and a possible implementation) in one of the next TAG meetings.

**Comment by resouer** [comment]
@thschue , I believe @hongchaodeng could show off the latest application deployment workflow defined by OAM in KubeVela.

**Comment by thschue** [comment]
This would be very nice. @hongchaodeng: How do you think? Should we schedule this for one of the next meetings?

**Comment by hongchaodeng** [comment]
Sure. I can handle it. I will add it to the meeting doc once slides & demo are ready.

**Comment by thschue** [comment]
@hongchaodeng: Have you got any news regarding the presentation? Would September, 21st be ok for you?

**Comment by joshgav** [comment]
This issue seems to have been lost, let's close it.
@hongchaodeng and @thschue ping us in Slack and add your item to [our agenda](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit) if/when you want to share. Thanks!
