### ISSUE TITLE
Enable discussions on repository

### ISSUE THREAD

**Issue by roberthstrand** [cncf/tag-app-delivery#164]
We just had a cooperative-delivery-wg meeting and we started to talk about how to collaborate on finding pain points or scenarios from which a delivery pattern could be defined. In my opinion, that is precisely the job for GitHub discussions.

Is this something we could enable? Off the top of my head I think having two categories for Cooperative Delivery would be great, for instance one open ended called `cooperative-delivery` and one something like `cooperative-delivery-patterns` that is set up as a Q/A style category.

**Comment by lloydchang** [comment]
LGTM

Similar to https://github.com/open-gitops/project/discussions and https://github.com/open-gitops/documents/issues/44

**Comment by hongchaodeng** [comment]
The discussion feature is enabled: https://github.com/cncf/tag-app-delivery/discussions

**Comment by roberthstrand** [comment]
Thanks a bunch @hongchaodeng, I appreciate it 🖖
