### ISSUE TITLE
Pattern proposal: Provision databases and their bindings on demand from any provider

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#168]
## Why?
Developers want to deploy typical database systems like PostgresQL to one of several providers without having to select the provider in advance. Developers also need credentials and URLs for provisioned databases to be injected for app code to use at runtime, rather than at build time or earlier.

This pattern will show how to delay selection of a database provider till runtime and inject required binding info in a uniform way at runtime for apps to use.

## How?

Following are some implementation proposals I intend to start with; tips and other recommendations are welcome!

- Use [Crossplane](https://github.com/crossplane/crossplane) to provision a PostgresQL database system from any of at least four providers: Azure, AWS, GCP and [CrunchyData](https://www.crunchydata.com/).
- Research binding providers and use one that can provide the exact same experience regardless of which provider provisions the actual database. Potential candidates include:
    - service-binding-operator: <https://github.com/redhat-developer/service-binding-operator>
    - Vault agent and secret engines: <https://github.com/hashicorp/vault/tree/main/command/agent>
    - Secrets Store CSI driver: <https://github.com/kubernetes-sigs/secrets-store-csi-driver>
- Run an API service in a container which simply allows CRUD of database records. Several frameworks should be able to consume the same bindings published in the previous step.
    - Initial examples will be in Java (Spring Boot or Quarkus) and Node.js.
- Finally, demonstrate how to deploy these components reliably and in order using _TBD_ - will start with shell scripts.

**Comment by thschue** [comment]
Closing this issue as there are no further action items associated with it.
