### ISSUE TITLE
Discuss Application Definition and Air-gapped Scenarios 

### ISSUE THREAD

**Issue by jeremyrickard** [cncf/tag-app-delivery#19]
At the SIG intro session at KubeCon NA 2019, there were a few questions about how air-gapped scenarios fit in or can be enabled by tooling in the landscape.

It would be good to have a discussion and maybe develop some best practices, an article or blog post that addresses these scenarios. 

In the CNAB world, we’ve been considering these use cases and would be happy to share our experiments and learnings at a SIG meeting or on the mailing list! 

Cc: @AloisReitbauer @radu-matei

**Comment by glyn** [comment]
The [airgap](https://github.com/cnabio/cnab-spec/blob/master/805-airgap.md) section of the CNAB spec provides a gentle introduction for anyone who would like it.

**Comment by jeremyrickard** [comment]
Thanks for linking that @glyn

**Comment by AloisReitbauer** [comment]
We could put together a doc outlining best practices.  Would be great to present in one of the upcoming meetings

**Comment by AloisReitbauer** [comment]
@jeremyrickard  can you have a short presentation at the next meeting this Wednesday

**Comment by jeremyrickard** [comment]
@AloisReitbauer sure thing. Should I just go add myself to the agenda for Wednesday(4 December)?

**Comment by jeremyrickard** [comment]
> We could put together a doc outlining best practices. Would be great to present in one of the upcoming meetings

If we want to produce some best practices, I think it might be good to solicit more examples of what people are doing today? We talked a little about CNAB, but we also heard that something in the Operator space was doing something in that vein. There was a comment on the youtube recording from the last meeting about another project that does this. Should we survey and try and find a more and extract some best practices from that survey?

**Comment by thschue** [comment]
There was a WG regarding Air-Gapped scenarios, which was dissolved. Therefore, this issue will also be closed.
