### ISSUE TITLE
Cloud-native app delivery at KubeCon US, Detroit

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/tag-app-delivery#194]
We are investigating to run a pre-conference event before KubeCon EU on App Delivery topics. 

More to come ...

**Comment by joshgav** [comment]
Cool :+1:. I'll help at least virtually!

A suggestion: it would be helpful to gather parties interested in developing CNCF program(s) that would provide example developer-oriented scenarios for education, research and compatibility checks. Projects that are bootstrapping themselves in this area include [podtato-head](https://github.com/podtato-head/podtato-head), the nascent [observe-k8s](https://github.com/observe-k8s) project, and perhaps the [OpenGitOps](https://github.com/open-gitops) project.

<https://github.com/cncf/tag-app-delivery/issues/167> could be a central point of discussion on the topic.

**Comment by joshgav** [comment]
On behalf of the Cooperative Delivery WG, we'd be particularly interested in case studies and presentations on how organizations are coordinating delivery of infrastructure [capabilities](https://joshgav.github.io/2021/08/30/deliver-platform-capabilities.html) with delivery of apps and business logic. For example, @ayushghosh discussed in our last sync a working implementation of something like what's proposed in #168 - it would be great to share a demo and have a discussion.

Our early hypothesis is that patterns for such coordination are today almost always bespoke to each organization. We want to gather these early and existing patterns, learn from them about user requirements and problems, and begin to gather and share common conventions in projects like [podtato-head](https://github.com/podtato-head/podtato-head).

Perhaps others in the WG, including myself and @roberthstrand, could propose, demo and discuss additional potential patterns to further the conversation, such as <https://github.com/podtato-head/podtato-head/issues/134> (Terraform) and <https://github.com/podtato-head/podtato-head/pull/144> (Operator Framework).

Perhaps the discussion could be a combination "birds of a feather" and "lightning talks" session where several folks present working patterns followed by discussion.

**Comment by thschue** [comment]
Requested an app-delivery booth (half-time) and a project meeting (4 hours) for TAG App-Delivery.

**Comment by joshgav** [comment]
I think we're done with this now. Let's open a new one soon to plan for Kubecons 2023.
