### ISSUE TITLE
[multitenancy] Multi-instance multitenancy for delivering applications in SaaS form

### ISSUE THREAD

**Issue by devdattakulkarni** [cncf/tag-app-delivery#200]
### Tenant relationship

A tenant is anyone who needs a complete instance of an application. These could be different groups needing, say, separate instances of Jenkins within the same org. Or it could be end customers of a Wordpress service provider needing separate instance of a Wordpress stack.

### Multitenancy implementation

Multitenancy is achieved by creating separate instances of an application in separate namespaces within a cluster. We use [KubePlus Operator](https://github.com/cloud-ark/kubeplus) for this purpose. 

### Organization

CloudARK (https://cloudark.io/)

**Comment by thschue** [comment]
Will close this issue as there are no further action items associated with it.
