### ISSUE TITLE
[multitenancy] Ensure both flexibility and control to the tenants

### ISSUE THREAD

**Issue by yogeek** [cncf/tag-app-delivery#201]
### Tenant relationship

*teams in the same group*

### Multitenancy implementation

*separate namespaces in one cluster*

We ("platform" team) provides several K8S clusters for different projects inside our organization :

- one K8S cluster per environment (dev, staging, production region 1, production region 2...)

- in each K8S cluster, multiple tenants (teams/projects) can deploy resources in different namespaces

Onboarding process for a new team : when a project wants to be hosted in our platform, they have to do Pull Request in our self-hosted gitlab 'onboarding' repository to

- add their desired namespaces into a YAML file like :
```
project1:
- project1_ns1
- project1_ns2
project2:
- project2_ns1
- project2_ns2
...
```

- optionally add an argocd applicationset custom resource (usually with a 'gitlab generator' for argocd appset controller to autodiscover their git 'deployment' repositories and generate corresponding argocd applications)

- optionally add additional RBAC for specific needs

This PR is reviewed and if merged, the Jenkins pipeline uses a shell script that loops over the projects list and initializes the tenant with an 'admin' kubeconfig to create all the resources :

- creates desired namespaces with a label 'owner=project1' and a label 'netpol-gen=true' (will be used by a kyverno clusterpolicy to generate network policies for these namespaces)

- generates kubeconfigs for this project (1 for the project's admin/sre/devops roles that will allow 'admin-like' permission in the project's namespaces and 1 for devs that will have less permissions)

- generates RBAC for the project to limit their actions to their namespaces

- creates a k8s dockerregistry secret with harbor credentials to pull only project's images from harbor and set the imagePullSecret of the namespace to point to this specific secret

- launch some tests to check the isolation and kubeconfig scope

- applies the potential argocd applicationset resources to automatically generate all project's argocd applications

This is currently done with a shell script using templated YAML for resources like namespaces, RBAC...

(original post [here ](https://github.com/cncf/tag-app-delivery/issues/193#issuecomment-1034512023))

### Pains

- the fact that users have to do a PR to create namespaces was based on the hypothesis that that the "1 namespace per team" pattern would be applied. Some teams are following it, but others (often for legacy reasons) are not. And for them, this process is cumbersome. We would like for the projects to be able to create namespaces on their own while being conformant to the best practices (security, quality...) we want to apply to every tenant to provide a good "cohabitation"
- the shell script that creates namespaces and initializes them is becoming too large and difficult to maintain
- the corresponding deployment pipeline is too long => we would prefer a more GitOps approach
- the script only does creation of namespaces, not deletion (which must be done manually)
- the default K8S RBAC manifest are numerous and very "verbose"
- the whole process it not "dynamic" enough (changing a little piece implies launching the pipeline again on all of our environments to propagate the change to all clusters)

### Suggestions

We are currently studying a full refactoring of the repository to use :

- RBACManager project would simplify and improve the current K8S RBAC approach (https://rbac-manager.docs.fairwinds.com/introduction/#the-benefits)

- kyverno to handle RBACManager resources generation (as we are already doing today for network policies)

- kyverno to handle imagePullSecret secret generation and the NS default serviceaccount corresponding modification

And some other ideas :

- use hierarchical namespaces to give namespaces control back to the projects : we would only handle the 'parent' namespaces creation for each project and leave them the freedom to create all the sub-namespaces they want (all the netpols, secrets, rbac would be propagated from the parent NS to the child NS)

- use a homemade 'Project' CRD for the project to describe their needs in a declarative way and kyverno to generate all needed resources in reaction to a 'Project' CR creation and write a kyverno policy to detect any new 'Project' custom resource and generates all necessary resources in reaction (instead of writing a full controller to do this, we think kyverno can do the job)

(I found it was a bit like what [Capsule](https://github.com/clastix/capsule) proposes with its 'Tenant' CRD, but it would be more specific to our needs. By the way, Kapsule may have been a nice solution for us I think if it existed at the time of we set up our onboarding process...)

- argocd to apply all manifests (namespaces, RBACManagers...) to benefit from auto-reconciliation and auto-pruning of resources

### Organization

Continental

**Comment by thschue** [comment]
Closing this issue as there are no further action items associated with it.
