### ISSUE TITLE
OpenFeature review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#210]
Presented to TAG App Delivery by @toddbaert on 2022-05-04.

- Web site: https://openfeature.dev/
- Code: https://github.com/open-feature
- Spec (WIP): https://github.com/open-feature/spec/tree/main/specification
- Specifies a common API to be implemented (possibly via conversion) by a service provider like LaunchDarkly and others.
- One SDK per language can work with either a) native OpenFeature API _or_ b) any service provider via provider plugins for the SDK (compare to OpenTelemetry exporters).
- No implementations of spec as an API service for now. Maybe in the future.
- SDK allows adding additional “hooks” at time of checking flags
- SDK as a sidecar via operator extracts logic from actual apps into CRDs: https://github.com/open-feature/feature-operator
- Q: Why something specific to feature flags rather than a general configuration management system? Is “feature flags” a special case of general config mgmt?
    - Feature flags must be evaluated dynamically, at run time. Config management systems handle more static info, compare to ConfigMaps.

**Comment by thschue** [comment]
Will close this issue as there are no further action items associated with it.
