### ISSUE TITLE
[GitOps] Update TAG repo access for OpenGitOps maintainers

### ISSUE THREAD

**Issue by scottrigby** [cncf/tag-app-delivery#213]
Step to follow, in order:
- [ ] 1. Merge CODEOWNERS PR first: #212 
- [ ] 2. make sure each user listed in the CODEOWNERS file for `/gitops-wg/` has write access to this repository
    - [ ] @chrispat 
    - [ ] @csand-msft 
    - [ ] @todaywasawesome 
    - [ ] @chris-short 
    - [ ] @murillodigital 
    - [x] @scottrigby 
    - [ ] @christianh814

**Comment by joshgav** [comment]
I'm going to close this as stale. But we'd like to address CODEOWNERship in this repo soon.
