### ISSUE TITLE
[WG Operators] Proposed section: Which types of operators are there and how are they characterized?

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#221]
Which types of operators are there? Are there typical types of operators? How are they characterized?
- Traditional - Install and maintain application lifecycle
- GitOps (add the GitOps Use Case)
* Refine GitOps Controller Use Case (roberth.strand@gmail.com)
- Resource Management (maintain clusters)

**Comment by grzesuav** [comment]
+ I see more patterns when reconciliation should be triggered outside of the cluster (via some events // observing external service) - however not related to gitops
