### ISSUE TITLE
[WG Operators] Proposed section: Operator Performance / Observability

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#224]
- How long does reconciliation take?
- Kubernetes API?
- Sharding Operators
- Pros and cons?

**Comment by grzesuav** [comment]
I asked quesiton in #sig-scalability re this https://kubernetes.slack.com/archives/C09QZTRH7/p1653045221273659 , probably better to reach to that group via mail group ? I attended their talk on kubecon and it seems they can have some insight on operator load on apiserver and probably can give some advice around this

**Comment by grzesuav** [comment]
Regarding sharding, I do not believe many operators use that this days. worth dig a bit why is that.
