### ISSUE TITLE
[WG Operators] Proposed section: Updating CRDs

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#225]
(Jen) Question: is this covering Operator upgrades? Backwards compatibility and operator upgrading plan, etc?

I'm asking Recently I had a big pain with upgrading keda operator for example (v1 and v2 can't run on the same cluster). Would something like common issues and recommended ways to update versions fit here or is this covering a different part (only API/CRD)?

**Comment by grzesuav** [comment]
if operator upgrade is not covered here it would be good to have some issue specific to this. Currently is raises questions, as you can have single operator in a cluster, if cluster is big (or have a lot of CR's) then updating can be challenging
