### ISSUE TITLE
Acorn review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#238]
Thanks to @cloudnautique for presenting [Acorn](https://acorn.io/) at the Sept 7 TAG meeting. Following is a summary of the presentation and Q&A. We'll add a link to the recording once it's published.

## Summary

- Goals of Acorn:
  - focus on app concerns and minimize required K8s knowledge
  - provide a Docker CLI-like experience for Kubernetes
- Acorn CLI packages application code and config in OCI images. Acorn controllers in cluster unpackage the code image, build and configure a runnable image, and deploy required artifacts (Deployment, Service, Ingress, etc.) that run it.
- Configuration is captured in an `Acornfile`; syntax is the CUE-like language [Acornfile Markup Language (AML)](https://github.com/acorn-io/aml).
- `acorn build` bundles code and config in an image file based on the Acornfile and ships it to a cluster to be built; `acorn run` asks the in-cluster controller to deploy.

## Q&A

- What is packaged?
   - manifests and metadata
   - actual images (in tarballs)
   - Acornfile
- What is an Acornfile?
  - "AML" - [Acorn Markup Language](https://github.com/acorn-io/aml) - inspired by CUE
  - ref: <https://docs.acorn.io/reference/acornfile>
  - lots of config, e.g. `expose` to indicate that something should be available from external
- Each `container` in the Acornfile becomes one Deployment in cluster - compare Docker Compose
- Acorn controller and apiserver must first be deployed in cluster with `acorn install`
   - adds capabilities to cluster like builders
   - automates creation of ingresses
- Can additional hooks be applied during build? E.g. to run scans and add standard metadata per policies.
  - A: Under consideration.
- How does the builder work?
    - BuildKit-based builder runs in cluster
    - Can output the build as YAML and then add hooks via Flux or ArgoCD
- Comparisons to other projects
    - Difference from a Helm chart? Are the parameters in a `values.yaml` equivalent to what's in an `Acornfile`? (Can parameterize Acornfile with profiles.)
    - CNAB/Porter - <https://porter.sh/> - Acorn requires less K8s knowledge
    - ketch - <https://www.theketch.io/>
    - Buildpacks builders
- How can Acorns use non-`container` services such as those provided as cloud services or via operators?
    - Can link to an existing service; acorn will add a proxy K8s service
    - Can also get bindings (URL, credentials) from a secret. Acorn uses a custom `secret://` scheme to refer to K8s secrets

**Comment by joshgav** [comment]
I'm not sure if `acorn build` builds the actual runnable image locally and puts it in the OCI image pushed to the cluster, or if only source and config is in the initial image, and the in-cluster controller builds the runnable image. @cloudnautique could you clarify?

**Comment by joshgav** [comment]
We'd love to include Acorn in the delivery scenarios for [podtato-head](https://github.com/podtato-head/podtato-head/tree/main/delivery). It's pretty similar conceptually to [ketch](https://github.com/podtato-head/podtato-head/tree/main/delivery/ketch) so we might copy and paste that as a template.

I opened <https://github.com/podtato-head/podtato-head/issues/172> if someone wants to work it. Thanks!

**Comment by thschue** [comment]
I think there are no more action items, therefore closing this issue
