### ISSUE TITLE
Proposal: Rename "Cooperative Delivery WG" -> "Platforms WG"

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#243]
The TAG has recently discussed (in [Slack](https://cloud-native.slack.com/archives/CL3SL0CP5) and [meetings](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#heading=h.cxeef75dgm9t)) the name of the Cooperative Delivery WG and recommended changing it to **Platforms WG**. We believe the [charter of the Coop Delivery WG](https://github.com/cncf/tag-app-delivery/blob/main/cooperative-delivery-wg/charter/README.md) is aligned with the emerging "platform engineering" movement and by renaming it contributors will more easily grasp and support our mission to facilitate cooperative delivery of infrastructure and applications.

More background on the mission of the Coop Delivery WG and how it parallels the Platforms movement is in this pending blog post: <https://github.com/cncf/tag-app-delivery/pull/242>

We're developing a shared understanding and definition of _Platforms_ in this document: <https://docs.google.com/document/d/1UDL3E5BqPyDdzV1wek9o8xR-nLJQXEEMU1qIMCgq5cI/>. Please comment and contribute, the WG will use that as part of a foundation for whitepapers and deeper analysis.

I'm including the problem statement from [the original TAG charter](https://github.com/cncf/tag-app-delivery/blob/main/cooperative-delivery-wg/charter/README.md) inline here since it illustrates the deep alignment with Platforms:

> In most app-delivery scenarios, the packaging format and delivery mechanism of the application artifacts are targeted, but not necessarily the app's infrastructure dependencies such as data stores and message queues. That is, application and infrastructure delivery are not coordinated. Often, applications are heavily dependent on infrastructure resources that are not directly linked to a specific deployment, and therefore problems with non-existing infrastructure resources might cause deployments to fail. In addition to this, the application and infrastructure lifecycles are not synchronized, creating additional complexity and challenges when delivering workloads.
> 
> Example:
> * Developers using a storage class for testing an application locally that is not available in higher environments.
> * Deployment of an application workload is a separate approval process and journey as to deploying the necessary ingress to route traffic to that service.
> * Delivering complex micro-service architecture and a sustainable GitOps deployment pattern are treated as separate but related workflows.
> 
> Setup of a CI/CD pipeline and its constituent parts to enable the delivery of applications in coordination with infrastructure is part of institutional knowledge and not easily transferable across organization, system nor domain boundaries.
> 
> Additionally, it is often assumed that infrastructure is always available when dealing with application delivery. At some point, it might be useful that infrastructure could also be deployed by GitOps mechanisms and/or using the deployment pipeline. Therefore, there is always a cut between the infrastructure deployment and the application delivery/deployment tooling, which might lead to deployment problems and misconfigurations.
> 
> Currently, it seems that there are no ubiquitous best practices or recommendations for these use cases and no standard for declaring an entire application in a platform-agnostic way.
> 
> There are projects like Crossplane and Terraform primarily used for provisioning infrastructure and other tools like Argo, Flux and Keptn for provisioning applications on that infrastructure . There are also emerging projects like OAM and Dapr to abstract infrastructure and "inject" it automatically on behalf of apps, but these have not (yet) been broadly adopted by implementation providers, i.e. public cloud platforms. This working group should clarify what application and infrastructure coordination could look like and develop best practices for such cases.

I'll create a PR for this change linked to this issue.

cc @roberthstrand

**Comment by chris-short** [comment]
This seems like a smart idea to me. It definitely aligns better with the
state the industry has gone too.

*Chris Short <https://chrisshort.me>*
He/Him/His
TZ=America/Detroit
