### ISSUE TITLE
Create a Working Group for GitOps

### ISSUE THREAD

**Issue by monadic** [cncf/tag-app-delivery#27]
Please create a WG for GitOps.  There are several community members that wish to maintain a document that describes GitOps. 

A very rough starting point for such a doc is here 
https://docs.google.com/document/d/1ZgdtI8ck3DWIig5gBnbS20A0cgzBRlOT3Yv-s1b2c54/edit?usp=drivesdk

**Comment by AloisReitbauer** [comment]
Great idea. Please comment if you are willing to join

**Comment by AloisReitbauer** [comment]
Sharing the process for working groups:

#Introduction
The purpose of working groups are to study and report on a particular question and make recommendations based on its findings. The end result of a working group may be a new project proposal, landscape, whitepaper or even a report detailing their findings. The intention of working groups is not to host a full project or specification. Working Groups can be formed at any time but must be sponsored by a TOC member and voted with a super majority vote by the CNCF TOC. The TOC can also shut down a working group with a super majority vote.

#Process
If you would like to submit a working group proposal, please submit a pull request to the working groups folder. As an example, you can see the other working group proposals here: https://github.com/cncf/toc/tree/master/workinggroups *(I will take care of this)*

You will also have to present to the CNCF TOC and wider community before your WG proposal will be voted upon by the TOC and community. You can request a presentation by filing an issue here: https://github.com/cncf/toc/issues

At a minimum, please include this information:

Goals
Non-goals
Mailing list information
The location of meetings / agenda / notes
Initial interested parties to show that there are multiple people across multiple orgs interested
The chair(s) and TOC sponsor being explicitly listed so they are discoverable

**Comment by AloisReitbauer** [comment]
Here is the draft document for the WG to get it ready for submission:

https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit?usp=sharing

**Comment by todaywasawesome** [comment]
+1 and speaking for Codefresh we're very engaged here.

**Comment by AloisReitbauer** [comment]
Please add your name to the doc as well. Thx!

**Comment by scottrigby** [comment]
> Great idea. Please comment if you are willing to join

@AloisReitbauer I'm happy to attend and help contribute to the WG. Also added/proposed my name to the draft doc.

**Comment by todaywasawesome** [comment]
Added you on slack, excited to have you Scott!
