### ISSUE TITLE
[WG Platforms] Platforms Def - What is a platform

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#273]
Review and finalize "What is a platform" section of Platforms whitepaper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#what-is-a-platform>

**Comment by abhinavm-rafay** [comment]
@joshgav it'd be great to potentially own this section if possible would love to add some details here as well as helping solicit feedback let me know if that works!

**Comment by joshgav** [comment]
Thank you @abhinavm-rafay, that would be great, I went ahead and assigned you here; we can add others if appropriate.

As we chatted, let's try making significant edits via PRs to the `platforms-v1alpha1` branch, and having discussions here or in distinct issues as you feel appropriate. Thank you!

**Comment by jkleinlercher** [comment]
> It seems like we have some doubts about the naming. We opted for talking about "platforms" in general, but as also understandable from Matthew Skelton's [comment](https://cloud-native.slack.com/archives/C020RHD43BP/p1673522113762099?thread_ts=1673388246.346779&cid=C020RHD43BP), that term is too generic and we probably need to be more specific.


> Therefore, an "application platform" (or "internal developer platform/IDP") would be a type of cloud native platform that supports the path to deliver value to the application end-users, from idea to production. But there are more.
> 
> Other types of cloud native platforms would be:
> 
> * core platform (containing only the services necessary to offer a Kubernetes-based environment with security, compliance and access control that could provide the foundation to build special-purpose platforms on top of it).
> * deployment platform (focused on the final part of the path to production)
> * data platform (oriented to big data or ML use cases)
> * observability platform (offering services to monitor, visualize, and work with telemetry and other signals coming from different sources, including other platforms).

I wonder if an "application platform" (which supports the path to deliver value to the application end-users, from idea to production) consists of a deployment platform and observability platform? The path from idea to production always needs deployment and observability, isn't it?

> These categories are not standard terminology, so I wouldn't try to use them here. At least, not in this first paper. I would talk more in general about "cloud native platforms" with focus on how we build them, both from a technical and an organisational point of view, and how to provide the best user experience. I'm not a fan of the "developer platform" terminology because application developers are not the only users of the platform. I think that the UX is critical for all users of the platform.

Totally agree, we also had platform users who hosted third-party applications on our platform, but they weren't developers. Although they used the same APIs (gitops-repos, gitlab-pipelines) to deploy there applications on the platform. However, they didn't develop the applications by themselves.

What do you think about the term "container platform"?

**Comment by krumware** [comment]
Just raising my hand to help here 👍

**Comment by AaronFriel** [comment]
I'd like to add the Pulumi name & logo for the diagram in this section, likely best fitting in "provide environments and resources". In addition to being a CLI, Pulumi has the Automation API, an SDK to allow platform teams to integrate provisioning in their services, and a Kubernetes operator for provisioning via programs defined as k8s resources in YAML.

I can make a PR to add to the table under #279, however the image is a blob and I don't want to race anyone on trying to edit the diagram in Google Docs.

**Comment by ThomasVitale** [comment]
> > It seems like we have some doubts about the naming. We opted for talking about "platforms" in general, but as also understandable from Matthew Skelton's [comment](https://cloud-native.slack.com/archives/C020RHD43BP/p1673522113762099?thread_ts=1673388246.346779&cid=C020RHD43BP), that term is too generic and we probably need to be more specific.
> 
> > Therefore, an "application platform" (or "internal developer platform/IDP") would be a type of cloud native platform that supports the path to deliver value to the application end-users, from idea to production. But there are more.
> > Other types of cloud native platforms would be:
> > 
> > * core platform (containing only the services necessary to offer a Kubernetes-based environment with security, compliance and access control that could provide the foundation to build special-purpose platforms on top of it).
> > * deployment platform (focused on the final part of the path to production)
> > * data platform (oriented to big data or ML use cases)
> > * observability platform (offering services to monitor, visualize, and work with telemetry and other signals coming from different sources, including other platforms).
> 
> I wonder if an "application platform" (which supports the path to deliver value to the application end-users, from idea to production) consists of a deployment platform and observability platform? The path from idea to production always needs deployment and observability, isn't it?

I also see an "application platform" as one that comprises all the necessary capabilities to go from idea to production. But I wouldn't define it in terms of a combination of other platform types. In general, I see a "pool" of capabilities that are composed together to achieve a well defined goal. What capabilities to include depends on what we are trying to achieve. Which is why I wouldn't focus too much on platform types, besides providing examples.

> > These categories are not standard terminology, so I wouldn't try to use them here. At least, not in this first paper. I would talk more in general about "cloud native platforms" with focus on how we build them, both from a technical and an organisational point of view, and how to provide the best user experience. I'm not a fan of the "developer platform" terminology because application developers are not the only users of the platform. I think that the UX is critical for all users of the platform.
> 
> Totally agree, we also had platform users who hosted third-party applications on our platform, but they weren't developers. Although they used the same APIs (gitops-repos, gitlab-pipelines) to deploy there applications on the platform. However, they didn't develop the applications by themselves.
> 
> What do you think about the term "container platform"?

I see "container platform" as a type of cloud native platforms. Perhaps one I could use as a developer to provide a pre-built container image, and then the platform takes care of the rest. But I wouldn't expect the platform to take care of provisioning databases on Azure (just to make an example), or to take care of supporting the entire software supply chain, or to provide a temporary development environment. But that is a very subjective description, which is one of the reasons why I prefer focusing more on the general architectural style ("cloud native") and the several capabilities that might be part of the final product (in a flexible and composable fashion).

**Comment by Saim-Safdar** [comment]
**Looking for thoughts and opinions of others on this**, To build a platform that can offer services to thousands of customers, cloud providers have an underlying control plane that ensures the desired state of infrastructure that a customer has requested is aligned with the actual state.

If they are not already, the control plane will work to drive the two states to alignment. In simplest terms, the control plane is what translates from the interface exposed to users to actions required to satisfy their requests. A platform is an API that the control plane exposes. **A lot of companies like Upbound and many others**, here's how to drive the conversation, and here's how they think about the platform, looking for opinions do you think these sentences and terms fall under the definition, if yes, I'm thinking we can drive a similar story forward.

**Comment by krumware** [comment]
@AaronFriel, we're working on a different place to include examples and other resources. (cc'ing @joshgav)

Can you please move your request into the Capabilities section? https://github.com/cncf/tag-app-delivery/issues/279

**Comment by abhinavm-rafay** [comment]
> Similarly, I like talking about "cloud native platforms" as an architectural style to design and implement platforms that thrive in cloud environments (but they don't have to necessarily run there). That architectural style could be applied to support multiple use cases resulting in different categories of platforms, all sharing the same architectural principles and properties (the ones listed in the paper as "key attributes").

Hi @ThomasVitale 

I agree with this as well. The problem is if we get too broad it might not be as impactful for those who are adopting cloud native technologies and need some guidance on what direction to go in. The goal is to provide a clear pathway for those enterprises and companies who have adopted data center/cloud technologies today and are transitioning to building platforms via cloud-native but need some guidance. 

@joshgav Any thoughts here?

**Comment by abhinavm-rafay** [comment]
> **Looking for thoughts and opinions of others on this**, To build a platform that can offer services to thousands of customers, cloud providers have an underlying control plane that ensures the desired state of infrastructure that a customer has requested is aligned with the actual state.
> 
> If they are not already, the control plane will work to drive the two states to alignment. In simplest terms, the control plane is what translates from the interface exposed to users to actions required to satisfy their requests. A platform is an API that the control plane exposes. **A lot of companies like Upbound and many others**, here's how to drive the conversation, and here's how they think about the platform, looking for opinions do you think these sentences and terms fall under the definition, if yes, I'm thinking we can drive a similar story forward.

@Saim-Safdar Agreed on this and this kind of ties in with thomas's comment as well. there is an intended desired state that developers request for and some underlying component/control plane that takes care of this in terms of reconciliation and operations. Not all of this can be delegated simply to the cloud provider because there are other things that need taking care of for example authentication or invoking APIs across multiple cloud platforms to deploy the entire app stack.

**Comment by ThomasVitale** [comment]
> > Similarly, I like talking about "cloud native platforms" as an architectural style to design and implement platforms that thrive in cloud environments (but they don't have to necessarily run there). That architectural style could be applied to support multiple use cases resulting in different categories of platforms, all sharing the same architectural principles and properties (the ones listed in the paper as "key attributes").
> 
> Hi @ThomasVitale
> 
> I agree with this as well. The problem is if we get too broad it might not be as impactful for those who are adopting cloud native technologies and need some guidance on what direction to go in. The goal is to provide a clear pathway for those enterprises and companies who have adopted data center/cloud technologies today and are transitioning to building platforms via cloud-native but need some guidance.
> 
> @joshgav Any thoughts here?

Yeah, I agree that it's important to give some concrete examples to make it clear to the reader.

**Comment by ThomasVitale** [comment]
> > **Looking for thoughts and opinions of others on this**, To build a platform that can offer services to thousands of customers, cloud providers have an underlying control plane that ensures the desired state of infrastructure that a customer has requested is aligned with the actual state.
> > If they are not already, the control plane will work to drive the two states to alignment. In simplest terms, the control plane is what translates from the interface exposed to users to actions required to satisfy their requests. A platform is an API that the control plane exposes. **A lot of companies like Upbound and many others**, here's how to drive the conversation, and here's how they think about the platform, looking for opinions do you think these sentences and terms fall under the definition, if yes, I'm thinking we can drive a similar story forward.
> 
> @Saim-Safdar Agreed on this and this kind of ties in with thomas's comment as well. there is an intended desired state that developers request for and some underlying component/control plane that takes care of this in terms of reconciliation and operations. Not all of this can be delegated simply to the cloud provider because there are other things that need taking care of for example authentication or invoking APIs across multiple cloud platforms to deploy the entire app stack.

That's a very good point and an important aspect we could elaborate later in the document (perhaps "attributes of platforms"?). Having the platform as a "universal control plane" makes it possible to manage any tool in a consistent and unified way (either running on k8s or externally), while still allowing flexibility to organisations that don't have to go through a big-bang migration but can proceed in small steps and continue using existing tools they spent a lot of money to establish over the years. With the different being that they are integrated with the platform for unified management and control. I really like how Victor Farcic (Upbound) explains this concept in this episode of his show: https://www.youtube.com/watch?v=j5i00z3QXyU

**Comment by krumware** [comment]
Lots of great thoughts and progress here!
A couple of quick opinions from me:

There is lots of chatter in general in the other issues and slack around examples that are "platforms as a product" and I believe this paper should be focused on helping to point out problems, approaches, and solutions experienced by people, etc, not necessarily what a platform should look/function like. It's up to the products themselves to define the user experience and how they solve problems in their own unique ways, and to what depth.  Those are the same decisions these teams will make when they start developing their own platforms.

To me, the platform is the (almost literal) sandbox that teams play in together to get work done. It's the tangible place folks can go get the information they need, create the resources they need, operate within guardrails, etc, in ways that also fit the business requirements. Not a "one PaaS that rules them all", but an understood collection of tools that work together.

While this isn't a maturity model, and maybe it will grow into one in the future, there should be flexibility in the definition of a platform to make it so it doesn't require 'doing all the things' as some sort of conformance for being a platform.

**Comment by joshgav** [comment]
@ThomasVitale 

> I would talk more in general about "cloud native platforms" with focus on how we build them, both from a technical and an organisational point of view, and how to provide the best user experience. I'm not a fan of the "developer platform" terminology because application developers are not the only users of the platform.

> I like talking about "cloud native platforms" as an architectural style to design and implement platforms that thrive in cloud environments (but they don't have to necessarily run there). That architectural style could be applied to support multiple use cases resulting in different categories of platforms, all sharing the same architectural principles and properties (the ones listed in the paper as "key attributes").

:heart:

I also prefer to call these platforms "cloud" or "cloud-native" platforms, and I also think "cloud" or "cloud-native" is a new architectural style enabled by such platforms. I wrote about it a while ago FWIW: <https://blog.joshgav.com/posts/cloud-redefined-infrastructure>

IMO "developer" is a bit of a distraction as the value of a cloud platform is mostly in accelerating delivery of value and that doesn't _have_ to involve application developers - think of commercial-off-the-shelf (COTS) software operators, data scientists, information workers, etc. An overemphasis on developers may also be questioned by enterprise leaders.

It has led to heated discussion when an adjective is proposed, and so in fact that's why the WG is just called "Platforms" :laughing:. But I think we might be able to get consensus on "cloud-native platforms" - after all we're developing this as the "cloud-native computing foundation".

@ThomasVitale

> In general, I see a "pool" of capabilities that are composed together to achieve a well defined goal. What capabilities to include depends on what we are trying to achieve. Which is why I wouldn't focus too much on platform types, besides providing examples.

> Other types of cloud native platforms would be:
> - core platform (containing only the services necessary to offer a Kubernetes-based environment with security, compliance and access control that could provide the foundation to build special-purpose platforms on top of it).
> - deployment platform (focused on the final part of the path to production)
> - data platform (oriented to big data or ML use cases)
> - observability platform (offering services to monitor, visualize, and work with telemetry and other signals coming from different sources, including other platforms).

@abhinavm-rafay

> The problem is if we get too broad it might not be as impactful for those who are adopting cloud native technologies and need some guidance on what direction to go in. 

How about we list these "types of platforms" as use cases in the ["Why are platforms valuable" section](https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#why-are-platforms-valuable)?

We would describe the core notion of cloud-native platforms as collections of integrateable capabilities first, then describe specific sets of such capabilities for particular use cases next.

**Comment by joshgav** [comment]
@jkleinlercher

> What do you think about the term "container platform"?

Overcoming the notion of a container "platform" may in fact be part of the reason to publish this paper :laughing:. That is, containers are interesting but they're just one form of compute in a broad platform of capabilities; there are other forms of compute and other capabilities required to build cloud-native apps. Just to illustrate, an enterprise _could_ adopt a build-from-source-oriented compute paradigm using e.g. Knative and hide containers from developers.

@Saim-Safdar 

> cloud providers have an underlying control plane that ensures the desired state of infrastructure that a customer has requested is aligned with the actual state

Yes! I agree that this is the implementation of a platform many of us believe in, and not coincidentally Kubernetes' controller-manager (or "operator") framework embodies it. FWIW I wrote about that here: <https://blog.joshgav.com/posts/kubernetes-isnt-about-containers>.

I'm not sure I'd go so far as to say a reconciliation-oriented approach is _required_ for a platform though. For example, some folks may prefer to imperatively run Terraform commands. I think the top-level requirement is to choose and implement _consistent_ interfaces to a _complete_ set of capabilities in some way that fits the needs of the organization and platform users.

Thoughts?

**Comment by abhinavm-rafay** [comment]
@joshgav I like the idea of the types of platforms 

I think we should also think about this from a persona point of view. We have builders and consumers. The builders are typically platform admins. Users can be a developer but can be anybody including platform users or other types of admins themselves. They could be doing security, fin ops, anything. 

I think for the paper it should be giving them direction in terms of 
- what are the pain points today - stitching disparate solutions, not able to create self-service models across your org for different personas, not able to launch new capabilities fast because of governance issues and security 
- what are different types of platforms 
- what should a platform encompass - talk about it at a core level, needs to address builder and consumer in terms of solving for some key KPIs (need to lahnch capabilities fast, need a way to authenticate different users) , can have some key capabilities, we can point out examples 

I think the key is that while we don't want to be too prescriptive in saying it has to be this way, we should point out some key considerations that organizations need to think about. For example, in order to scale a governance model is needed so that users of the platform don't do anything out of compliance or anything insecurely. 

@ThomasVitale @krumware @Saim-Safdar would love to know your thoughts here

**Comment by Saim-Safdar** [comment]
@joshgav +1 for the idea of the types of platforms
But the challenge is, as with Kubernetes, comes in many flavors, the platform comes in many flavors, and we need to tell what, when, why, and how to operate, for each of the types of platforms we are about to choose, which ends up in a debate for a certain type of scenario you need this plus a unification of observability platform plus data platform, we might need to have an answer ready for cross-sectional and unification, this might lead us to forget about the core problem we are addressing here, what platform actually does best, I believe we can use the cloud-native maturity model as in conjunction with defining the platform, as we can say the platform has a bear minimum of what tools people use most and ready for interoperability for day 02. 

Developer platforms influence the developer experience by letting the [99% developer](https://future.com/software-development-building-for-99-developers/) focus on coding without worrying about infrastructure or how to run their software. But many platforms are also designed with the flexibility to let the 1% developer explore and experiment. The developer platform, supported by architecture, [DevOps](https://blog.getambassador.io/is-platform-engineering-the-new-devops-or-sre-472ed97a1885) and SRE teams, contains the ingredients of transformation for all of these teams and roles, fueling improvement in the developer experience, which fuels faster, safer software releases.  Words are taken from [this article](https://thenewstack.io/platform-engineering-in-2023-dev-first-collaboration-and-apis/)

What I try to understand here is who is the most consumers or end-user of the platform, is it a developer, SRE, DevOps, FinOps or we can name it, if we have an answer ready, we need to focus more on that consumer and drive the opinion of the community about other roles and we can pinpoint about the bear minimum for others consumers of the platform users. For example, here's the consumer needs platform most of the time, for this certain activity:

1. Creating a service that automatically deploys to the platform 
2. Editing secrets and automatically redeploying the service 
3. Deploying a branch to a new environment 
4. Accessing logs 
5. Seeing resources that a service consumes For each use case,

**Comment by abangser** [comment]
Hey all, just following along with interest given the why section will need to make sense with the changes y'all implement.

One thing I am seeing in this thread is a thread of conversation that seems to be moving towards defining concrete platforms that I _think_ is taking us away from the original intention.

I want to bring back the comment from @krumware about a focus on platform as a product that will evolve with the org:
> There is lots of chatter in general in the other issues and slack around examples that are "platforms as a product" and I believe this paper should be focused on helping to point out problems, approaches, and solutions experienced by people, etc, not necessarily what a platform should look/function like.

Two trends I am seeing in this conversation are:
1. **Defining platform types** The attempt to concretely list types of platforms may lead us down a path that makes readers think we are providing a blue print to success. E.g. "if I just create 4 teams for the core, deployment, data and observability platforms my organisation will be successful". I believe this was an anti pattern when we were previously discussing goals for the paper.

1. **THE platform** I think this may be a knock on from the point above, but we seem to be falling into a pattern of talking about THE platform when in our calls I hear people advocating that the platform is the same as any product: Start with something valuable, extend it to cover more uses, and of course split it into more manageable domains as necessary when you need to.

To wrap up, this is a really interesting thread, and as a (mostly) observer I just wanted to share what I am witnessing in hopes it helps converge the interesting ideas into the right set of messages for _this_ white paper. It would be great to refer back to the intention of the paper more (and put that in writing if it isn't already) so that we can all better check that we are staying on course for this paper and allowing other interesting topics to evolve into their own offerings.

**Comment by abhinavm-rafay** [comment]
Hi @abangser 
I agree with this sentiment. Ultimately every organization will have a different version of a platform that fits best to their organization. What we need to do is describe the pain points and give some guidance in terms of key things to look out for key capabilities that are worth investigating etc without getting too prescriptive

this is why imo as I had mentioned in the call a week or two ago that we should have the why section first, or relevant personas. It's hard to describe what is a platform without describing the state of platform teams, what the pain points of platform engineers and developers are and why platforms are needed. I believe putting the why first also allows us to focus more on breadth from the very beginning  

@joshgav @abangser let me know your thoughts here but I do think some kind of problem statement and why we're talking about this is crucial before a what is a platform section.

**Comment by joshgav** [comment]
Thank you all for your thoughts. I think we're all agreeing on the notion of platform _types_, and also agreeing that we _don't_ want to talk about them much in this top-level doc. That is, we specifically _don't_ want to a) canonically define any specific "types" (aka "use cases", "scenarios", "archetypes") or b) get particularly deep into how to implement any given type.

OTOH this conversation leads us to think of getting a bit more prescriptive in later work - for example we might describe a specific type in conjunction with an actual prototype of that type as worked in #293, and reference it from a doc exploring platform types.

My suggestion is we iterate on the existing 6 (2 x 3) use cases listed in the ["Why Platforms"](https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#why-are-platforms-valuable) section - perhaps one app dev use case, one data science use case and one third-party COTS use case? Our goal with the examples should be to illustrate and help folks understand platforms, again not to formalize any "types" or get too prescriptive. I'll add this suggestion to #274 too.

**Comment by abangser** [comment]
For those interested, I have taken a stab at swapping the order of why and what sections. Please join in commenting on if this is a useful change in general, and more specifically what about the change would need to change if we were to merge it 🙇‍♀️ 

https://github.com/cncf/tag-app-delivery/pull/294

**Comment by joshgav** [comment]
Thank you all for #309, #305, #301, #294, #289 and more. The paper is much better after your contributions!
