### ISSUE TITLE
[WG Platforms] Platforms Def - Why platforms

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#274]
Review and finalize "Why are platforms valuable" section of Platforms whitepaper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#why-are-platforms-valuable>

**Comment by taras** [comment]
I'll support @abangser on this

**Comment by krumware** [comment]
I'll support

**Comment by Saim-Safdar** [comment]
I want to work on this section and add my opinions

**Comment by Saim-Safdar** [comment]
I have come across this article published by [crossplane community,](https://thenewstack.io/crossplane-a-package-based-approach-to-platform-building/) the article addresses some of the pain points of platform teams and is mostly related to capabilities provided by cross-plane providers and composition, but the statement attached here can be a good fit for **why platform** The process of onboarding a new vendor in a large enterprise is long and arduous. While organizations frequently have a uniform set of checks that any software must undergo before it can be adopted, the process inevitably leads to special cases being identified as unique to each vendor. This creates an inefficient iteration cycle that can last months — time in which the vendor could have been providing value to the customer. I believe some points can be carried forward to the why the need for a platform or please do correct me if I'm making some wrong assumptions here. I'm thinking we can uniquely add the linkage between the sentences (unified pain points of enterprises ) to create the story forward in terms of content writing.

**Comment by abangser** [comment]
Thanks for sharing that link @Saim-Safdar! I also found that to be a great write up.

Specifically focusing on the pain point you are highlighting:

> The process of onboarding a new vendor in a large enterprise is long and arduous.

I can actually see this as both a problem that can be exacerbated by a platform as much as solved by one. Once onboarded, a platform can speed up vendor adoption across an organisation, but often a platform team can create friction between the team needing the tool and the onboarding of that tool if it is not widely confirmed as needed.

I would be really curious to see how you might fit this in, would you be up for creating a comment / pull request with the addition you envision? That may help me understand better!

**Comment by Saim-Safdar** [comment]
@abangser I have some opinions on addition but need to research more on this phrase "but often a platform team can create friction between the team needing the tool and the onboarding of that tool if it is not widely confirmed as needed." I see this happen in many places, what I get here is when we create a story for **why platform** might we choose the words some see as wins and others as loses  **a platform can speed up vendor adoption** but at the same time steep learning curve, create friction and take away the liberty of customization, or creating an extra abstraction.

**Comment by abangser** [comment]
Calling attention to [this comment](https://github.com/cncf/tag-app-delivery/issues/273#issuecomment-1398743895) that may want to get worked in here:

> @ThomasVitale
> 
> In general, I see a "pool" of capabilities that are composed together to achieve a well defined goal. What capabilities to include depends on what we are trying to achieve. Which is why I wouldn't focus too much on platform types, besides providing examples.
> 
> Other types of cloud native platforms would be:
> 
> core platform (containing only the services necessary to offer a Kubernetes-based environment with security, compliance and access control that could provide the foundation to build special-purpose platforms on top of it).
> deployment platform (focused on the final part of the path to production)
> data platform (oriented to big data or ML use cases)
> observability platform (offering services to monitor, visualize, and work with telemetry and other signals coming from different sources, including other platforms).
> @abhinavm-rafay
> 
> The problem is if we get too broad it might not be as impactful for those who are adopting cloud native technologies and need some guidance on what direction to go in.
> 
> How about we list these "types of platforms" as use cases in the ["Why are platforms valuable" section](https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#why-are-platforms-valuable)?
> 
> We would describe the core notion of cloud-native platforms as collections of integrateable capabilities first, then describe specific sets of such capabilities for particular use cases next.
> @joshgav 

I believe there is still some chat going on before any concrete changes are made, but should make sure to address this before we close this issue.

**Comment by joshgav** [comment]
As mentioned in https://github.com/cncf/tag-app-delivery/issues/273#issuecomment-1408779622 let's think about refining the list of use cases to reflect our initial hypotheses of typical ones, I suggested web app dev, data science, and third-party COTS systems. Goal here is to be illustrative, far from prescriptive. WDYT?

**Comment by abangser** [comment]
Quick check in. The paper has moved on quite a bit since the comments on this issue so I want to touch base with interested parties as we close out the last week before finalising it.

@taras @krumware @Saim-Safdar @joshgav, can you please take a look at the paper (and specifically the Why section) and update any questions/comments/concerns you may have here or via a PR? Thanks!

**Comment by abangser** [comment]
Hi all, I am headed on vacation for a bit so won't be super responsive here as we enter our final days of review.

Thank you to everyone for their hard work and great ideas on this section and the paper as a whole. I believe I can consider this section wrapped up pending the final working group call on Tuesday (Feb 28).

@taras / @joshgav please do not block on me if any new ideas come up and you want to incorporate them!

**Comment by joshgav** [comment]
Thank you all for #309, #305, #301, #294, #289 and more. The paper is much better after your contributions!
