### ISSUE TITLE
[WG Platforms] Platforms Def - Platform attributes

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#275]
Review and finalize "Attributes of a platform" section of Platforms whitepaper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#attributes-of-platforms>

**Comment by ThomasVitale** [comment]
I volunteer to lead this section

**Comment by joshgav** [comment]
Thank you all for #309, #305, #301, #294, #289 and more. The paper is much better after your contributions!
