### ISSUE TITLE
[WG Platforms] Platforms Def - Platform team attributes

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#276]
Review and finalize "Platform team attributes" section of Platforms whitepaper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#attributes-of-platform-teams>

**Comment by taras** [comment]
I would like to provide some input about DX teams

**Comment by joshgav** [comment]
@roberthstrand did you want to be responsible for this with Taras? Assignees will gather edits and help finalize the content by 2/28.

**Comment by roberthstrand** [comment]
Yes please, @joshgav 😄

**Comment by joshgav** [comment]
Thank you all for #309, #305, #301, #294, #289 and more. The paper is much better after your contributions!
