### ISSUE TITLE
[WG Platforms] Platforms Def - Platform challenges

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#277]
Review and finalize "Challenges of platforms" section of Platforms whitepaper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#challenges-with-platforms>

**Comment by joshgav** [comment]
Consider integrating challenges for platform teams in this section.

**Comment by taras** [comment]
I'll support this

**Comment by roberthstrand** [comment]
I can support as well

**Comment by joshgav** [comment]
Thank you for #285 and other discussions!
