### ISSUE TITLE
[WG Platforms] Platforms Def - Measuring success of platforms

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#278]
Review and finalize "How to measure success of platforms" section of Platforms whitepaper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md#how-to-measure-the-success-of-platforms>

**Comment by Saim-Safdar** [comment]
Happy to work and lead this

**Comment by taras** [comment]
I'm happy to support this

**Comment by joshgav** [comment]
Thank you @Saim-Safdar and @taras, assigned.

**Comment by salaboy** [comment]
Hi team, (@joshgav @jkleinlercher), this is something that I am covering in my book: Continuous Delivery for Kubernetes (http://mng.bz/jjKP) -> Chapter 9, and I built an open source example (https://github.com/salaboy/from-monolith-to-k8s/tree/main/four-keys) on DORA metrics (lead time, deployment frequency, mttr, change failure rate) in collaboration with the https://cd.foundation and the https://cdevents.dev team. I think that on this topic we can definitely collaborate and include some examples of how this can be tackled at the platform level.

**Comment by joshgav** [comment]
Want to note that this "metrics" section is the only one IMO in the current revision that's not "content complete" and needs more than a review and edit.

For this section we need to do the following:

1. Verify that we've gathered and explained the right metrics and measures. Modify list as appropriate.
2. Add prose to help the section flow with the rest of the document.

@salaboy's links look promising, thank you!

**Comment by joshgav** [comment]
> Frequency of updated deployments

We mentioned in a call today that we should define what a deployment is - does it include bug fixes, security fixes, dependency updates? Or perhaps only a featureful proper release?

**Comment by abangser** [comment]
> we should define what a deployment is - does it include bug fixes, security fixes, dependency updates? Or perhaps only a featureful proper release?

Ah love this! IMHO a change is a change (so I would agree with your list as a reasonable starting point to describe a change).

I think one of the biggest issues is a platform that separates "hot fix" changes and "normal" changes (or some other naming convention). Basically everyone figures out ways to do a hot fix instead of the normal process as it is faster. If the release process is too slow to support a hot fix, it may take more effort, but the real fix is to the release process, rather than to introduce a fast track where you just end up with a second problem in the long run.

**Comment by Saim-Safdar** [comment]
Some key points to consider here, while we are exploring at measuring success.

**Actionable accountability**

- **Cost management,** having clarity of which team is storing what in S3
- **Troubleshooting**, understanding which EC2 instance it’s failing doesn’t help you much
- **Performance**, front-liners might want to evolve their products by understanding which parts can actually be improved.

[How to measure success of your platform teams — part II
](https://medium.com/@josenoblecilla/measuring-success-of-your-platform-teams-part-ii-2976fd2b1315) actionable items, can be a good starting point, looking for others' opinions on this.

**Comment by jkleinlercher** [comment]
@Saim-Safdar in my opinion your points are capabilities of a platform. Observability-Tools help to troubleshoot and get insights about performance problems in applications and their root cause.
And „cost management“ in terms of resource consumption per application and a pay-per-use model for applications on the platform is also a feature of the platform, isn‘t it?

**Comment by Saim-Safdar** [comment]
@jkleinlercher good call, needs to be moved to [Capability Section](https://github.com/cncf/tag-app-delivery/issues/279) but I believe there's some common connection to it here as well, doesn't 100% sure, added to the plan to figure it out.

**Comment by joshgav** [comment]
@abangser 

> Basically everyone figures out ways to do a hot fix instead of the normal process as it is faster. If the release process is too slow to support a hot fix, it may take more effort

Love this, I think you're saying hotfixes are often the impetus for a faster release cadence, and a forward-thinking organization will use the opportunity to improve the process for _feature_ releases too. And therefore rapid releases of any sort, even just hotfixes, is a signal that an organization is capable of rapid _feature_ releases too.

That is, the capability to release _features_ quickly can be signalled by the capability to release _anything_ quickly.

**Comment by joshgav** [comment]
Posted a proposed rewrite of the metrics section to continue the conversation: https://github.com/cncf/tag-app-delivery/pull/297

PTAL, thanks!
