### ISSUE TITLE
[Platforms] Publish Platforms Def paper via CNCF

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#281]
Need to determine the process for publishing a whitepaper via CNCF and/or propose one. I started an email thread with CNCF staff and will share what I learn.

In today's WG meeting we agreed that we'd like to have this published by Kubecon EU on April 17 latest.

Here's the draft paper: <https://github.com/cncf/tag-app-delivery/blob/platforms-v1alpha1/platforms-whitepaper/v1alpha1/paper.md>

A couple examples we might learn from:

- [WG Cartographos](https://github.com/cncf/cartografos) publishes their paper on a Netlify site: <https://cncfmaturitymodel.netlify.app/>
- This TAG's Operators whitepaper is published as PDF in this repo: <https://github.com/cncf/tag-app-delivery/blob/main/operator-wg/whitepaper/CNCF_Operator_WhitePaper_v1-0_20210715.pdf>

**Comment by joshgav** [comment]
The website framework is complete and the doc is available at <https://appdelivery.cncf.io/whitepapers/platforms>. Thank you @krumware and @cjyabraham for your contributions and advice, great stuff!

The PDF version is now being prepared by CNCF; let's keep this issue open till that's finished.

**Comment by krumware** [comment]
🎉🎉🎉🚀🚀🚀
