### ISSUE TITLE
[TAG] Fix up CODEOWNERS

### ISSUE THREAD

**Issue by roberthstrand** [cncf/tag-app-delivery#287]
This has been bugging me for some time, but I haven't gotten around to raising the issue. There are several users set as codeowner that does not have any permissions on the repository. There are a couple of users here that might be stale, so I can figure out who should have access, but I need help from an owner to grant permissions to users.

**Comment by joshgav** [comment]
I'm re-purposing this as a general tag-admin issue to figure out and update CODEOWNERS. This will make our work here more efficient.
