### ISSUE TITLE
[Platforms] Add website draft following cartographos model

### ISSUE THREAD

**Issue by krumware** [cncf/tag-app-delivery#292]
Cartographos has implemented a website following other CNCF patterns, which can be used as a publishing tool here as well.

Implement the patterns established by Cartographos and migrate current draft docs (to be updated alongside drafts)

**Comment by joshgav** [comment]
Thanks @krumware! For readers, here's an example of such a site, to give you an idea of how we might structure content over time: <https://cncfmaturitymodel.netlify.app/>

**Comment by krumware** [comment]
A draft temporarily accessible via https://platforms.devnetes.com. This will be updated shortly to included the recently merged content, then we will be hoping to move this into a cncf subdomain

**Comment by abangser** [comment]
This is *so* good. Thanks for doing this!

A few small things I am curious about:
1. Do you have any plans/hopes for a "printable" version of this site? I am under the impression that we will have a PDF which maybe is something we just offer as a link from the page once it is available?
2. On a similar note, do you have an idea for a "searchable" version? I am not sure how valuable this is, but I could imagine people looking to see if someone is included or finding a previously found spot within the doc may be easier with a search. Of course I don't want to encourage a complex solution where it is not necessary, but I wonder if we do end up with a printable version that could be used with CTRL+f?
3. The image in the top left seems to be the same as used by the cartographos page. Did you have a plan for one that better fits this page? This may also be a moot point given https://github.com/cncf/tag-app-delivery/issues/329 🤔

**Comment by krumware** [comment]
Welcome back Abby!
I've looked into the printable version (there's an example on the Hugodocs site), and I'm not sure it's PDF-worthy out of the gate, without some extra styling effort. But it's possible. Could be that a PDF version needs to be knocked out separately.
I think the reformatting that's needed to support the site, which is going on in some slack discussion, will make the paper more searchable. The Maturity Model site looks like it relies on Google search indexed results, but if we're required to pull the separate sections back into one page for the app-delivery site then I think that will take care of itself.
We're getting some help from the cncf website team and that's one of the items discussed. There's also the need for a landing image or more mature graphics that was mentioned, but don't know if anyone has the ball on that yet. 
We probably need to start bubbling more up out of the slack chats and other gh issues to make it more clear. But CNCF website team has some items they have the ball on, then we can attack

**Comment by abangser** [comment]
Thanks Colin 😄 That all makes a lot of sense. I don't see search-ability as a blocker, just something I was thinking of. Thanks for the details!

**Comment by joshgav** [comment]
The site is up and running, see #333! Let's open PRs and issues for updates to the content.
