### ISSUE TITLE
[Platforms] Get a git repo for whitepaper site

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#318]
We'll publish the whitepaper as a web site like the cloud-native maturity model here: https://cncfmaturitymodel.netlify.app/, as discussed in #292.

It would be easiest to maintain the site in its own dedicated git repo rather than as part of this repo. This issue is to discuss and track that.

cc @thschue @krumware

**Comment by krumware** [comment]
I think it would make sense just to move the whitepaper to it's own repo, containing the site, as part of the publishing process

**Comment by joshgav** [comment]
Hi @krumware do you think we could have a directory `website` or `site` here in the TAG repo which would host all content for TAG App Delivery including the Platforms and other whitepapers? It could be like Cartografos' [`website` directory](https://github.com/cncf/cartografos/tree/main/website).

At the same time we could move the content currently here in the [Jekyll branch](https://github.com/cncf/tag-app-delivery/tree/jekyll) and published at <https://cncf.github.io/tag-app-delivery/>.

What are the differences between a subdirectory `site` here in this repo versus a dedicated repo just for the site? What would we lose by maintaining the site here? Thanks!

**Comment by joshgav** [comment]
After some discussions we're going to try to use a subdirectory in this repo for the paper; in fact we're going to try to move the TAG blog into this subdirectory too and have the Platforms and other papers as subsections in the greater site.

This implies migrating our TAG blog from Jekyll to Hugo to conform with [Cartografos](https://github.com/cncf/cartografos)' and [Glossary](https://github.com/cncf/glossary)'s patterns. I'll open an issue to track that. See also #327 which brings the `jekyll` branch into `main` - that's not so important now since we'll migrate to Hugo soon.

The [Cartografos](https://github.com/cncf/cartografos) repo uses a subdirectory and the [Glossary](https://github.com/cncf/glossary) repo has site contents in the root. Our plan is to go with Cartografos' approach so we can keep the website separate from other work while benefiting from better discoverability by sharing a single repo.

**Comment by joshgav** [comment]
Work continues to progress in https://github.com/cncf/tag-app-delivery/issues/329
