### ISSUE TITLE
[Platforms] Managing service bindings and secrets

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#322]
:exclamation:  **If you're interested in supporting and driving this work please respond to this issue.** Once we have enough interest we'll schedule an initial meeting to review current ideas and proposals.

----

## Background

The Platforms group is going deep into capability domains for platforms to seek ways to reduce complexity and increase synergies and standardization across related projects, vendors and users.

One of the domains which many find hard to rationalize today is how to seamlessly bind workloads to the capabilities or services they rely on. That is, workloads must be able to authenticate and connect to databases, object stores, message brokers, observability systems and more and there are many different ways to accomplish this.

At a high level this binding is typically accomplished by 1) getting a credential and URL from the service; 2) securely storing that info in a secure store like Hashicorp Vault; and 3) injecting that info into workloads in specific formats and locations. However, it seems every service, every platform, every secure store and every workload type has a different way to accomplish these steps.

This leads to difficulty, confusion and delay for cloud developers and lots of discomfort and concern to cloud security practitioners about how secrets are managed. For example, many folks may not realize that some projects write secret data in Kubernetes secrets as it's transferred to the workload, a practice some enterprises don't allow.

We've jumpstarted discussion about projects and ideas to address this in [this Google doc](https://docs.google.com/document/d/1-9ZU7yRB3oVKozIDO5FkkZQc1svvBj4ME8pUOqN9Mjw/). I'll copy the two main sections here to continue discussion.

Please share other projects and ideas with us and if/how you can contribute. Thanks!

## Related Projects and Services

- [External Secrets Operator](https://github.com/external-secrets/external-secrets) (ESO) - synchronizes secrets from an external store into Kubernetes' secret store (i.e., etcd)
- [SOPS](https://github.com/mozilla/sops) ("Secrets Ops") - secrets are encrypted and the encrypted strings are stored in plaintext. A master secret is maintained elsewhere and decrypts secrets before use.
- Service binding [runtime](https://github.com/servicebinding/runtime) and [spec](https://github.com/servicebinding/spec) - a relationship between a service and a workload is declared; on reconciliation credential is retrieved from service and injected into workload
- [Hashicorp Vault](https://github.com/hashicorp/vault) - static secrets are stored in an encrypted database; and/or dynamic secrets are generated on demand for specific service types. Secrets are retrieved by direct API call or injected into workloads by a sidecar.
- [Azure Passwordless](https://learn.microsoft.com/en-us/azure/developer/intro/passwordless-overview) - automatically generate secrets for services and inject into workloads (need verification as it's closed source)
- [Dapr secrets management](https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-overview/) - provides a standard API for retrieving secrets from any store, bypassing the Kubernetes store
- [SPIFFE/SPIRE](https://spiffe.io/) - inject a workload identity
- [GCP Cloud SQL Auth Proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy)
- [vault-config-operator](https://github.com/redhat-cop/vault-config-operator)
- Tekton auth: https://github.com/tektoncd/pipeline/blob/main/docs/auth.md
- Cloud providers: [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault), [AWS KMS](https://aws.amazon.com/kms/), [GCP Key Management](https://cloud.google.com/security-key-management)
- ArgoCD’s doc on secrets integration: https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/
  - How Argo manages secrets in its rendering engine: https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/#mitigating-risks-of-secret-injection-plugins
- [kube-bind](https://github.com/kube-bind/kube-bind) - binding CRD based APIs from providers to consumer clusters, with the ability to exchange secrets and other auxiliary objects, e.g. services.
- [Vault Secrets Operator](https://www.hashicorp.com/blog/vault-secrets-operator-a-new-method-for-kubernetes-integration) - syncs secrets from Hashicorp Vault into Kubernetes secrets

## Ideas
- Focus on dynamic generation of short-lived credentials and transparent injection of those credentials into workloads (pods).  Contrast with static secrets, i.e., simple key/value pairs that must be kept secret, like an API key from a service provider.
- Explore conventions for requesting short-lived credentials and locators from services on demand
- Could we have a standard API that given a CR* returns fresh credentials?
  - Compare Vault dynamic secrets engines
  - Compare knative [SinkBinding](https://knative.dev/docs/eventing/custom-event-source/sinkbinding/) and [Binding](https://knative.dev/docs/concepts/duck-typing/#binding) duck type
  - Compare service binding "[Provisioned Service](https://servicebinding.io/spec/core/1.0.0/#provisioned-service)"
  - How to avoid transiting a K8s secret? (some enterprises insist on this)
- Explore conventions for injecting credentials and locators into workloads in specific locations, e.g. as files at a specific path
  - Hypothesis: this will enable library authors to seamlessly consume secrets, reducing load on app developers to template secrets in specific files at specific locations.
  - Establish a convention on where to put binding info in workloads, e.g. as files in a well-known folder. Could be used in Vault agent and SBO.
- Establish a library of dynamic credential generators for different service types, a la Hashi Vault's dynamic secrets engines. 
  - Use these in service binding runtime and other secret generators.
- Encourage user community to treat all secrets as short-lived and ephemeral. Encourage folks to avoid static secrets persisted in a store. If we get a library going, ask service and cloud providers to contribute "generators" for their services.
- Add `SecretClass` to Kubernetes secrets and enable alternate implementations, e.g. served from an external store rather than etcd. Compare to ClusterClass and StorageClass.

cc @monadic @raffaelespazzoli @sttts @sabre1041 @hiddeco @cmoulliard

**Comment by jkleinlercher** [comment]
What about bitnami sealed-secret?

**Comment by szh** [comment]
I'm interested in potentially helping out with this. I'm a member of TAG Security and a maintainer of [Conjur Open Source](https://github.com/cyberark/conjur).

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic.

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!

**Comment by cmoulliard** [comment]
Instead of closing it, it should be better to move the request/issue to a future milestone
