### ISSUE TITLE
[Platforms] Multitenancy capability

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#324]
As we worked on the platforms whitepaper the topic of support for multiple tenants in one environment (henceforth just "multitenancy") came up a couple times. We decided that multitenancy is not a capability platform _users_ would much care about as the goal for most multitenant scenarios is for the tenants themselves to be blissfully unaware that they're sharing space. That is, multitenancy is ideally invisible to the tenants themselves.

However, multitenancy _is_ an important capability in platforms for building _platforms_ (sic). That is, platform engineers and platform teams often want to use the same spaces and environments to host many teams and tenants, and would consider projects like [vcluster](https://www.vcluster.com/), [kubeplus](https://github.com/cloud-ark/kubeplus) or [kcp](https://www.kcp.io/) to achieve this.

Let's use this issue to discuss how we might capture capabilities required for "platforms for _platforms_" (sic) and how we might support platform builders and platform framework providers in rationalizing this space. Let's consider initial work in https://github.com/cncf/tag-app-delivery/issues/193 (cc @AlexsJones).

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic.

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
