### ISSUE TITLE
[website] Only trigger fresh builds for changes to website

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#356]
Hi @cjyabraham, can you configure our connection to Netlify to only rebuild the website for changes within the `./website` path? That would reduce Netlify's "comments" in other PRs and save energy from unneeded builds. Thanks!

**Comment by cjyabraham** [comment]
I believe that is the default behavior, [only to run a build when something changes in the base directory](https://docs.netlify.com/configure-builds/ignore-builds/), `website` in our case. Is that not what you're seeing?

**Comment by joshgav** [comment]
Thanks Chris. I saw it trigger a build/deploy in https://github.com/cncf/tag-app-delivery/pull/313, but maybe that config is why it cancelled itself.
