### ISSUE TITLE
Image url is broken

### ISSUE THREAD

**Issue by boatrainlsz** [cncf/tag-app-delivery#361]
Example Backup Process image in [Operator-WhitePaper_v1-0.md](https://github.com/cncf/tag-app-delivery/blob/main/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#backup) is missing

**Comment by aryasoni98** [comment]
I would love to contribute on this issue.

**Comment by Jenniferstrej** [comment]
We are no longer maintaining this version of the Whitepaper. The version to be used is https://github.com/cncf/tag-app-delivery/tree/main/operator-whitepaper/latest. We need to clean up the old versions to avoid confusion, apologies.
