### ISSUE TITLE
Create an Artifacts Working Group

### ISSUE THREAD

**Issue by scottrigby** [cncf/tag-app-delivery#368]
Hello, everyone! 

There is serious interest in a new Artifacts Working Group. We are asking to create this WG under TAG App Delivery, as outlined in this [WG Artifacts Charter](https://docs.google.com/document/d/1w_lo2RZDKeEzQg4DMV-9Tq4ir_znONj_ypJ27CUfMgY/edit?usp=sharing) draft.

Please create the WG under TAG App Delivery. Thank you!

## Brief history

There has been an ongoing effort to improve support for OCI artifacts for Cloud Native app delivery. Recently a group of interested parties has begun [work on improving artifacts search and discovery](https://docs.google.com/document/d/1rcQROZP31q7BOjoZ977Ok7pt28z_UXfW0vAK3xC0wdI/edit?usp=sharing). This Artifacts Search and Discovery goal, however, relates to wider artifact improvement within the cloud native ecosystem, and so it is now outlined as one of several activities for a new Artifacts Working Group. Such a WG belongs within CNCF, and under TAG App Delivery, as outlined in this [WG Artifacts Charter](https://docs.google.com/document/d/1w_lo2RZDKeEzQg4DMV-9Tq4ir_znONj_ypJ27CUfMgY/edit?usp=sharing) draft.

**Comment by developer-guy** [comment]
This is super cool 🫠 I'd love to be part of that WG ☝️💯

**Comment by dlorenc** [comment]
It would be helpful to understand where the work output from here is intended to land (CNCF vs. OCI). In my experience there's been a lot of confusion already around things like OCI Artifacts, so being clear up front on what the deliverables from this group are and where they're intended to live would be useful.

A few questions:
* Will these be extensions to the OCI APIs that live in a CNCF project?
* Will recommendations from here end up being proposed over to the OCI and going through their standard process?

I see that the draft charter calls out some of this and says:

> The group is in CNCF rather than OCI because OCI's TOB determined that work on Artifacts other than container images should be in CNCF while OCI focuses on container images exclusively [3].
[2]: https://github.com/cncf/toc/blob/main/tags/app-delivery.md#areas-considered-in-scope
[3]: https://github.com/opencontainers/tob/pull/68

But I'm not sure I interpret that closed TOB issue the same way. Either way, it's several years old, so checking back in with the OCI TOB to get their current thoughts would still be useful. Lots of movement has happened in this space recently there.

**Comment by imjasonh** [comment]
As noted in a comment on the WG charter doc:

> I'd like to suggest this clarify the goal as being an OCI extension specified by this WG, and not for these common formats to be defined in OCI itself.

To be more explicit: whatever the group produces, whether it's new APIs, new types, a system for extensible type registration, whatever, I believe it should be limited to APIs defined and controlled by some CNCF body, perhaps _using_ the [OCI extensions mechanism](https://github.com/opencontainers/distribution-spec/tree/main/extensions), and not a proposal for new OCI specs itself.

If the goal is OCI specs, you need to engage with the OCI TOB, not CNCF TAG App Delivery.

Going that route means this group should be very careful about positioning the work as "_an_ artifacts API defined by CNCF TAG App Delivery" and not anything that could be confused to mean "_the_ OCI artifacts API". Positioning it as an official OCI thing would require approval from OCI TOB and an OCI WG process. We've been less careful about our words in the past, and it's caused no end of confusion.

**Comment by scottrigby** [comment]
Thanks @imjasonh 👍  Yes, confirmed. The discussion so far has been precisely this. Perhaps using OCI extensions, and *not* to create update the OCI spec itself. Any such improvement would, of course, have to be a collaboration with – and move through – the OCI org and its existing processes.

The goal of moving this work to CNCF came from previous discussion on this with OCI org members through past work on artifacts, and there has already been some informal discussion between several folks currently involved in OCI now. I will join tomorrow's OCI meeting, and make sure we're all on the same page. (Thanks @amye for pointing out that meeting!).

Also, I hope we can connect in person in Amsterdam, since I just found out there will be an OCI event at KubeCon! Looking forward to moving ahead with this in the best way(s) possible ❤️

**Comment by scottrigby** [comment]
@dlorenc just to follow up on your comment too

> A few questions:
> 
> * Will these be extensions to the OCI APIs that live in a CNCF project?

The proposed WG would be a vendor-neutral and transparent place to discuss and explore these ideas. However, any implementation would live in the correct locations. For example, code will likely live in an ORAS subproject. Yes so far extensions have been the proposed path forward.

> * Will recommendations from here end up being proposed over to the OCI and going through their standard process?

But - continuing from above - yes if there ends up being recommendations to propose for the OCI spec, this will absolutely move through OCI orgs existing processes, no question.

> 
> I see that the draft charter calls out some of this and says:
> 
> > The group is in CNCF rather than OCI because OCI's TOB determined that work on Artifacts other than container images should be in CNCF while OCI focuses on container images exclusively [3].
> > [2]: https://github.com/cncf/toc/blob/main/tags/app-delivery.md#areas-considered-in-scope
> > [3]: [opencontainers/tob#68](https://github.com/opencontainers/tob/pull/68)
> 
> But I'm not sure I interpret that closed TOB issue the same way. Either way, it's several years old, so checking back in with the OCI TOB to get their current thoughts would still be useful. Lots of movement has happened in this space recently there.

The fact that some time has passed is a good point. However, a number of the members of this proposed working group have spent a lot of time going that route in the past. But yes, per my comment to @imjasonh above I will join tomorrow's OCI meeting and we can make sure we're all on the space page about every part of this proposal. The most important thing is to have a neutral, fair, and transparent place to move ahead with improvements to artifacts that a number of projects are interested in. We will do the right thing, either way, and may have to discuss the goals a bit more to clarify any ambiguity 💖

**Comment by vbatts** [comment]
I'm glad to see this tighter coupling. 

There will be an OCI meeting _**at**_ KubeCon, that some of us will be attending (including myself).
Date: Wednesday, April 19
Time: 2:30pm - 5:00pm
Room: D203-204

**Comment by dlorenc** [comment]
> The fact that some time has passed is a good point. However, a number of the members of this proposed working group have spent a lot of time going that route in the past.

Thanks! This is really the only part I take objection to. I don't believe the OCI TOB ever issued a statement "that work on Artifacts other than container images should be in CNCF while OCI focuses on container images exclusively". I don't think they said that two years ago, and I don't think they'd agree with that statement today.

I also don't think it really matters - the OCI is a different group than the CNCF and this TAG and can't claim to "own" or "block" anyone from doing work like this, but I do think it's important to be accurate in this framing.

**Comment by sabre1041** [comment]
> I'm glad to see this tighter coupling.
> 
> There will be an OCI meeting _**at**_ KubeCon, that some of us will be attending (including myself). Date: Wednesday, April 19 Time: 2:30pm - 5:00pm Room: D203-204

Excellent. I'll be attending and look to participate in the OCI meeting

It will be good to get some mindshare across communities

**Comment by angellk** [comment]
I may be late but plan to attend as well on April 19. Agree, having a tighter coupling across communities would be excellent.

**Comment by joshgav** [comment]
TAG App Delivery will host an initial meeting for the Artifacts WG tomorrow Friday May 19 to finish the charter and start work towards goals. Here are the details!

- Event page (RSVP for an invite): <https://community.cncf.io/events/details/cncf-tag-app-delivery-presents-wg-artifacts-project-meeting/>
- Date/Time: Friday May 19 @ 1600 UTC ([click to convert](https://www.timeanddate.com/worldclock/converter.html?iso=20230519T160000&p1=1440&p2=64&p3=1960&p4=tz_aet))
- Zoom URL: <https://zoom.us/j/7276783015?pwd=R0RJMkRzQ1ZjcmE0WERGcTJTOEVyUT09>
- Notes URL: <https://docs.google.com/document/d/1w_lo2RZDKeEzQg4DMV-9Tq4ir_znONj_ypJ27CUfMgY/>
- Slack: <https://cloud-native.slack.com/archives/C04UQDWS4M7>

**Comment by joshgav** [comment]
Update for folks following: we held the meeting described in the previous comment a couple weeks ago and then another one today; and we're ready to submit a PR with the proposed charter for the group based on the contents of the draft doc above the horizontal line. The draft charter, meeting notes, and meeting recording playlist are linked below.

@afflom will work on getting the PR for the charter to this repo following the existing conventions in the TAG for [gitops-wg](https://github.com/cncf/tag-app-delivery/tree/main/gitops-wg) and [platforms-wg](https://github.com/cncf/tag-app-delivery/tree/main/platforms-wg). Once he does that @joshgav (I) will open an issue in [cncf/toc](https://github.com/cncf/toc) to get their review and approval of the PR, similar to [cncf/toc#1034](https://github.com/cncf/toc/issues/1034). Merging the PR will close this issue and represent the inauguration of the official WG!

I'll put this on the agenda for the next TAG meeting too to be sure all are aware and give feedback.

For ongoing discussions join [the #wg-artifacts Slack channel](https://cloud-native.slack.com/archives/C04UQDWS4M7)..

- Charter in development: https://docs.google.com/document/d/1w_lo2RZDKeEzQg4DMV-9Tq4ir_znONj_ypJ27CUfMgY/edit#
- Notes: https://docs.google.com/document/d/1E7iKPOuyA1jxPe8vDG8aPd8jtnCEbpDpCifXDvDCnA0/
- Recordings:  https://www.youtube.com/playlist?list=PLjNzvzqUSpxKNR7NIoEoXfFz1blYg4FUu

**Comment by ktarplee** [comment]
I would love to be a part of the artifacts working group regardless of if it lands in CNCF or OCI.
