### ISSUE TITLE
Website: Add a link from community page to new website

### ISSUE THREAD

**Issue by krumware** [cncf/tag-app-delivery#373]
The community page: [https://community.cncf.io/tag-app-delivery/](https://community.cncf.io/tag-app-delivery/) does not have information about the location of the new informational website ([appdelivery.cncf.io](https://appdelivery.cncf.io/)). 

It would be great to add it there for convenient access / discoverability

**Comment by aryasoni98** [comment]
I would like to contribute on this issue

**Comment by joshgav** [comment]
Added the new site to the description on the community page, thanks for the suggestions @krumware.

@aryasoni98 unfortunately it's a fix only an admin can apply, hope you can help us in the future! Thanks.
