### ISSUE TITLE
CNCF Platforms White Paper - Include KEDA for application autoscaling

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/tag-app-delivery#378]
I love the CNCF Platforms White Paper, however, I find it a bit of a pity that KEDA (CNCF Incubation, with open proposal for Graduation) is not listed as an application autoscaler.

Is there anything I can help on this front?

PS: As a KEDA maintainer, I'm clearly biased.

**Comment by niklasbeinghaus** [comment]
This issue has been discussed in today's platform-wg meeting.

When abstracting your request for adding KEDA to the platform components, from a broader perspective we would need to have a process for adding new projects first.

Going a bit further, we could also discuss this around the question "Where does _my project_ fit?" Unfortunately, the question isn't exactly easy to answer and we need some more time to discuss how we're gonna proceed.

As a first step, we're likely going to deploy the website from versioned whitepapers folders instead of latest, so you can refer to it as stable artifact: https://github.com/cncf/tag-app-delivery/issues/389

**Comment by joshgav** [comment]
Thanks for the update @niklasbeinghaus and for the suggestion @tomkerkhove. Let's use this issue to discuss where a system like KEDA fits in our current list of capabilities.

I think KEDA and other scaling tools are part of compute infrastructure, and thus the infrastructure capability. I say that cause these tools and similar ones like [Azure VM Scale Sets](https://azure.microsoft.com/en-us/products/virtual-machine-scale-sets/) and [AWS EC2 Auto Scaling](https://aws.amazon.com/ec2/autoscaling/) support adding and removing compute instances as necessary - VMs, containers, functions, perhaps even WASM binaries. The actual scaling of compute is transparent to the developer.

As another example, Knative Serving includes scaling capabilities and perhaps is more clearly part of the compute/infrastructure capability.

These autoscalers don't much effect network and storage either, just compute.

**Comment by joshgav** [comment]
We've merged #385 to add KEDA to the list of example infrastructure capability providers. :tada: 

And we're discussing how to maintain and modify the graphic in #388.

As @niklasbeinghaus says, we still need a way to discuss the current list of "capabilities" and guide projects to find their fit or suggest a new category. I'd like to compare and contrast with the categories in the CNCF landscape and the list of TAGs too. Let's open a new issue to discuss how to modify and maintain the capabilities list.

With that I think it's okay to close this issue, thanks again @tomkerkhove !

**Comment by tomkerkhove** [comment]
No problem for me and thanks for considering and integrating!

One side question - How often does https://tag-app-delivery.cncf.io/whitepapers/platforms/ get updated?

**Comment by abangser** [comment]
Sorry for leaving this question hanging @tomkerkhove. There isn't a hard and fast rule right now on how often the paper will be updated. The paper is still very much in its infancy in that it was only released in time for Amsterdam in April 2023 so we need to allow time for learning before looking to reinvest time into a second version. Based on other CNCF projects at this scale I would expect 1-3 years between releases.

**Comment by tomkerkhove** [comment]
Thanks for the update! That's fine, however, isn't 1-3 years a gigantic period in a fast-moving space such as cloud-native?

**Comment by abangser** [comment]
I would be inclined to agree it is unlikely the paper will be durable up to 3 years. That being said, I'm hesitant to say we will have learned enough to do a version change including re translation in less than a year. 

Right now the only changes are adding more projects which is as you rightly say very fast moving, but also not the core deliverable of the paper. We have goals of producing more low level resources that focus on implementations that will hopefully fill this need. 

If you want to join in on that it would be great!
