### ISSUE TITLE
Release a Platform Maturity Model

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#381]
Hi all 👋  I was a part of the WG-Platform that released the [white paper](https://tag-app-delivery.cncf.io/whitepapers/platforms/) recently.

## Background
This white paper intentionally focused on a high level topic and specifically says its goal is to "support enterprise leaders, enterprise architects and platform team leaders to advocate for, investigate and plan internal platforms for cloud computing...[and to] enable that support by discussing what the value of platforms is, how to measure that value, and how to implement platform teams that maximize it." Given this, the group always imagined a number of follow up papers and documents to dive deeper into the details introduced in the white paper. Some of these actions are already underway (e..g the [product mindset paper](https://github.com/cncf/tag-app-delivery/issues/282), [survey](https://github.com/cncf/tag-app-delivery/issues/315), and [prototype platform](https://github.com/cncf/tag-app-delivery/issues/293)). This issue proposes another add on in the form of a maturity model.

## Why maturity model
When people are exploring new ways of working or disciplines there is a desire to identify current shortcomings and opportunities for growth is common and fair. So at the highest level, a maturity model is defined on Wikipedia as:
 
> a framework for measuring an organization's maturity, with maturity being defined as a measurement of the ability of an organization for continuous improvement in a particular discipline...The higher the maturity, the higher will be the chances that incidents or errors will lead to improvements either in the quality or in the use of the resources of the discipline as implemented by the organization.

Given platform engineering is such a new term, it is a natural fit for a maturity model that can help identify implementations that are less effective and provide guidance on where to be targeting as an organisation. Despite these best intentions, it is important to also acknowledge that maturity models come with a lot of risk and baggage. In particular, there is a history of these models being used as a box ticking exercise by organisations to compare teams. As the WG-Platform evolves this maturity model should keep this risk in mind.

## Current draft
This document is open for global suggestions:
https://docs.google.com/document/d/11J_RpaUwydNNBg5aVjH5Uzn8i-b4urEtJzwR86XezFQ/edit

## History of current draft

The original draft maturity model (v0.0.1) was drafted and reviewed by a number of leaders in the platform engineering space. That by no means indicates it is complete, only that it is a proposed starting point. There are a number of big questions still outstanding after the first round of reviews that we think will best be tackled by the wider WG-Platform.

* Should we add a small number of key principles into the top of the document
* Is there a better shape for this type of guidance (e.g. a [capability](https://octopus.com/blog/devops-uses-capability-not-maturity) or [fluency model](https://martinfowler.com/articles/agileFluency.html) instead of a [maturity model](https://martinfowler.com/bliki/MaturityModel.html))
* Does the size, shape, or stability of the organisation affect their use of this model?
* Should we give suggestions on when/how to apply this model effectively (e.g. each platform team can self evaluate rather than once per organisation if there are more than one platform teams)
* Should we encourage "empowering" style platforms (where some platforms "disempower" by hiding things, abstracting things, limiting what developers can do)
* When picking levels for an aspect...
  * Do all aspects need the same number of levels?
  * Are the levels intended to be progressive (as in, you should attempt to reach level 2 before aiming for level 3?)
* Specific feedback on the aspects...
  * Is organisational structure the right name, and is it actually the outcome from funding (and therefore should be merged)?
  * Do we want to focus at all on how the platform team builds software? Backlog touches on this (and may not be a good aspect) and an idea of "engineering discipline" was discarded).
  * Should. backlog be called "Product Management"
  * Does level 4 in cross-functional representation do enough to speak to co-creation of capabilities across the org (and a mindset towards inner-sourcing in general)

This was then iterated on to create version 0.1.0 which saw an increase in contributions and a strong focus on defining the model table. There were three deep dive calls as well as a number of async chats in the #WG-Platforms slack channel to result in version 0.2.0.

## Proposed next steps
Similar to the white paper, I think that this document would benefit from a wider audience and a refinement period. I would propose it be mentioned at WG-Platform and TAG-AppDelivery meetings as a suggestion for review. @joshgav was a fantastic guide for the white paper and if we decide this should be taken forward we should likely have someone in that role for this as well. These people can be added as editors for the document.

The current draft (v0.2.0) requires introducing the details section and is aiming to be complete (though not fully reviewed) by September 10th, 2023 which would allow us to publish by KubeCon NA in Chicago.

**_Please comment on this issue if you want to be a lead or otherwise on publishing this paper!_**

**Comment by roberthstrand** [comment]
I'm in, let me know how I can help 😊

**Comment by niklasbeinghaus** [comment]
I absolutely love the idea of having a maturity matrix for platform engineering - actually that's what kickstarted my cloud-native journey when I originally read this book: https://www.oreilly.com/library/view/cloud-native-transformation/9781492048893/

-> see https://www.cnpatterns.org/how-to-use-cards for a ref of their version of a cloud native maturity matrix.

In my opinion, maturity matrixes are an easy to understand tool to get a feeling of where you're currently at and what to focus on next on your journey to excellence.

**Comment by tsahiduek** [comment]
Really like this proposal. Self-evaluating process is one of the key tasks when organization (or even business units) are doing when adopting a new framework/methodology.

Happy to join and collaborate here.

**Comment by abangser** [comment]
Looking at the schedule, I think I am going to aim for a first meeting w/c May 8. That way we will be able to announce at the next TAG meeting (May 3) and WG Platform meeting (May 9). 

### My proposed time to meet is 16:00 UTC on Wednesday May 10
**please shout if this does not work for you and we can try to arrange a more suitable time or a second meeting**

This meeting is going to cover some high level getting started items for the maturity model and I am collecting topics here: https://docs.google.com/document/d/1FG9ntkwLedumuTS3b6nJ9A7sAYz5fNiAJpIwCnB6a0E/edit

**Comment by abangser** [comment]
Would really appreciate if you come @AlexsJones ! I think that world is something I personally would want to actively avoid as well. It is also part of why the format has its challenges as how people use it leaves our hands. 

One thing I am currently thinking is that we are targeting outcomes and not implementations. That isn't to say this draft is perfect but I would hope the v1 draft can outlive any one technology as it levels can be achieved with many implementations.

**Comment by osowski** [comment]
Just got through the draft and loved what I saw. Only minimal comments on my end and would love to participate in any further focused discussions on this work effort in the future.

**Comment by abangser** [comment]
I have updated the overall comment here to reflect the state of the world. In particular it now points at v0.2.0 which is the current working doc.

**Comment by abangser** [comment]
A PR has been opened to do final review on v1.0.0! 🎉

https://github.com/cncf/tag-app-delivery/pull/464

**Comment by abangser** [comment]
Congratulations to the almost 50 people who engaged with this work over the last 10 months. We are now v1.0.0 released! 🎉

Just as with the white paper, we will open up a `latest` directory to manage any edits/ideas that come in as we discuss next versions over time.
