### ISSUE TITLE
Update repo link to https://tag-app-delivery.cncf.io for better discovery

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/tag-app-delivery#386]
Update repo link to https://tag-app-delivery.cncf.io to make this nice website easier to discover.

![image](https://user-images.githubusercontent.com/4345663/234189114-f464fd6f-7094-44fc-8d96-9ab3f03498ad.png)

**Comment by joshgav** [comment]
Good suggestion! I don't seem to have rights to change that - @AloisReitbauer do you?

**Comment by Jenniferstrej** [comment]
Great idea, done! https://github.com/cncf/tag-app-delivery :)

**Comment by tomkerkhove** [comment]
Thank you!
