### ISSUE TITLE
[Platforms] Define a process for iterating over platform-components graphic

### ISSUE THREAD

**Issue by niklasbeinghaus** [cncf/tag-app-delivery#388]
At the moment, a static png is stored in this repository: https://github.com/cncf/tag-app-delivery/blob/main/platforms-whitepaper/latest/assets/platform_components.png

Let's discuss on how we can iterate over the graphic in a good way considering:
* recurring changes to components
* visual improvements

**Comment by niklasbeinghaus** [comment]
From a process perspective, I'd suggest to keep the graphic as simple as possible.

In order to do so, adding a new icon whenever a new project is added as a platform component might be a little too much overhead as long as the graphic generation isn't fully automated. For this reason, I'd like to suggest to simplify the graphic by removing the project icons.

**Comment by joshgav** [comment]
Thanks for the research and suggestion @niklasbeinghaus! I'll take a look and reply soon.

**Comment by abangser** [comment]
Agreed on the idea of removing icons from the image and leaving them just in the table below. I wonder if we can do this in the latest directory and make this a part of the ongoing improvements work that won't impact the currently hosted white paper on the site?

**Comment by joshgav** [comment]
I've been using draw.io for a few months now to learn how to implement @niklasbeinghaus's suggestions :laughing:. I'm going to move the graphic from the Definition paper to draw.io and see about removing icons. I'll start a PR to replace the origina graphic when ready and let you know here. Thanks for the tips @niklasbeinghaus!
