### ISSUE TITLE
[Platforms] Prepare website for whitepaper translations

### ISSUE THREAD

**Issue by niklasbeinghaus** [cncf/tag-app-delivery#394]
There's been some work towards a korean translation of the Platform Whitepaper: https://cloud-native.slack.com/archives/C020RHD43BP/p1681383330022189 

I'd suggest to make translations happen by:
- preparing the directory structure in hugo
- adding some guidance on where to put which files

Reference:
- https://github.com/cncf/cartografos/tree/main/website/content
- https://github.com/cncf/cartografos/blob/main/website/config.toml#L47

**Comment by joshgav** [comment]
cc @sysnet4admin

**Comment by niklasbeinghaus** [comment]
Yup, started this (see draft PR above), however I seem to have broken some stuff in the preview. Didn’t have time to review it again, probably happening next week ;)

**Comment by node** [comment]
Any update here ? 

Actually there has been a Chinese version of paltform whitepaper by @rootsongjc ,and a Chinese version of the "Capabilities of platforms " image by @node (it's me 😄 )  . Also need to publish on website.

**Comment by abangser** [comment]
Want to confirm that this is getting worked on in #450 as well. It would be great to get this in!

**Comment by node** [comment]
No. #450 just set up the i18n infra and translate basic menu and title , do not translate all things one time, we need make it step by step .

**Comment by node** [comment]
Hi, website enable i18n now, so better choice may be adding Korean support for the whole webstie not only one whitepaper .

**Comment by Eeap** [comment]
Hi, I saw the PR(#406) about korean translation about v1. But there is not latest version, so I want to translate it into korean.

**Comment by joshgav** [comment]
Thank you @Eeap, as I mentioned in <https://github.com/cncf/tag-app-delivery/pull/406#issuecomment-1827741137> let's refactor that PR and provide a Korean version of the site alongside the Chinese and English versions.

**Comment by joshgav** [comment]
And thank you @Eeap, indeed translations should come from the [latest](https://github.com/cncf/tag-app-delivery/tree/main/platforms-whitepaper/latest) directory.

**Comment by joshgav** [comment]
This issue has been resolved with #492. Please open other issues for topics like adding Korean.
