### ISSUE TITLE
[Platforms] Community Outreach role

### ISSUE THREAD

**Issue by jorgelainfiesta** [cncf/tag-app-delivery#396]
## Proposal

Create a community outreach role within the Platforms WG. This proposal comes from what @abangser described as a possible role in yesterday's meeting, but I thought that to achieve that one, there'd be a need for a bigger coordination.

## Motivation

There are three main reasons why I think this is much needed:
- The whitepaper popularity has shown how much the community is expecting vendor-neutral literature on the subject of Platform engineering. Right now, it is not the easiest to figure out what the WG is working on or what it has to say, as the website is not as known as it could be.
- The WG wants to talk to end-users regularly. In order to make sure we can have a constant flow of people sharing their stories, people must know about the WG existence and that sharing their stories is a possibility.
- The WG will also want to reach out to the community for initiatives like the survey, which requires a more structured communications 

## What would this role do?

- Structure a communication strategy and channels for outreach (LinkedIn? Newsletter?).
- Give visibility to the initiatives the WG is working on
- Regularly publish content to update audiences on what the WG is working on and share outcomes
- Actively engage with the community

## Who could do this role?

Naturally, I volunteer to take care of these issues. But of course there may be somebody who's up for the task too. I have a limited experience doing this as part of a CNCF WG, have only done it for companies.

**Comment by roberthstrand** [comment]
I love the idea of this type of role. It would probably be best to start off by defining this as a team, even if that team only has one member at the start, just to make sure that this is a role that can be easily passed on if needed.

It might even be beneficial to talk about having such a team on a TAG level, so one could share knowledge across the TAG. Then someone from the OpenGitOps project could join the team as the designated community outreach person for the project, and then you (@jorgelainfiesta) could be the dedicated person for the platforms working group.

I'll try to remember to mention it in both the TAG and OpenGitOps meeting.

**Comment by abangser** [comment]
This is so amazing @jorgelainfiesta, thanks for turning a half baked suggestion into an actionable role!

I think @roberthstrand has added some key points and his suggestions make the idea work well within the CNCF structures which will hopefully enable a broader and longer lasting impact. But I also don't think it has to be limiting if we don't immediately have an interested party from each WG. IMO setting the structure up at the TAG level makes sense, but I don't think you should be limited on getting started withe the WG Platform until that is matured.

I wonder if next steps are:
* Raise at next TAG meeting (May 3)
* Open a PR to this repo with a new directory to manage associated documents

I don't think these are necessarily dependent on each other, but raising at the meeting may make the PR easier to understand / review for the team members.

**Comment by joshgav** [comment]
Thank you for starting this @jorgelainfiesta! To date outreach activity for the TAG and its WGs has been informal and we haven't made much explicit effort to reach our audience, that would be welcome! @lianmakesthings has also stepped up to help in this area and she may be able to support this too.

Agree with @roberthstrand and @abangser's sentiment that the initiative applies to the TAG generally, but it's reasonable IMHO to start by focusing on WG Platforms and go from there. @roberthstrand it would be great to bring this up in GitOps too. I'll label this issue to be discussed in the next WG Platforms and TAG meetings.

FYI @jorgelainfiesta, here are some existing presences we have:
- TAG website - <https://github.com/cncf/tag-app-delivery/blob/main/website/README.md>
- TAG Twitter account - [@CNCFTAGApp](https://twitter.com/CNCFTAGApp)
- TAG community page: https://community.cncf.io/tag-app-delivery/

We also can request content be published on the CNCF blog pretty easily.

Thanks again!

**Comment by joshgav** [comment]
Thank you @jorgelainfiesta for suggesting this, we're trying to integrate community outreach into our work and appreciate the support. I'll close this issue as complete as we're pursuing the items like Web pages and newsletters now and have added some leads to the TAG to help.
