### ISSUE TITLE
Discuss CDEvents support

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#397]
At Kubecon EU TAG leads talked with @fdegir and @afrittoli of the [Continuous Delivery Foundation](https://cd.foundation/) (CDF), another Linux Foundation member, about supporting [CDEvents](https://github.com/cdevents) in CNCF's and TAG App Delivery's projects.

We've invited them to present CDEvents and explore opportunities in an upcoming TAG general meeting.

cc @thschue @AloisReitbauer

**Comment by joshgav** [comment]
Copying notes from today's discussion, thank you!

## Why CD Events?
- Enable interoperability between delivery services and tools.
- Make delivery components independently scaleable
- Observability of delivery tasks/pipelines
    - Events enable calculation of DORA (and other) metrics
    - Collection of all events can attest to intended activity throughout pipeline (but need to trust events - e.g., need to be signed)

## Technical WIP
- Recently added events for ongoing operations (runtime, post-delivery)
- Working on correlation/shared context across a related set of events (e.g., one pipeline run)
- Working with tools providers to emit compliant events
- SDKs are able to both send and receive compliant events
    - Go SDK is complete, others in development
- Projects implementing today, using SDKs:
    - Jenkins: https://plugins.jenkins.io/cdevents/
    - Spinnaker: https://github.com/spinnaker/governance/pull/299
    - Tekton: https://github.com/tektoncd/experimental/tree/main/cloudevents
    - Testkube: https://github.com/kubeshop/testkube/issues/3682

## Questions
- Are CDvents semantics used by OpenTelemetry emitters?
    - Not currently, but see <https://github.com/open-telemetry/opentelemetry-specification/issues/3168>
- What event bus is used to store and forward events to subscribers?
    - The event bus implementation doesn't have to matter
    - Knative Eventing is used in prototypes
- What protocol for transporting events?
    - The standard includes a schema and binding to Cloud Events.
    - SDKs support JSON over HTTP, but other transports for JSON could be used.

## What can TAG App Delivery do?
- Develop prototypes
    - use CD Events-driven flows in podtato-head (https://github.com/podtato-head/podtato-head-delivery)
- Encourage addition of event emitters to other services and tools, could use SDKs
- Participate in CDEvents meetings to further the spec and standard
    - [CDF Public Calendar](https://calendar.google.com/calendar/u/0/embed?src=linuxfoundation.org_mhf0kmgedn67ihni8r129avp24@group.calendar.google.com&ctz=America/Los_Angeles) 
    - Join the community: https://cdevents.dev/community/ 
- Idea: conventions for how to react and respond to events
- Check in again in June for opportunities

**Comment by afrittoli** [comment]
@joshgav it was good to meet you all and discuss TAG App Delivery + CDEvents.
Shall we meet again at the next TAG meeting on June 07?

**Comment by joshgav** [comment]
In discussion in Slack we determined that @afrittoli will come visit the TAG again in a couple months to provide an update and gather more contributors. In the meantime the TAG is sharing CDEvents with other projects and encouraging adoption.

Relatedly, the following couple proposals to OpenTelemetry have been opened which propose to integrate CDEvents events with OpenTelemetry events (aka traces). Using OpenTelemetry as a "transport" could make CDEvents useable quickly.

- https://github.com/open-telemetry/oteps/pull/223
- https://github.com/open-telemetry/opentelemetry-specification/issues/3168
