### ISSUE TITLE
[Platforms] Maintenance of platform capability categories

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#398]
As mentioned [here](https://github.com/cncf/tag-app-delivery/issues/378#issuecomment-1523841598) we'd like to help projects find their place in the list of platform capabilities in the definition white paper; and/or suggest changes or additions to the list.

We'd also like to compare and contrast the list of capabilities in the platforms paper with the categories in the CNCF [landscape](https://github.com/cncf/landscape) and [list of TAGs](https://github.com/cncf/toc/tree/main/tags) too.

It could be helpful to synchronize or correlate all of these lists to reduce complexity for users and projects.

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic.

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
