### ISSUE TITLE
Archive Operator whitepaper v2 issues

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/tag-app-delivery#403]
Since we are changing the cadence of releases, we will ask for contributions  to "latest" and not have a big-bang v2 release.

**Comment by joshgav** [comment]
Makes sense to me. Folks could pick up a particular section of the paper and propose to work on it anytime.

**Comment by joshgav** [comment]
Closed all pending issues for the operators v2 white paper. We will open individual issues for areas folks want to work on.
