### ISSUE TITLE
TAG chairs elections

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/tag-app-delivery#407]
### TAG App Delivery will vote for the next three co chairs of the working group. 

Primary role of  co chairs is to run operations and the governance of the group. The Chairs are responsible for ensuring that group meetings are planned and facilitated effectively, while also engaging group members in leadership roles. Effective facilitation includes (but is not limited to) the following activities:
* Setting the agenda for meetings
* Extending discussion via asynchronous communication to be inclusive of members who cannot attend a specific meeting time.
* Scheduling discussion of proposals that have been submitted
* Asking for new proposals to be made to address an identified need
* Facilitating the creation, ramp up and execution of working groups. 
* Partnering with Technical Leads to establish a roadmap and manage ongoing projects

## Nominations

Nominations will be open until **August 18th** . People can nominate themselves. If you plan to nominate somebody else please ensure that they accept the nomination. 

Once nominations are closed, the list will be provided to the TOC for voting. 

Nominations *need* to include the following information and should be posted as comments to this issue: 

* Name of the nominee.
* Affiliation of the nominee.
* Short CV - Three to five sentences. 
* Motivation for the role and previous contributions to the TAG. 
* Agreement on the how much time you can dedicate to the role.

Please keep the nomination short and concise.

**Comment by thschue** [comment]
I am nominating @AlexsJones as a Co-Chair for the CNCF TAG App-Delivery.

**Candidate Name**
Alex Jones

**Affiliation of the Nominee**
Alex is Director of Kubernetes Engineering for Canonical, Currently a Tech Lead of the CNCF TAG App Delivery and CNCF Ambassador.

Furthermore, he is member of the Governing Board for Keptn and Founder/Maintainer of K8sGPT.

**Short CV**
* Currently Director of Engineering at Canonical
* Previously Principal Engineer at Civo and VP of SRE at JP Morgan
* Long track record in Software Engineering, DevOps and SRE related jobs

**Motivation for this Nomination**
I started working with Alex during the final phase of the Operator Whitepaper. There, he added lots of value in very short time and became Tech Lead for the CNCF TAG App Delivery afterward. As Tech Leads, we initiated the creation of the Cooperative Delivery (now Platforms) Working Group and I learned that he is very knowledgeable and enthusiastic when it comes to progressive ways to deal with technologies.

Over time, we worked and are working together in many projects, as OpenFeature, Keptn and in the last few months for K8sGPT. 

I appreciate Alex's technical oversight and expertise and am enjoying to work with him personally. Given these things, I am convinced that he will be a great co-chair.

**Dedicated time for the role**
He already dedicates time as a Tech-Lead and I am sure that he can dedicate enough time for this role.

**Comment by AlexsJones** [comment]
I am withdrawing my application as chair.

**Comment by AloisReitbauer** [comment]
> I am withdrawing my application as chair.

Just to be clear you do not want to run as chair vs. your nomination  of Thomas

**Comment by thschue** [comment]
I am nominating @AloisReitbauer as co-chair for the CNCF TAG App Delivery.

**Candidate Name**
Alois Reitbauer

**Affiliation of the Nominee**
Alois is Chief Technology Strategist at Dynatrace, a Linux Foundation Europe Advisory Board member, and involved in Open Source Projects, such as Keptn and OpenFeature.

**Short CV**
* Currently Chief Technology Strategist at Dynatrace
* Founder of TAG App Delivery
* Maintainer and co-creator of two CNCF projects Keptn and OpenFeature
* Linux Foundation Europe Advisory Board

**Motivation for this Nomination** 
I worked together with Alois for several years, and his enthusiasm for Cloud Native Technologies (and App Delivery) motivated me to join this TAG. He is one of the founding members of this TAGs, initiated many initiatives in this TAG, he is very inspiring and cooperative when dealing with topics in the TAG. As such, he is almost always present in the TAG meetings and is always supportive when people want to step up in the TAG.

**Dedicated time for the role**
He is currently dedicating lots of time and I'm sure he will continue doing this

**Comment by AlexsJones** [comment]
> > I am withdrawing my application as chair.
> 
> Just to be clear you do not want to run as chair vs. your nomination of Thomas

I am withdrawing my own application

**Comment by thschue** [comment]
> 
Hello @amye!

Yes, and the nomination period ends on Friday.

**Comment by amye** [comment]
Ok perfect! Ping me when we're complete on nominations and I'll kick off a vote with the TOC.

**Comment by thschue** [comment]
Hello @amye! 

The nomination period is over now, I think we can proceed with the TOC vote.

The nominees are:
@AloisReitbauer - https://github.com/cncf/tag-app-delivery/issues/407#issuecomment-1677792217
@joshgav - https://github.com/cncf/tag-app-delivery/issues/407#issuecomment-1568847460
@thschue - https://github.com/cncf/tag-app-delivery/issues/407#issuecomment-1579279849

Thank you for your support!

**Comment by amye** [comment]
https://github.com/cncf/toc/issues/1151#issuecomment-1687065712 is open

**Comment by thschue** [comment]
The voting is finished, the newly elected chairs are:
@AloisReitbauer, @joshgav and @thschue.

Transition will be tracked in #452
