### ISSUE TITLE
TAG App Delivery at Kubecon Chicago

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#408]
This issue is to track planning for coordinated pre-day events for CNCF's app delivery-related projects at Kubecon Chicago.

I think we should try to coordinate the project meetings to make them more productive for all of us by enabling projects to learn from each other. Facilitating cross-project pollination and collaboration should be a focus at Kubecon when we actually have people together!

To help plan, here's a list of the project meetings from Amsterdam: https://kccnceu2023.sched.com/overview/type/Project+Meeting

And from Detroit: https://kccncna2022.sched.com/overview/type/Project+Meeting

As a strawman for debate: let's run an 8-hour App Delivery meeting on Monday November 6 and give ~30 minutes to each delivery-related CNCF project (that wants to) to present their latest innovations and answer questions from other projects. Let's also include time for lightning talks on new sandbox projects and ideas; and time for each WG to talk about their domains.

The target audience would be project and TAG maintainers, _not_ the general dev/ops audience at the rest of Kubecon.

We could start by reaching out to the delivery projects that held meetings in Amsterdam such as OpenGitOps, OpenFeature, Buildpacks, Knative, Backstage, LitmusChaos, Flux, Harbor, Carvel, and Keptn and asking them if they'd like to have 30-45 minutes in a shared program rather than their own meetings.

I started a related discussion in Slack at <https://cloud-native.slack.com/archives/CL3SL0CP5/p1685976894161329> if you prefer to chime in there. Thanks!

**Comment by joshgav** [comment]
A suggestion was to hold project meetings on Friday November 10 after Kubecon rather than Monday November 6 before Kubecon. The idea would be to make the pre-day about end users, and the post-day about maintainers. What do folks think?

**Comment by abangser** [comment]
I really appreciate the goal of supporting both end users and maintainers as a part of the KubeCon activities.

IME KubeCon raises a lot of really interesting maintainer questions/opportunities in large part because of the end user conversations. But also, the framing of those conversations can have a bit impact. 

For that reason I am really torn on moving the maintainer conversations to the end. My experience in Amsterdam bringing people together to raise the goals of this maintainer group for the next 6-12 months energised me to seek out conversations at the event that would help me learn more about use cases and interests in that area. At the same time, I wonder if that generated a bit of an echo chamber and allowing an end of conference get together would have let the needs of the community surface better.

All of that to say, I don't know 😅 But maybe there is a way to have a short meal/coffee/open space on the opposite day to the one where we invest most heavily in maintainer conversations so as to counteract the risks I raised?

**Comment by abangser** [comment]
Hey all, as mentioned at the Platforms WG call this week i have had some people raise interest in "Birds of a Feather (BoF) style conversations in Chicago. The topics raised so far are IMO TAG level chats (secrets w/GitOps, patterns for "package managing" in Kubernetes).

One idea is to set a meeting place during the conference that takes advantage of lunch tables out of hours for something like this.

WDYT both about the concept and if you think we should go forward with something like this how to implement it successfully to raise the right topics with a reasonable group of interested people given the amount of events during the week.

**Comment by angellk** [comment]
That's a great idea @abangser

Another idea could be taking advantage of the project pavilion and rotating through different project booths? Like a mini-TAG project pavilion crawl at set times other projects are available.

**Comment by abangser** [comment]
> That's a great idea @abangser
> 
> Another idea could be taking advantage of the project pavilion and rotating through different project booths? Like a mini-TAG project pavilion crawl at set times other projects are available.

Love it! Given we are trying to get more involved in the project reviews etc, maybe we could get a sponsor for a prize if people get stamps from every project? 🤔

**Comment by joshgav** [comment]
Here's an update on what we've been allocated. Wanted to share this info so others can help with planning - thank you all!

First, TAG App Delivery has been allocated **a meeting room at the conference center on Monday from 8-12pm** (not 8 hours as I proposed above :laughing:). The meeting space will hold about 20 people and is intended for us to discuss work in our TAG, WGs and governed projects. Let's discuss the agenda here, such as soliciting some of our projects to come chat with us and each other; and getting updates from WGs like Platforms and Artifacts.

Second, the TAG will also will have **a kiosk in the project pavilion in the PM**; this kiosk includes a monitor, a small desk and some display space. We can have small presentations there and share info about the TAG, WG and governed projects.

 Here are the times for the booth, I'll be looking to folks to help staff it:
- Tuesday, November 7: 3:30 - 8:00 PM
- Wednesday, November 8: 2:00 - 5:00 PM
- Thursday, November 9: 12:30 - 2:30 PM

Thanks again for your help!
