### ISSUE TITLE
Project review: Microcks

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#411]
@yada and @lbroudoux presented [Microcks](https://github.com/microcks) to the TAG on 2023-05-17. 

Recording of the presentation begins at <https://youtu.be/UnNozJiNcz8?list=PLjNzvzqUSpxJ0JfD6vrdF5bsuBaJQ2BRT&t=1600>.

Original notes from the presentation are [here](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#heading=h.2npmztrgu5sw) and are copied below for discussion.

## Resources
- https://github.com/cncf/sandbox/issues/37
- https://github.com/microcks
- Presentation: [Slides](https://docs.google.com/presentation/d/1wcX6JHDeaOlJMiwX2PfzgM6JkoU-QY0zPJN6CWpiI0Y/), [PDF](https://drive.google.com/file/d/1bBMquCAyY59xsSOvBqzD8nFPlkipMGvL/)

## Why?
- Accelerate development of APIs
- Secure APIs (from a QA perspective to avoid breaking changes and commit on your consumers promise)
- Enable collaboration between developers and product owners
- Gather all types of APIs and protocols
- Quote: "Releasing v1.0 is no problem. It's later versions where you might have conflicts, this 'secures' and verifies behavior is as expected."

## What? 
- Generate all kinds of APIs via a UI
- Mock/simulate APIs for integration tests
- Send requests per schema to test endpoints
- Generate Kafka messages to send to consumer
- Listen to Kafka messages to verify conformance to schema
- Use as part of CI/CD pipelines for verification
- Integrates with other projects
- Support for import of specs for SOAP, OpenAPI, gRPC, GraphQL, AsyncAPI, CloudEvents, Postman collections
- Use AsyncAPI for:
  - Kafka
  - MQTT
  - WebSocket
  - RabbitMQ
  - NATS
  - Google Pub/Sub
  - AWS SQS and SNS
- Includes [Hub](https://hub.microcks.io/) to share API descriptions ([How to contribute an API package](https://hub.microcks.io/doc/how-to-contribute))

## Future
- Develop client library (SDK) for Microcks to publish and retrieve definitions

**Comment by yada** [comment]
Thanks to the TAG App Delivery community for the warm welcome of our submission 🙌

Direct link to the 2nd presentation (with a live demo) as a follow-up during TAG App Delivery bi-weekly meeting, see:
https://youtu.be/UnNozJiNcz8?t=1608

Regarding the future and full details of the project roadmap (agile and community-driven), see:
https://github.com/orgs/microcks/projects/1

**Comment by yada** [comment]
BTW, We have created the #microcks channel in the CNCF slack if you have any questions or would like to know more on the project 🙌

**Comment by scottrigby** [comment]
This looked really great @yada. Like how you've set up the project so far, and feels like on the road to a well-maintained project that follows cloud native principles. Added support in cncf issue. Looking forward connecting more on this soon ❤️

**Comment by joshgav** [comment]
Microcks is now part of CNCF, congrats @yada and talk to you soon.

**Comment by yada** [comment]
Thanks, @joshgav and the TAG App Delivery team.
