### ISSUE TITLE
Reduce decision-making required by platform builders

### ISSUE THREAD

**Issue by Saim-Safdar** [cncf/tag-app-delivery#412]
While talking to one of my friends during the weekend "he introduced the concept of decision-making beneficial to many while many of us reading the whitepaper", which can relate to shortening the loop for decision-making for platform engineers, while I'm exploring some of the content on that domain I came across this informative article, James identifies common "bugs" that frequently cause unnecessary delays in decision-making. He recommends several alternative strategies to help you make a final judgment call in as minimal time as possible [Fast-forwarding decision-making](https://theengineeringmanager.substack.com/p/fast-forwarding-decision-making). Looking for other's opinions is it possible going forward to have a dedicated section b/c I see the challenge with the platform has many components and services glued together and understanding those require(s) a lot of time, having a suggestion on what to consider for the decision making while choosing a Minimum Viable Solution, or effective strategy for shortening the decision making would help a lot, I believe we might have some content in the past, there's an exploration of stitching together.

**Comment by joshgav** [comment]
Hi Saim - I hear you that many decisions face platform builders today. I think the solution you're suggesting is that we in the CNCF/TAG/WG provide guidance and "paved paths" for building such platforms. That guidance could reduce the number of decisions architects must make and perhaps make some decisions for them.

IMO this ask follows naturally from our initial paper - folks agree to the ideas and want to know practical tactics for putting them in practice.

Based on feedback like yours we're pursuing this now by:

- Crafting a platform maturity model (#381) describing the aspects of platform adoption and what maturation of these aspects could look like
- Crafting model platforms for specific use cases (#293)

We also want to learn directly about the decisions platform architects are faced with to better direct our own attention, so any presentations and interviews with platform teams would be great, something we're trying to pursue in #315.

What other actions do you suggest? Thanks!

**Comment by joshgav** [comment]
Thanks for your thoughts @Saim-Safdar, closing this now.
