### ISSUE TITLE
[wg-artifacts] Tasks for new WG

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#417]
Now that the Artifacts WG has been chartered we have a few tasks to be done so I'm listing them here. @afflom are there more?

- [x] Elect 2 chairs to manage the WG
    - #420
    - #427
    - #428
- [x] Add WG info to the WG README 
    - #421
- [x] Add WG info to the TAG web site
    - after #426
- [x] Schedule meetings
- [x] Create a repo for the WG in GitHub
    - https://github.com/cncf/toc/issues/1122
- [x] Add WG chairs to CODEOWNERS in this repo

**Comment by afflom** [comment]
I think that this is a great start. Everything else that  comes to mind would  be dependent on the repo creation.

**Comment by SteveLasker** [comment]
Link to electing [Alex](#420) and Ram (TBD)

**Comment by joshgav** [comment]
Also need to update the CODEOWNERS file here to grant admin rights to the WG chairs.

**Comment by afflom** [comment]
> Also need to update the CODEOWNERS file here to grant admin rights to the WG chairs.

PR linked here.

**Comment by joshgav** [comment]
Repo has been created at <https://github.com/cncf-tags/wg-artifacts> and @afflom and @rchincha have been invited as admins.

**Comment by joshgav** [comment]
All tasks have been completed! Thank you @afflom and the Artifacts working group! For more info check out the home page at <https://tag-app-delivery.cncf.io/wgs/artifacts/>
