### ISSUE TITLE
Nominate Alex Flom as WG Artifacts chair

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#420]
With WG Artifacts chartered we need to select 2-3 people to chair it. Chairs schedule and lead meetings, facilitate technical discussions, and keep timelines and roadmaps for deliverables on track.

I'd like to nominate @afflom (Alex Flom) as one of the chairs of WG Artifacts. He's been working on patterns and implementations for artifact storage and retrieval for years and was instrumental in bringing together and defining the charter for the working group.

In his own words:

Thank you for considering me for a leadership position in the CNCF TAG App Delivery Artifacts WG. Here’s a little about me:

I was in the US Navy for 11 years, where I was able to work in various roles spanning system administration, network administration, RF systems administration, IT curriculum development, information systems engineering, and leadership.
After I was honorably discharged in 2018, I focused  on air-gapped system automation, network automation, and gitops workflows for various government systems.

While at Red Hat, I wrote the conceptual model for https://github.com/openshift/oc-mirror, wrote the conceptual model for https://github.com/ortelius/emporous-go, and now focus on automating regulatory compliance management by leveraging https://github.com/usnistgov/OSCAL in Continuous Compliance workflows.

The recurring theme of my career is moving software between information systems, most of which are air-gapped. To this end, I created Universal Object Reference (UOR), the conceptual model of Emporous, which is an implementation of Object Oriented Ontology; a metaphysics theory that observes Enriched Category Theory in nature. In more traditional information systems terms, UOR provides name resolution for content addressed artifacts.

In a leadership role within the Artifacts WG, I would leverage my unique perspective and experiences to guide and assist the working group in executing under the Artifacts WG charter to improve software artifact management across the CNCF and the internet.

----

You can support Alex by +1'ing this issue and/or the corresponding PR. Thank you!

**Comment by rchincha** [comment]
+1

**Comment by AlexsJones** [comment]
I support this notion

**Comment by roberthstrand** [comment]
+1 (+011110010110010101110011)

**Comment by AaronFriel** [comment]
+1

**Comment by AaronFriel** [comment]
@joshgav As we're bootstrapping this WG, we discussed in the call today considering this nomination accepted by unanimous consent. As you're the TAG chair, I think it make sense for you to confirm that and close?

**Comment by thschue** [comment]
+1

**Comment by hongchaodeng** [comment]
+1

**Comment by AloisReitbauer** [comment]
+1

**Comment by Jenniferstrej** [comment]
+1
