### ISSUE TITLE
New GitHub repository for WG Artifacts

### ISSUE THREAD

**Issue by ncdc** [cncf/tag-app-delivery#424]
We are requesting a new GitHub repository in the github.com/cncf-tags organization for the Artifacts Working Group. This will be a repository in which we can collaborate on designs and everything else related to artifacts. Happy to provide additional information as needed.

Possible repo name ideas: either wg-artifacts or artifacts-wg.

TIA!

**Comment by rchincha** [comment]
Slack channel already a precedent - named wg-artifacts
