### ISSUE TITLE
Nominate Ramkumar Chinchani as WG Artifacts chair

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#427]
WG Artifacts would like to nominate @rchincha as a WG chair alongside @afflom (see #420). Ramkumar leads CNCF's [zot](https://github.com/project-zot) container registry project.

Please share your support by +1'ing this post. We'll open a PR to finalize chairs shortly.

In @rchincha's own words:

Thank you for considering me for a leadership position in the CNCF TAG App Delivery Artifacts WG.

I have about 18 years of experience working in silicon valley companies big and small, on projects involving storage, networking, security and software distribution.

Currently, I am with the containers group at Cisco Systems, Inc., with the mandate to securely build and distribute products using industry standard techniques and technologies.

I consider it my good fortune that significant parts of this work (such as the *zot* and *stacker* projects) could be made available as open source allowing us to contribute and get involved with the community. Consequently, I am in a favorable position of being involved in both CNCF and OCI communities.

Why is the artifacts work important? Because in a rapidly growing open source world, we are increasingly playing the role of chefs instead of farmers, and standardization greatly helps expedite.

In the leadership role within the Artifacts WG, I will try to ensure that we listen to right voices and get the right folks together to solve the problems at hand well.

**Comment by FeynmanZhou** [comment]
Support +1.

**Comment by AaronFriel** [comment]
@joshgav As I replied on #420 - we discussed in the call today considering this nomination accepted by unanimous consent. Can you confirm that this is OK and close this?

**Comment by sajayantony** [comment]
+1 supportin Ram here. Ram has helped connect multiple projects and been a great collaborator on OCI as well.

**Comment by cmoulliard** [comment]
+1

**Comment by thschue** [comment]
+1

**Comment by Jenniferstrej** [comment]
+1
