### ISSUE TITLE
2023 Sandbox Project Review - Porter

### ISSUE THREAD

**Issue by angellk** [cncf/tag-app-delivery#434]
2023 Review of Porter

https://github.com/cncf/toc/pull/951

**Comment by joshgav** [comment]
@AloisReitbauer you indicated you might lead this one.

**Comment by joshgav** [comment]
cc @hypernovasunnix per <https://github.com/cncf/foundation/blob/main/project-maintainers.csv#L697>

**Comment by joshgav** [comment]
This was closed by TOC as complete :+1:
