### ISSUE TITLE
cdk8s - Review last year's Sandbox review or Sandbox application approval

### ISSUE THREAD

**Issue by angellk** [cncf/tag-app-delivery#436]
https://github.com/cdk8s-team/cdk8s/issues/280
Project was [admitted to Sandbox](https://www.cncf.io/projects/cdk-for-kubernetes-cdk8s/) on November 10, 2020

**Comment by joshgav** [comment]
Thank you for opening this issue @angellk. TOC has decided to change the way project annual reviews are conducted and so we won't need to review previous year's reports for now. I'll go ahead and close this issue.
