### ISSUE TITLE
Platform maturity model details section: Adoption

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#441]
This is to track the progress on this specific details section.

Please see https://docs.google.com/document/d/11J_RpaUwydNNBg5aVjH5Uzn8i-b4urEtJzwR86XezFQ/edit#bookmark=id.jwmitrq3pcds for more detail.

Everyone is enabled and encouraged to be a reviewed through Google Doc comments. To become a contributor directly please reach out to "Abby Bangser" or "Josh Gavant" on CNCF slack or via the Google Document comments.

**Note, it would be great to add another person to pair on creating and editing this section**

This is a blocker to #381

**Comment by joshgav** [comment]
I'm going to work on an initial description of this aspect in the next couple days. Chime in here if you'd like to review and refine it together, perhaps we can sync up early next week. Thanks!

**Comment by joshgav** [comment]
Quick update: @menzenski and @victorjunlu have done great work creating a foundation of content describing this aspect in [our working doc](https://docs.google.com/document/d/1dn5_yIuEiaZNpOEcQEQ9XTJ2UUsve57fEPOZGi4FrxM/edit), thank you both. We're continuing to iterate asynchronously and discuss in Slack, and plan to meet live later this week (9/4-8).

The doc with our work in progress is here: <https://docs.google.com/document/d/1dn5_yIuEiaZNpOEcQEQ9XTJ2UUsve57fEPOZGi4FrxM/edit>

**Comment by abangser** [comment]
I am going to close this as the iterative work in Google Docs has been complete. For final review see https://github.com/cncf/tag-app-delivery/pull/464 and #381.

Thank you to everyone who contributed in the WG calls and in the Google Doc 🙇
