### ISSUE TITLE
Platform maturity model details section: Interface

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#442]
This is to track the progress on this specific details section.

Please see https://docs.google.com/document/d/11J_RpaUwydNNBg5aVjH5Uzn8i-b4urEtJzwR86XezFQ/edit#bookmark=id.jwmitrq3pcds for more detail.

Everyone is enabled and encouraged to be a reviewed through Google Doc comments. To become a contributor directly please reach out to "Abby Bangser" or "Tsahi Duek" on CNCF slack or via the Google Document comments.

**Note, it would be great to add another person to pair on creating and editing this section**

This is a blocker to #381

**Comment by techmaharaj** [comment]
I've added the first round of descriptions to the document and resolved some suggestions that Tsahi had to make.

**Comment by abangser** [comment]
I am going to close this as the iterative work in Google Docs has been complete. For final review see https://github.com/cncf/tag-app-delivery/pull/464 and #381.

Thank you to everyone who contributed in the WG calls and in the Google Doc 🙇
