### ISSUE TITLE
Platform maturity model details section: Operations

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#443]
This is to track the progress on this specific details section.

Please see https://docs.google.com/document/d/11J_RpaUwydNNBg5aVjH5Uzn8i-b4urEtJzwR86XezFQ/edit#bookmark=id.jwmitrq3pcds for more detail.

Everyone is enabled and encouraged to be a reviewed through Google Doc comments. To become a contributor directly please reach out to "Abby Bangser" or "Josh Gavant" on CNCF slack or via the Google Document comments.

**Note we are actively looking for one to two leads for this section!**

This is a blocker to #381

**Comment by Saim-Safdar** [comment]
I will be working on this alongside Puja. Making some progress via doc.
