### ISSUE TITLE
Silver Surfer sandbox submission review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#446]
Silver Surfer has been [proposed to CNCF sandbox](https://github.com/cncf/sandbox/issues/53). This issue is to track discussions and reviews of Silver Surfer to help with deciding whether to accept it in CNCF sandbox.

We've asked @Abhinav-26 and team to join an upcoming TAG meeting to discuss the following about the project:

- the values this project proposes to end users
- the project's high-level technical architecture
- the project's near-term roadmap
- state of the project's community and governance
- comparison with existing projects

**Comment by Abhinav-26** [comment]
Thanks @joshgav for creating this issue. 
Looking forward to the meet.

**Comment by Abhinav-26** [comment]
Hello @joshgav, any updates on this?

**Comment by joshgav** [comment]
Hi @Abhinav-26 - sorry for the delay, I'll post the notes and recording to this issue shortly!

**Comment by Abhinav-26** [comment]
Sure @joshgav, thanks for the response.

**Comment by joshgav** [comment]
Here's the write up from Silver Surfer's presentation to the TAG on 9/6. The recording starts here: <https://youtu.be/vi49fpVI-_I?t=800>

## Value props
- Make cluster upgrades more reliable
- Evaluate API version of all K8s resources and suggest path for upgrade

## Problems with upgrade
- cluster version compatibility
- downtime and service disruption
- config management, custom resources
- addons must also be considered/upgraded
- disparate tools, no tool which solves all problems related to upgrade e.g.
  - kubeval - validates config files, not maintained
  - kube-no-trouble - checks for deprecated APIs
  - kubepug - doesn't provide migration path
  - kubeconfirm - inspired by kubeval, for config files

## Architecture
- kubedd - client side tool which connects to API server using kubeconfig context
- Uses kubectl.kubernetes.io/last-applied-configuration

## Community
- 7 contributors
- Supported by Devtron: https://devtron.ai/

## Roadmap
- generate new manifests for next version
- create support for pre-upgrade checks for Helm chart updates
- check CRDs
- publish as homebrew package for Mac and Linux
- run as a server, install in cluster, via Helm chart
- establish "migration policies" to alert on upgrades if cluster isn't ready

## Questions
- Is scope right for CNCF? May be appropriate as part of Kubernetes itself?
  - Compare https://eraser-dev.github.io/eraser/docs/
- Maybe consider relationship to https://kcl-lang.io/ for high-level schema validation
- Consider presenting to the CLI SIG in K8s too

**Comment by joshgav** [comment]
Thanks again for the presentation @Abhinav-26! We'll close this issue now.
