### ISSUE TITLE
IO Flow sandbox submission review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#447]
IO Flow has been [proposed to CNCF sandbox](https://github.com/cncf/sandbox/issues/55). This issue is to track discussions and reviews of IO Flow to help with deciding whether to accept it in CNCF sandbox.

We've asked @mayur-yambal and team to join an upcoming TAG meeting to discuss the following about the project:

- the values this project proposes to end users
- the project's high-level technical architecture
- the project's near-term roadmap
- state of the project's community and governance
- comparison with existing projects

**Comment by Shashwattiwari02** [comment]
Hi @joshgav, I regret to inform you that we will need to reschedule tomorrow's meeting. Due to an urgent business trip that has come up, our team will be unable to attend as planned. We sincerely apologize for any inconvenience this causes. 

Would it be possible to postpone our discussion to next week's meeting instead? We appreciate your understanding and look forward to connecting then to continue our presentation on IO Flow.

**Comment by joshgav** [comment]
Hi @Shashwattiwari02, thanks for the heads up. Could you present at our November 1 meeting? (The next meeting on 10/18 already has a presentation.)

Here's the agenda doc: https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit

**Comment by joshgav** [comment]
Hi @Shashwattiwari02 - are you still able to present IO Flow at our Wednesday 11/1 meeting? We look forward to hearing from you then. If you'd like to chat beforehand visit our [#tag-app-delivery](https://cloud-native.slack.com/archives/CL3SL0CP5) channel in CNCF Slack.

**Comment by Shashwattiwari02** [comment]
Certainly @joshgav, we're all set to present IO Flow on Wednesday, 11/1 Meeting. Looking forward!

**Comment by joshgav** [comment]
Thank you @mayur-yambal, @sudhir-raut and @Shashwattiwari02 for joining TAG App Delivery and presenting on IOFlow. Here's the collateral from their presentation and a write-up of key points.

- Repo: <https://github.com/iauroSystems/io-flow-core>, <https://github.com/iauroSystems>
- Home page: <https://www.iauro.com/io-flow>
- Presentation: TBD
- Recording: <https://www.youtube.com/watch?v=jbQ7nOqSu0c?t=200>

## What is it?
- IO/Flow is a cloud-native, open source workflow engine
  - Runs in containers
  - Instances are independently scalable, e.g. in multiple pods
- Value propositions
  - Eliminate inefficient operations, save time, reduce costs via automation
  - Optimize resource utilization
  - Standardize business processes
  - Monitor business processes in real-time
  - Scale process execution smoothly
- Features
  - Intelligent task management
  - Smart dashboards
  - Easy integration
  - Realtime updates
  - Process monitoring
  - Workflow orchestration

## Architecture
- Typical flow
  - create workflows in a designer using BPMN models
  - execute workflows via API calls
  - monitor workflows via API calls and dashboards
  - optimize workflows via AI/ML
- Basic resource types
  - Gateways - conditional gates on logic flow, e.g. "if true then...." and parallel execution
  - Events - on Start, on End, on Timer
  - Tasks - system, user, compound
- Connectors - integrate from tasks with REST, GRPC, Python, OpenAI, shell, JS
- Doesn't have to be hosted in K8s, runs as a standalone container
- Workflows are described in JSON and submitted via APIs
  - properties: `properties`, `stages`
- APIs
  - CRUD "business process definitions" 
  - CRUD instances
  - CRUD tasks
- No GUI included today but is on the roadmap

## Community
- [Iauro](https://www.iauro.com/) uses this with their customers already
- Used by Telefonica, Airtel and some other companies, and they contribute too
- Want to join CNCF sandbox to increase contributions and usage

## Comparisons
- Argo Workflows, Keptn, Airflow - oriented to app delivery - IOFlow is oriented to business processes

## Questions
- Are there CRDs for the APIs?
  - First use case is business processes, but next will do K8s CRDs
- Does it emit OpenTelemetry events? Does it integrate [CDEvents](https://cdevents.dev/)?
- Compare to keptn? Keptn orients on app deployment, IOFlow is for any workflow type
- Why is this "cloud-native" in particular?
  - Built per cloud-native principals
  - Can execute cloud app delivery workflows too
- Share copy of deck

**Comment by Shashwattiwari02** [comment]
Thanks @joshgav, it was a pleasure presenting IO Flow. We're looking forward to the TOC meeting with enthusiasm!

The presentation deck is available on [Github](https://github.com/cncf/tag-app-delivery/files/13235804/IO.Flow.Presentation.-.CNCF.Sandbox.pdf) & [Drive](https://drive.google.com/file/d/1SJGrgpG_vCSyT8RO1cJhf_-iMrTWpYqj/view) . I've also added it on the TAG Meeting Doc

**Comment by joshgav** [comment]
Thanks @Shashwattiwari02, I also added that link to my comment :+1: 
Closing this issue now, good luck on TOC review!

**Comment by Shashwattiwari02** [comment]
Hey @joshgav, could you confirm the IO Flow TOC Meeting schedule and share details of any associated ticket or document for tracking purposes?
