### ISSUE TITLE
Blog post on how to get started with contributing to the TAG app delivery - WG Platforms

### ISSUE THREAD

**Issue by techmaharaj** [cncf/tag-app-delivery#495]
Idea: Create a blog post about how can people get started on contributing to the TAG app delivery. Largely on the line of creating an issue, sharing the idea, joining the meetings, discussing the outcomes, TG, etc., and eventually publishing the blog post.

**Comment by menzenski** [comment]
I think there's potential also to tie into the existing Platforms Working Group Charter, specifically the part of that document which discusses the working mode of the group: https://tag-app-delivery.cncf.io/wgs/platforms/charter/#working-mode--expected-outcome .

**Comment by abangser** [comment]
Agreed @menzenski I am going to take a stab at some work to codify a process and I know @adminturneddevops is interested in this too. 

I will look to first create a Google doc and then a PR with the content and will comment on this issue as the work progresses for feedback/transparency as I see this issue as the culmination of that work. 

My target timeframe is an MVP ready in days/weeks rather than a highly structured thing that takes weeks/months to get rolled out 🤞

**Comment by AdminTurnedDevOps** [comment]
Something that I was thinking here are some basic steps and then dive into it more in-depth. For example, I think a great first step is to read through the CNCF WG Slack channel that you think you may be interested in and ask the simple question of "hey, anywhere I can help out?". We could go more in-depth as well and say something like "here are some common questions you can ask to get yourself started"

**Comment by abangser** [comment]
Great idea @AdminTurnedDevOps, I think that is maybe another angle on the doc I just wrote [here](https://docs.google.com/document/d/1HyjXbR2VJ5Pj6qn7wASvEY5tH7YhTAVm96Y4BuOv1NE/edit?usp=sharing). As in, some people come with proposals and some just come to interact and we need to support both.

Can you take a look at my suggestions around supporting early contributors proposals and tell me what you think? Please keep in your mind how it felt to come with your idea around the tech stacks and what we can/should do to make that easier for you now and future yous!

**Comment by AdminTurnedDevOps** [comment]
@abangser Awesome, thanks! I added in some suggestions and comments (hope that's okay). Let me know if you have any questions. Happy to help!

**Comment by techmaharaj** [comment]
@abangser I had a look at this too and left one suggestion on the steps, the rest of it looks pretty good. 

Further, in my head, I would read the current headings as "Who we are?", "What we do?" and "How you can get started?" - only to keep it simple and because these _might have better relatability_ for first-timers as compared to the current titles. WDYT?

**Comment by abangser** [comment]
Thank you both for taking a look!

@AdminTurnedDevOps I have taken your suggested content and made that into the basis of a blog that encourages TAG contributions at the bottom of the doc. @techmaharaj I have added your suggested titles there.
_(also, @techmaharaj I am not sure it is clear, but everything above the line is me proposing the the TAG, not what I would recommend for a public blog!)_

I have also taken a stab at a second blog which is more targeted for the Platforms WG as I am keen to encourage and support these blog ideas that have been coming in. So this blog is a kind of example implementation of the proposal above. The big thing missing is the template issue for people to submit with, but if the blog looks good I will go there next! PTAL if you have a minute!

**Comment by krumware** [comment]
I added some content in-line.
Also, included a reference to something cartografos added recently which I think might be helpful for getting feedback on blogs: https://github.com/cncf/cartografos/issues/67

**Comment by techmaharaj** [comment]
Hi, @abangser, I looked at this and left a few suggestions for the overall flow. We still need to figure out a few things like the questions in the templates, review and approval process etc. We can discuss on this. Meanwhile, do have a look and suggest the next steps.
