### ISSUE TITLE
Blog Post idea - summary/reflections of 2023-11-06 TAG App Delivery pre-day meetup

### ISSUE THREAD

**Issue by menzenski** [cncf/tag-app-delivery#496]
Opening a GitHub issue to track the suggestion that @abangser made in Slack here: https://cloud-native.slack.com/archives/CL3SL0CP5/p1699294922748169

I will try to write up a version of this post tonight (if someone else is able to do so sooner, please feel free).

**Comment by menzenski** [comment]
I started on this, here is a link that allows anyone to edit (please feel free): https://docs.google.com/document/d/12fX4vuc2aGmTYcN3M3fQ9cv1bmbGYv-NweWCabT1uSY/edit

**Comment by abangser** [comment]
Thanks for getting this started @menzenski! I want to take a deeper look, but I want to start with a more meta question: What is our goal from this blog? I think that the current format is taking the approach of documenting the meeting progression, almost in the way of minutes. Another angle we could take is trying to summarise key takeaways/patterns, and I am sure there are others! Did you have a thought on why one format or another would be more effective?

**Comment by abangser** [comment]
@menzenski this is the video that we have from the session: https://www.youtube.com/watch?v=NZCmYRVziGY

I am thinking that we can link to this with a bit more of a "teaser" blog. WDYT?

**Comment by abangser** [comment]
I think this is unfortunately a bit past the time where we can effectively put this content together. I would recommend that if we want wrap up blogs we should aim to allocate them to people _before_ the event so as to have a focus on collecting the necessary details. I will look to make this a suggestion for the next KubeCon (NA 2024 in SLC).

Thanks for the great idea for this and I look forward to making content like this in the future!
