### ISSUE TITLE
Extend CNCF Platforms White Paper to include external facing platforms

### ISSUE THREAD

**Issue by jpmorgenthal** [cncf/tag-app-delivery#499]
"Because these platforms target no more and no less than an enterprise’s internal users we often refer to them as internal platforms."

Why define this constraint? Platforms could support both internal and external users to an enterprise. The methodologies, practices and procedures for developing a platform applies equally whether used by only internal enterprise users or external users.

**Comment by krumware** [comment]
Hi @jpmorgenthal, it's on our radar. We've been actively discussing this topic and a number of the participants agree (me included), it just hasn't yet been reincorporated into the paper in the current version. I believe it is an important thing to highlight in upcoming updates, and will likely also be surfaced in the coming Platform as Product white paper. Definitely join us in the meetings if you're able and weigh in on this topic.

If you want to go ahead and expand on the topic here to start scaffolding some language as well I'm happy to also weigh in and support.

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic (or create an associated blog post).

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
