### ISSUE TITLE
About the edge of layer2 and layer3

### ISSUE THREAD

**Issue by mmpei** [cncf/tag-app-delivery#5]
i have read the doc for App Delivery and agree with the point of separated layers.
but there are still some confusion. 
by the design layey2 and layer3 are two different layers and layer3 is a controller in local k8s while layer2 is a micro-service in our manage cluster. how do they do interaction? and if there are multiple k8s clusters(one layer2 and multiple layer3). and if the deploy policy is complex like grouped release with multi-versions.

**Comment by thschue** [comment]
Is there still something to clarify on this issue or could we close this (it's quite old)?
