### ISSUE TITLE
Feedback process for the Platform Engineering Maturity Model

### ISSUE THREAD

**Issue by jpmorgenthal** [cncf/tag-app-delivery#500]
What is the process for gathering and incorporating feedback and learning?

I quote from my DXC whitepaper entitled "Digital platforms accelerate delivery of modern applications ", 

"Enterprises are turning to digital platforms to drive positive business outcomes such as lower costs, faster speed to market and increased consistency. This paper details the role digital platforms can play in application development and provides real-world examples of how they are delivering significant benefits to companies. "

https://dxc.com/us/en/insights/perspectives/paper/digital-platforms-accelerate-delivery-of-modern-applications

Measurement with regard to maturity for the enterprise must take into account these factors or will suffer the fate of becoming an engineering silo.

**Comment by abangser** [comment]
Hi @jpmorgenthal , thanks for reaching out! The process for suggestions is through issues and PRs. We highly recommend that people join calls for the WG (details here: https://tag-app-delivery.cncf.io/wgs/platforms/) to share context but that isn't required. What is requested is a shared understanding of what the current issue is and how the change will support an improvement.

To that end, I see your suggested quote but I am not sure how this is in contrast to or where this would extend the current maturity model. Can you please share an example of where in the current paper there is a concern and what you may suggest in its place?

Thanks!

**Comment by jpmorgenthal** [comment]
Hi, I believe you misunderstood me. The first line of my original message
was a quote from your paper under measurement. I wasn't inquiring about the
process. I should have put that in quotation marks, apologies.

So, as to my follow on quote, I believe measurement in today's business
world is desperately seeking a way to model return on the investment, which
was the first characteristic. Measurement needs to address the variables
that feed return and user satisfaction is not a satisfactory value to
determine success.

**Comment by abangser** [comment]
Hi @jpmorgenthal , first of all I am so sorry for the long delay on responding here. 

Secondly, I am sorry that there was a misunderstanding there and the working group has absolutely felt the same as you in the following point:

> I believe measurement in today's business world is desperately seeking a way to model return on the investment

That being said I think I am still not quite sure what your suggestion is here. Are you suggesting that there is a different framework we could introduce to make the measurement more effective for readers? Or are you just adding your vote for the value of this section? I am happy to discuss further here or if a more synchronous chat either via [CNCF slack](https://communityinviter.com/apps/cloud-native/cncf) (you can find me with "abby bangser") or a call would be best we can find time for that too!

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic (or create an associated blog post).

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
