### ISSUE TITLE
RFC: The two-sided markets theory and the Maturity model

### ISSUE THREAD

**Issue by nagyv** [cncf/tag-app-delivery#501]
I finally managed to jot down my thought on what engineering platforms / DevOps platforms / IDPs can learn from the theory of economics, namely two-sided markets.

Feedback is welcome: https://docs.google.com/document/d/1XCeP0kntq0bTCf2xO9Cf6K-_SsTUH4zJ4MrEdT7jwcA/

I'd be happy to publish the **final** post on the TAG blog if there is interest in it.

**Comment by krumware** [comment]
Lots of great thoughts in here, thank you! Added some comments

**Comment by abangser** [comment]
Thanks so much for sharing this @nagyv, I think it is a topic that is only starting to get airtime and would love to see more of this discussed and published!

I have added a few comments that I think could be interesting to discuss either in threads there or via one of the WG calls (next one is Nov 28).

The one thing to call out here is that we need to sort out what kind of TAG sign off is necessary for publishing to the blog. I would like to check with @joshgav as he is both a WG and TAG lead and can hopefully help us clarify and get this unblocked quickly!

**Comment by techmaharaj** [comment]
Loved the analogy, being a business student and a software professional, I liked the parallels that you've drawn here. 
I too left a few comments on this. 

@abangser for the review process (and tracking, interactions, etc.) I suggest creating a thread in wg-platforms slack for every blog post that is proposed. That way we all know what blog posts are in progress without looking at GitHub. Secondly, whatever discussions/clarifications are required for a blog post, we can do it in that specific thread so discussions are not scattered and easy to find. And then we can simply post a link to the Slack thread in a GH issue, so everyone can follow the discussion as well. 

WDYT?

**Comment by abangser** [comment]
Glad to hear this resonated @techmaharaj, it's a great vote of confidence for publishing!

And great idea for slack, though we did actually have a thread for this one but it got buried 😥 we definitely need to iterate on what good looks like to visibility of WIP. 

For this specific post, @nagyv I'd suggest opening a PR to the website with the blog content for final review by the TAG leaders. The only blocker I see in the doc is the point about selling Gitlab a bit hard. As a community post I think we would lean towards the wording @roberthstrand suggested. 

Happy for you to make decisions as you port it to the PR and final review can occur in that form. 

Thanks again for the great work and open review Viktor!

**Comment by earth2marsh** [comment]
Sorry, I must have missed the thread in Slack and only noticed it b/c it was in the agenda for this week's meeting. My apologies in advance for littering the PR with comments, but I was struggling with what seems like a premise that platform economics (i.e., 2-sided markets in economics) must necessarily apply to developer platforms.

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic.

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
