### ISSUE TITLE
Do we want feedback buttons on pages of the site?

### ISSUE THREAD

**Issue by cjyabraham** [cncf/tag-app-delivery#506]
I've recently got the page feedback buttons to work on the [CNCF Glossary site](https://glossary.cncf.io/abstraction/) (see at the bottom of the page). They feed events into our cncf.io Google Analytics 4 property which we can later create reports on to see which pages get good feedback, which do not.

<img src="https://github.com/cncf/cartografos/assets/463160/71e21b1f-90ad-44a3-acca-063619fb4adc" width=400>

Would we like this feature activating for the TAG App Delivery site? If not, please just close this issue.

**Comment by cjyabraham** [comment]
Any thoughts @joshgav ?

**Comment by joshgav** [comment]
Hi @cjyabraham, we certainly love feedback, so sure let's add these!

It would really help us improve if we get reports with this feedback and information on traffic patterns and user behavior. Maybe you could share all this with us once per quarter or so @cjyabraham, WDYT?

**Comment by cjyabraham** [comment]
Sounds good. I've submitted a PR: https://github.com/cncf/tag-app-delivery/pull/510

**Comment by cjyabraham** [comment]
This is deployed. In a couple of weeks I'll produce a report to see if there's any useful data.
