### ISSUE TITLE
[TRANSLATE] Translate Platform whitepaper into Chinese

### ISSUE THREAD

**Issue by node** [cncf/tag-app-delivery#507]
Recently our website enable i18n support(for Chinese example), welcome more contribution of translation.
@rootsongjc from cloudnative community in China translated Platform whitepaper into Chinese several months ago , it's time to merge it to upstream. 

Refer PR #492 , issue #394 

Platform whitepaper in Chinese https://lib.jimmysong.io/blog/cncf-platforms-white-paper/

**Comment by rootsongjc** [comment]
Glad to see that the website now supports internationalization. Should I submit my translation to this repository?

**Comment by node** [comment]
> Glad to see that the website now supports internationalization. Should I submit my translation to this repository?

Yes, just update this file https://github.com/cncf/tag-app-delivery/blob/main/website/content/zh/wgs/platforms/whitepaper/index.md
