### ISSUE TITLE
Threeport sandbox submission review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#512]
[threeport](https://threeport.io/) is a framework for delivering cloud-native applications proposed to [CNCF sandbox](https://github.com/cncf/sandbox/issues) in <https://github.com/cncf/sandbox/issues/69>. This issue tracks discussions and reviews of threeport to help with accepting it in CNCF sandbox.

We've asked @lander2k2 and team to join an upcoming TAG meeting, perhaps on 12/20, to discuss the following about the project. @lander2k2, please plan to present the following info in about 25 minutes, followed by 5 minutes of questions and answers from TAG members. Thank you!

- the values this project proposes to end users
- the project's high-level technical architecture
- a brief demo of experiences and UIs
- the project's near-term roadmap
- state of the project's community and governance
- comparison with existing projects

**Comment by lander2k2** [comment]
Thanks @joshgav.  I'll have a presentation ready for Dec 20.  Apologies for the silly question, but where can I find that call's details so I can add it to my calendar?

**Comment by joshgav** [comment]
Hi @lander2k2 and thanks, looking forward!

TAG meetings are on [the CNCF calendar](https://www.cncf.io/calendar/) and you can copy from there, but if you want an easy way to get a personal invite you can RSVP to individual events via the community site at <https://community.cncf.io/tag-app-delivery/>.

Specifically, here's the page for the 12/20 meeting: https://community.cncf.io/events/details/cncf-tag-app-delivery-presents-tag-app-delivery-general-meeting-2023-12-20/

**Comment by lander2k2** [comment]
Thanks again to everyone that took the time to see my presentation for Threeport.

Here is a link to the slide deck I used if anyone would like to re-visit it: https://docs.google.com/presentation/d/1j0tB9E6BtQ_bI1KPLOlX0QZY-w6P0xFjYrtswq5WX1E/edit?usp=sharing

And here is the Threeport homepage where you can find links to our docs, github repo, etc: https://threeport.io/

**Comment by thschue** [comment]
Presentation is done and currently no open action items. Therefore closing this ticket.

@lander2k2 : Please feel free to come back to us if you need our support!
