### ISSUE TITLE
Apicurio Registry sandbox submission review

### ISSUE THREAD

**Issue by angellk** [cncf/tag-app-delivery#517]
Apicurio Registry is a runtime server system that stores a specific set of artifacts (primarily schemas and API designs) as files and manages evolution of artifact versions. It was proposed to [CNCF sandbox](https://github.com/cncf/sandbox/issues) in [https://github.com/cncf/sandbox/issues/72](https://github.com/cncf/sandbox/issues/72). This issue tracks discussions and reviews of Apicurio Registry to help with accepting it in CNCF sandbox.

We've asked @carlesarnal and team to join the December 20 TAG meeting to discuss the following about the project.

Please plan to present for about 20 minutes, followed by 5-10 minutes of questions and answers from TAG members.

- the values this project proposes to end users
- the project's high-level technical architecture
- a brief demo of experiences and UIs
- the project's near-term roadmap
- state of the project's community and governance
- comparison with existing projects

**Comment by joshgav** [comment]
The upstream issue in github.com/cncf/sandbox has been closed for now so we'll close our tracking issue as well.
