### ISSUE TITLE
ConnectRPC sandbox submission review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#520]
[Connect](https://connectrpc.com/) is a framework to quickly enable service-to-service communication using Protocol Buffers and other formats like JSON. It was proposed to [CNCF sandbox](https://github.com/cncf/sandbox/issues) in [https://github.com/cncf/sandbox/issues/63](https://github.com/cncf/sandbox/issues/63). This issue tracks discussions and reviews of Connect to help with accepting it in CNCF sandbox.

We've asked @akshayjshah and team to join the January 17 TAG meeting to discuss the following about the project.

Please plan to present for about 20 minutes, followed by 5-10 minutes of questions and answers from TAG members.

- the values this project proposes to end users
- the project's high-level technical architecture
- a brief demo of experiences and UIs
- the project's near-term roadmap
- state of the project's community and governance
- comparison with existing projects

**Comment by akshayjshah** [comment]
Thanks for the opportunity to present to TAG App Delivery! I've uploaded the [Markdown for my slides][slides], and I believe the meeting was also recorded.

[slides]: https://github.com/cncf/tag-app-delivery/files/13966256/2024-01-17-cncf-connect.md

**Comment by angellk** [comment]
Recommendation:
- have TAG Network review RPC's place in CNCF
- ConnectRPC to present/demo to TAG Network
- TAG Network work with Connect for rest of Sandbox application
