### ISSUE TITLE
Hugo styling for taxonomy on blog

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#522]
As a part of #518 we have introduced a light weight categorisation and tagging strategy. This is in preparation for a hopeful increase in content generation and posting. By adding the taxonomy we will be able to better display relevant content to readers and also call out what is "official TAG" writing and what is "community contribution". The definition of what this means will need to get more detailed over time and can be added to the `contributions` page.

This issue tracks the visual changes that @cjyabraham has kindly offered to work on after the holidays!

**Comment by cjyabraham** [comment]
I've submitted [a PR](https://github.com/cncf/tag-app-delivery/pull/526) with some thoughts for this for your feedback.

**Comment by abangser** [comment]
Merged this PR yesterday, thanks again for the great work!
