### ISSUE TITLE
API Design Review WG / proposal

### ISSUE THREAD

**Issue by toumorokoshi** [cncf/tag-app-delivery#531]
This is a tracking issue to discuss the possibility of a working group (or whatever construct) around API Design Review for CNCF projects.

For context: there is a group of API design leads from various organizations today (Roblox, IBM, Microsoft, Netflix, and some ex-Googlers) who meet in a regular meeting around API Enhancement Proposals (https://aep.dev/). We've previously applied to be a CNCF project or working group (see #448).

We're looking at ways to contribute to the CNCF ecosystem, and one such way is to help review new APIs that are being introduced by CNCF projects. Long-term we'd like to develop a unified specification around remote APIs, but short-term we could use our time to review new APIs being introduced, help drive them toward uniform best practices, and use that to refine our own specification in progress.

Perhaps there's time to discuss this at the next tag meeting (2/21?)

Relevant slack threads:

- https://cloud-native.slack.com/archives/CL3SL0CP5/p1704905973103559
- https://cloud-native.slack.com/archives/CL3SL0CP5/p1704914379664109

**Comment by toumorokoshi** [comment]
@angellk actually sorry about this but I have a vacation planned on 02/21, so it'll be difficult for me to speak to it. Would it be possible to bump this topic up to 02/07 or after on 03/06?

**Comment by angellk** [comment]
@toumorokoshi we'll look for a different date!

**Comment by angellk** [comment]
@toumorokoshi Let's plan on 03/06

**Comment by toumorokoshi** [comment]
sounds good! we'll be there.

**Comment by joshgav** [comment]
Related: #448

**Comment by lianmakesthings** [comment]
Hi everyone, we've decided to move forward with an App Dev Working Group, in full awareness that this WG is somewhat out of scope for the App Delivery TAG.
We would like to see if we can keep interest consistently high to eventually create a TAG App Development. 
For now, we're asking you to join the App Dev WG (#wg-app-development on the CNCF Slack) and bring this up as a topic of discussion within that WG
