### ISSUE TITLE
Score sandbox submission review

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#539]
[Score](https://score.dev/) is a spec for describing infrastructure for workloads independently of its implementations. It was proposed to [CNCF sandbox](https://github.com/cncf/sandbox/issues) in [https://github.com/cncf/sandbox/issues/79](https://github.com/cncf/sandbox/issues/79). This issue tracks discussions and reviews of Score to help with accepting it in CNCF sandbox.

We've asked @sujaya-sys and team to join the January 23 WG Platforms meeting to discuss the following about the project.

Please plan to present for about 20 minutes, followed by 5-10 minutes of questions and answers from TAG members.

- the values this project proposes to end users
- the project's high-level technical architecture
- a brief demo of experiences and UIs
- the project's near-term roadmap
- state of the project's community and governance
- comparison with existing projects

**Comment by angellk** [comment]
[Notes from Presentation to Platforms WG (to be cleaned up)](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit)

**Comment by thschue** [comment]
The project has passed the Sandbox voting (https://github.com/cncf/sandbox/issues/79). Therefore, we'll close this issue.
