### ISSUE TITLE
[Community] Platforms of Platforms and methods of defining interaction layers between software products/platforms

### ISSUE THREAD

**Issue by krumware** [cncf/tag-app-delivery#542]
### Contribution Description

Applications and Platforms and Application Platforms, and the many variations, create confusion in the devex and management of cloud environments. If I am tasked with deploying an application that calls itself a Data Platform into my Kubernetes Platform, where does the platform end and the platform begin?

One of the primary benefits of cloud-native is the ability to share resources between components. This is also a common hurdle of understanding for cloud-native newbies. The ability to deploy multiple logically separate applications/platforms and have them share resources can be a huge benefit.  Actually making this happen is a whole other challenge that is not often made easy by project maintainers/vendors.

How do I define my application/platform's ability to interoperate and share resources, within the context of the component model in the Platforms Whitepaper? If I am going to deploy a vendor's platform into my platform, how can/will it interact with my other applications/platforms? How do I communicate whether or not it needs it's own tenant or standalone components?

I have both worked with project maintainers to help their applications/platforms become more deployable and adoptable, as well as the consumers who are managing their own platforms, and have faced these challenges from both sides. I would like to share our lessons learned and some recommendations on ways to communicate patterns and documentation methods (templates/artifacts) to help make software more adoptable and manageable.

### Related Working Group (WG)

Platforms

### Contribution type

Blog (Default)

### Why TAG App Delivery?

This targets the bridge between App Delivery and Platforms.

### Related projects/technologies

Platforms Whitepaper
Platforms Maturity Model
Platforms as a Product Whitepaper
{would like to target a CNCF project as an example}

### Affiliation disclosure

n/a

### Additional collaborators

@jawadqur

**Comment by abangser** [comment]
This sounds fantastic @krumware! The content sounds relevant to the TAG and specifically an add-on to the WG white paper work.

You mention you are going to use CNCF projects as an example which is great, but just want to call out the overall goal of the CNCF WGs to discuss patterns over "king making" so maybe have a think about how you can both provide an example while also acknowledging the "category" of tool that may be interchangeable.

Aside from that small nit, I would say this sounds well placed for a blog post. In general we aim for blog posts to be author led and while a TAG lead will need to verify the content meets our [guidelines](https://tag-app-delivery.cncf.io/contribute/community-post-guidelines/) and other community reviews are available more for support than as a blocker.

Is there anything further we can do to support you at this stage? If not, you are encouraged to create a draft, either using google docs if you expect a high level of collaboration/feedback or directly as a PR if you prefer to keep feedback more focused on "approval".

**Comment by krumware** [comment]
I'm definitely following. There wouldn't be an aspect of kingmaking, since there isn't a product to promote there, just examples of combining software applications which leverage (share) instances of platform capabilities to operate efficiently. I'll be working on the scaffold and will share. Thank you!

**Comment by joshgav** [comment]
Thank you @krumware. I've also been hearing about platforms on platforms, and am very interested in hearing how capabilities and platforms could become more composable and interoperable. Also heard from a couple folks just today how there is usually more than one "platform" team needed at an enterprise. Looking forward to reading your work!

**Comment by krumware** [comment]
Thanks again @joshgav and @abangser. I'm also sorry I've been pulled away from the past couple of meetings, duty calls! I'm working on a better strawman and would enjoy finding a team to hop on a call with you guys soon outside of the normal meeting times (which are difficult to make it to)

**Comment by earth2marsh** [comment]
I'm also interested in this topic as I have spent a long time in the API platform space. Explaining how different platforms intersect is quite interesting to me--happy to support this in ideation, reviewing, editing, etc.

**Comment by bryanrossUK** [comment]
I'm interested in this ... "platforms" is such an overloaded term and much of my work with customers is assessing what their definition might be.  In my mind, this is all about layers of abstraction - e.g. a storage platform takes advantage of disk; a cloud platform uses storage platforms; an IDP will hopefully consume many platforms to create an end-to-end experience for developers.

There are some really important general things though about platforms - the concept of a 'customer', etc.  I'd be happy to help contribute to this.

**Comment by giulioroggero** [comment]
I'm interested in this topic and I see a good relation with this issue https://github.com/cncf/tag-app-delivery/issues/586

**Comment by giulioroggero** [comment]
I have added a representation about Platform of Platforms. I don't known how to proceed. Better to cross link the issue https://github.com/cncf/tag-app-delivery/issues/586#issuecomment-2074591349 or move the conversation in this issue?

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. I also believe this may be superseded by the work in #586 and associated blog post. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic.

Thanks!

**Comment by krumware** [comment]
I still believe there's more to expand on here, but will archive for now.

**Comment by jinnjwu** [comment]
I am very intesting on it. Actually, I implmeneted same concept in my company for 3 years, platform name is POP,which means platforms of paltforms, super amzing name is same too.

**Comment by attekei** [comment]
I'd be very curious of any industry learnings of the topic. I'm in process of trying to establish patterns for Internal Platform <-> Internal Platform interaction and am struggling a bit.
