### ISSUE TITLE
Recruiting & Insights at Kubecon EU 2024

### ISSUE THREAD

**Issue by mluskind** [cncf/tag-app-delivery#553]
### Motivation

- We have an opportunity to reach our target audience at the conference.
- We need to have a concise pitch to clearly explain the nature of this work and sign-up participants to be interviewed. 
- We can to evangalize for the project by sharing some early insights from the conference 

### Considerations
- Who’s going to be doing the recruiting at the conference? 
- Should we do onsite interviews or recruit them for later remote interviews?
- Do we adapt our set of requirements for interviewees in this special event? (ie. ask a broader group of platform people).
- Do we cherry-pick a handful of questions that are more broadly applicable in order to get meaningful insights that we can publicize to market the overall project? (what are the most compelling questions around product thinking/"approach" to platform work)

### Outcomes
- We have a clear plan for recruiting at KubeCon EU 2024.
- Insights that can be published in blog form

**Comment by techmaharaj** [comment]
As for interviewing them, we could have a Google form to pre-book a slot based on the interviewer's availability. So that way some of us evangelise by sharing the form online before the event so by the time we're at KubeCon there's some interest. And internally we can match interviewees with interviewers.

**Comment by olivercodes** [comment]
`Should we do onsite interviews or recruit them for later remote interviews?`

If we can get a dedicated space for doing them onsite, I think that would be best. The general buzz and excitement of the event will drive engagement and topics like Platform and K8s will be at the top of mind of our interviewees making for better conversations.

**Comment by abangser** [comment]
Tagging in @lianmakesthings who I think is still waiting to hear about the booth?

**Comment by abangser** [comment]
Seems you connected and a booth here: 

https://github.com/cncf/tag-app-delivery/issues/498#issuecomment-1942363657

Not sure where the right place for chat is but wanted the visibility for others!

**Comment by lianmakesthings** [comment]
TAG booth is reserved for the platforms WG Thursday 12:30 - 13:30 for now.

**Comment by Rotfuks** [comment]
Heya folks! KubeCon is coming closer. Do we maybe want to setup a meeting next week to discuss options and create a plan?   
Maybe as preparation we can at least comment some options in here?

Some options we already talked about: 

*   create short survey for interview recruiting 
*   create short survey to get minimal set of quantitative data we could use for a blog post
*   just be on the booth and talk to people, nothing to plan on top :) 

Any more ideas?

**Comment by techmaharaj** [comment]
We should do a short survey maybe with a few basic quantitative questions.  

And we could also just interact with people on the booth and have a form for them to fill and show their interest in being interviewed along doth filling this survey. One single form to take both these details. 

That way post Kubecon we have a list of people who to interview so we can consistently drive interviews and have a healthy content pipeline later. 

But open to ideas.

**Comment by dstengle** [comment]
I was thinking along the same lines, although I had thought to have it just be for the team at the booth to record. We could certainly just have it public:
- Name

**Comment by dstengle** [comment]
I will create a form to have a look at in the meeting tomorrow. We can print up some QR codes for it.

Otherwise, how to we publicize our presence there? Maybe we could have something on display during platform day, possibly on-screen between talks?

**Comment by abangser** [comment]
Hi all! I am curious how this issue is progressing? I know the form led to a lot of fantastic sign ups at Paris, so is this issue complete? Or are there actions we want to take before closing this issue? Thanks! Maybe @dstengle you have some ideas?
