### ISSUE TITLE
App Enablement Tooling img does not show in */wgs/platforms/charter.

### ISSUE THREAD

**Issue by Eeap** [cncf/tag-app-delivery#555]
<img width="787" alt="image" src="https://github.com/cncf/tag-app-delivery/assets/42088290/1fa9c116-832d-4d65-9f10-aabd3cd2a07a">

Above the image, the image url is wrong so can't get image from file. 
I think the image(`/platforms-wg/charter/img/charter_app_enablement.png`) was not copied to each content language dir. So I will add each content dir that image. :)

**Comment by joshgav** [comment]
Thank you for the issue and fix @Eeap !
