### ISSUE TITLE
[Kubecon EU 2024] Platform WG - Morning meetup / Coffee

### ISSUE THREAD

**Issue by antoine-sncf** [cncf/tag-app-delivery#557]
We've been working with  @abangser so that we can have a small place at the  to meet and share a coffee before "the big day". It's near the kubecon's venue  (5 minutes)
Meet us starting tuesday 19/03 from 07h15 to 8h45 (at https://www.lebelluneparis.com/ 35 Boulevard Victor 75015 Paris )
https://framadate.org/mi8N2yFdWTzbMO7u 
Let us know (with the poll link ) if you're going to join us (so that i know if i need to book more).
The location will be reused the other days if people are still available.

I'm in touch with the bellune to book a small place near the bar. I'll preorder a thermos of coffee, a few pastries /cake and an orange juice. If you want more i believe that you'll be able to order at the bar a few extra things (but if you want a complete breakfast you should probably get one at your hotel).
Estimated : 10 people (up to 20 possibly ?).

I've also requested if we can use the bar the other days of the wek as a few people would like to reuse the place.

We'll share the bill but it looks like that we'll be able to get some sponsors 

Discussions on slack: https://cloud-native.slack.com/archives/C020RHD43BP/p1706099927099729

**Comment by abangser** [comment]
Translated quote from the venue via @antoine-sncf :
_For breakfast on March 19, we can provide you with three pastries per person (30), 2 thermoses of coffee and 2 carafes of orange juice.
For this it would cost 10 euros per person.
Indeed, if you wish to add items, you can ask the server and pay this supplement on site.
For people who wish to return on other days, if there are many of them, you should notify me in advance so that I can organize their arrivals and also apply the group rate (10 euros).
If people are alone, the price of our express breakfast at the bar is 12 euros per person including:
1 DETOX JUICE
Orange, carrot, lemon, ginger, acerola
1 homemade fruit salad
1 granola with cottage cheese
A CHOICE :
Honey, agave syrup, maple syrup
OR
1 hot drink, 1 fruit juice, 3 pastries_


I think we can assume no more than 20 people so that is ~200eur per day. So far we have the following people happy to sponsor: @loujaybee from GitPod,

**Comment by Sheepux** [comment]
After seeing the poll results, I have confirmed at the belune the option for 3 days : tue/wed/thu (the friday seems uncertain) for 10 persons minimum. I'll confirm the actual numbers again 1 week before the event (12/03)  up to 20.

I've personnaly guaranteed the paiement in case there is a paiement card issue onsite (we'll find a way later).

**Comment by antoine-sncf** [comment]
After seeing the poll results, I have confirmed at the belune the option for 3 days : tue/wed/thu (the friday seems uncertain) for 10 persons minimum. I'll confirm the actual numbers again 1 week before the event (12/03) up to 20.

I've personnaly guaranteed the paiement in case there is a paiement card issue onsite (we'll find a way later).

**Comment by olivercodes** [comment]
@antoine-sncf - just to clarify, are you saying we're doing all 3 mornings? Or just the Tuesday

**Comment by Sheepux** [comment]
All 3.
The first version of the poll was just "are you coming on tuesday" but Abby was thinking that somple might want to meet more than once.

**Comment by antoine-sncf** [comment]
All 3.
The first version of the poll was just "are you coming on tuesday" but Abby was thinking that somple might want to meet more than once.

**Comment by RinkiyaKeDad** [comment]
I would love to join as well! Is there somewhere we have to register? Or just show up at the venue?

**Comment by antoine-sncf** [comment]
If you voted at the poll on top that's enougth

**Comment by abangser** [comment]
To make sure we have complete details here as well as the slack thread:

We will ideally have people register via https://framadate.org/mi8N2yFdWTzbMO7u, however, *anyone is very welcome to arrive on the day if they didn't have time to register or were not aware. 

Full context:

Registration is really only useful up to 1 week before KubeCon as it will influence the amount of pastries / coffee that we want to preorder. 

It was decided in slack that the numbers are not "orders" for food/drink, but more for planning. So we will be first come first serve for refreshments and encourage anyone to come that is able!

**Comment by antoine-sncf** [comment]
I'll confirm the numbber of people tomorrow to the Bellune.
I see that we have https://framadate.org/mi8N2yFdWTzbMO7u
16 for tuesday
13 for wednesday
14 for thurrsday
I Will confirm "for estimated 20" on tuesday and "for estimated 15" the 2 other days

**Comment by abangser** [comment]
This was a HUGE success. Thank you again to @antoine-sncf for all the hard work planning this and to the sponsors: GitPod, Krumware and Syntasso (Kratix.io).

We had ~20 people every day (even Friday!) and had some great chats. If anyone would like to write up a summery blog that would be amazing, but I will let that come in as a separate PR / Issue.

We should look to set these up for each KubeCon given the success of this one 💪 

Here are some of my posts which capture the key pictures from the event:
https://www.linkedin.com/posts/abbybangser_day-4-of-cncf-tag-app-delivery-delivery-morning-activity-7176884098559291393-Fpe6
https://www.linkedin.com/posts/syntasso_kubecon-platformengineering-activity-7176497868180979712-kLjY
