### ISSUE TITLE
[Platforms] translate WG's glossary to Chinese (zh)

### ISSUE THREAD

**Issue by earth2marsh** [cncf/tag-app-delivery#559]
### New language

First translation (default)

### Language code to be used

zh

**Comment by earth2marsh** [comment]
This issue tracks the i18n from English into Chinese (zh) for the Platforms WG's glossary.

See the updates (v2) in https://github.com/cncf/tag-app-delivery/pull/545, with background in issue https://github.com/cncf/tag-app-delivery/issues/485.

Note that v1 does exist as a fully translated document that may be referenced; however the changes are significant enough to suggest a new translation.

**Comment by node** [comment]
Assign to me  ,thx 😄

**Comment by node** [comment]
Finished 🆗 
To be reviewed.

**Comment by abangser** [comment]
Thanks for all the hard work @node! I can see we are getting language reviews in the PR and will follow along there.

**Comment by abangser** [comment]
Very glad to have this merged in. Will close this issue to keep this tidy 🙌
