### ISSUE TITLE
Nominate and elect Colin Griffin as co-chair of WG Platforms

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#564]
**Background**: WG Platforms was formed in late 2021 to identify and strengthen patterns in the cloud computing industry for facilitating cooperative practices for delivery of infrastructure and applications. In 2022 we identified _platforms_ and _platform engineering_ as ideal trends to build on to achieve these goals, as described in <https://tag-app-delivery.cncf.io/blog/infrastructure-for-apps-platforms-for-cooperative-delivery/>, and accordingly we've spent the past 18 months developing a white paper, maturity model and small community to enable enterprises and end users to cooperatively deliver applications and infrastructure by understanding and implementing platform-centric models.

**Impact**: In addition to the impact on our industry, this work has led to more interest in and contributions to the WG, such as [issues tracked in GitHub](https://github.com/cncf/tag-app-delivery/issues?q=is%3Aissue+is%3Aopen+label%3Awg-platforms). discussions in [our Slack channel](https://cloud-native.slack.com/archives/C020RHD43BP), and a growing presence at Kubecon and other industry and community events.

**Request**: With this in mind the working group proposes to add another chair to help in handling this growing work and supporting the industry. Current WG leaders @joshgav, @abangser and @roberthstrand have nominated @krumware (Colin Griffin) for this role in recognition of his contributions these past 18 months, his interaction with others in our channels, and his proposals for future industry and community work. @krumware please feel free to share further qualifications of yours in a comment on this issue! We've checked with Colin and he has graciously accepted the nomination; and have also asked TAG App Delivery's leaders for initial approval of his election.

**Action requested**: So this issue is to make Colin's nomination official and **ask TAG App Delivery's leaders** (@AloisReitbauer, @thschue, @joshgav, @lianmakesthings, @angellk) **to approve it**. Please add a :+1: to this post or comment with a +1 to indicate your support. We'll finalize Colin's election with a PR adding him to relevant groups and listings.

Thanks for your support!

**Comment by abangser** [comment]
I can add a strong vote of confidence for the work that Colin has done and continues to do within both the WG and the wider CNCF including liaisoning with the CNCF Cloud Native Maturity Model, FINOS community and more. 

He will be a huge asset to the team given even more focus and opportunity to support others.

**Comment by menzenski** [comment]
+1, Collin does a lot for the WG Platforms community and I think he'll be an excellent co-chair.

**Comment by chase-weiser88** [comment]
I've worked closely with Krumware over the past few years and I cannot say enough about how great the experience has been. Colin will be an invaluable asset for WG platforms.

**Comment by abangser** [comment]
As suspected, Colin seems to have had overwhelming support! 🎉🙌

Given this I'd love to get this actioned before KubeCon so that Colin isn't in limbo land in Paris. 

What is left to do? Maybe a PR for adding his name to the site? 🤔

**Comment by angellk** [comment]
If there are 4 chairs, it would help to have one step down so we can have an odd number of chairs for decision ratification. Is there a chair that is ready to rotate out? Cc: @abangser @joshgav @roberthstrand

**Comment by abangser** [comment]
Agreed @angellk and we do have a rotation plan in place but I think the goal is to execute in a few more months. If it's OK to stay at 4 for a short time that would be ideal.

Another side note, the value of merging this asap is that @krumware is representing the WG on stage at Platform Engineering Day and I'd love to have him be able to be out of the current limbo state. 

All that said, I realise the value of split decisions, but I think at WG level that is less impactful and we've been more pressed for enough support for the ongoing projects. But of course understand if you want to maintain the odd number and we can organise if necessary.

**Comment by angellk** [comment]
Sounds good @abangser ! We can merge and then discuss timelines/plan in the leads meeting this next week.

**Comment by abangser** [comment]
That's great, thanks for understanding @angellk !
