### ISSUE TITLE
Clean-up Tasks for Merging WG GitOps with OpenGitOps Project

### ISSUE THREAD

**Issue by angellk** [cncf/tag-app-delivery#579]
GitOps Working Group Leads to work with OpenGitOps project maintainers to:

[ ] update the WG meeting documents, and any other outstanding items, to point to open gitops
[ ] make a decision on the #wg-gitops slack channel (e.g. point to opengitops or vice versa and rename)
[ ] update the OpenGitOps [project home page](https://github.com/open-gitops) with current information/status
[ ] schedule a time to present to TAG App Delivery in a general meeting in May/June with an update on OpenGitOps project status

**Comment by angellk** [comment]
@scottrigby can we close this out? have all items been completed?

**Comment by thschue** [comment]
imho the wg cleaned up the repo and progresses further as OpenGitOps project. Therefore, this issue will be closed.
