### ISSUE TITLE
Establishing an Application Development Working Group

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#588]
Throughout the last year, we have seen an increasing need for a home for Cloud Native Application Development-related projects and topics. To make a start, the TAG Leadership decided to spin up a working group to deal with this topic with the ultimate goal of making this a TAG in the long term (as discussed with @Riaankl).

APIs (https://github.com/cncf/tag-app-delivery/issues/531), SDKs, and development frameworks for cloud-native applications are examples of topics that would be in scope for this Working Group.

Therefore, we defined the following Action Items:

```[tasklist]
- [x] Finding interested people who want to drive the establishment process
- [x] Work on a charter and the scope of the working group
- [x] Make the working group operational and start working
- [x] Submit Charter / README and Leadership to TOC Liasons for formal approval (https://github.com/cncf/toc/issues/1311)
- [x] add WG to website
- [ ] https://github.com/cncf/tag-app-delivery/issues/627
- [x] add meeting to CNCF calendar
```
Initially, the TAG Leadership will drive the process together with @salaboy.

The current version of the charter can be found here: https://docs.google.com/document/d/1QrMlQGg9etKghHkVoQxCB8wUzvq_8Wvq3NEwR1eU2bw/edit?usp=sharing. 

We kindly ask the community to express their interest and also help us defining the scope of the WG.
To contribute, please join us on the CNCF Slack #wg-app-development

**Comment by salaboy** [comment]
I am happy to drive and bring people together around this topic to create a charter. 
I am sure that @ThomasVitale is happy to join too.

**Comment by pasimoes** [comment]
@thschue great initiative... @salaboy I will be very happy to join and help.

**Comment by ThomasVitale** [comment]
@salaboy I would be happy to join and contribute to this working group. Exciting!

**Comment by angellk** [comment]
This is exciting and a long time coming.

**Comment by aliok** [comment]
I would be happy to contribute and to help driving this initiative!

Great initiative!

**Comment by Titof974** [comment]
Hello, I would like to contribute too !

**Comment by menzenski** [comment]
I'm very interested in this, I would love to contribute in any way I can. This is an area near and dear to me.

**Comment by grudra7714** [comment]
I would like to contribute as well!

**Comment by toumorokoshi** [comment]
Hi there! I'd like to contribute as well: definitely interested in the API aspect described.

**Comment by redeux** [comment]
I'm interested in helping with the WG in whatever capacity is useful.

**Comment by LBMKRISHNA** [comment]
From this A / NZ region, I am happy to be part of this and contribute

**Comment by gianlucam76** [comment]
I would love to participate and contribute as well. Thank you.

**Comment by 0xE282B0** [comment]
I really appreciate this initiative and would like to offer my support!

**Comment by hhiroshell** [comment]
I am very interested in this as well and would like to contribute in any way possible!

**Comment by hibri** [comment]
I'd love to contribute :). Count me in

**Comment by professorisidro** [comment]
I'd like to contribute with this amazing initiative. Count me in!!

**Comment by dol** [comment]
I'm enthusiastic about joining this new working group and contributing my skills and insights.

**Comment by marcosnils** [comment]
Hey there! Would love to participate as well

**Comment by kdubois** [comment]
This is a GREAT initiative!  I'd be delighted to participate if you have room for one more :)

**Comment by Riaankl** [comment]
It was great to talk to the TAG App delivery folks at Kubecon. Thank you for driving this initiative.
I have created two files that would be the starting point for this initiative. 
Please collaborate in these files to create a [README](https://docs.google.com/document/d/1xVxAQPTGI6a_zx7skrVrJyzTG57WhI3gavGm7cHg62g/edit) and [Charter](https://docs.google.com/document/d/1N_47QytSqi8-PW4wjnLBN5EDEArC_YDT5QgfN-r7nSY/edit) for the Working Group. 
For the moment anyone with a link to the file can edit it. Please use comments and suggestion to collaborate on the docuements.

Please contact me on Slack if you need assistance setting up a kick-off meeting.

**Comment by salaboy** [comment]
Thank you all for commenting out here.. I will work a bit on the files created by @Riaankl , if you want to add comments or use suggestion mode that will be great.

**Comment by Titof974** [comment]
I added goals and non goals, not sure if they are consistent enough. The subject is very broad!

**Comment by salaboy** [comment]
@Titof974 please use suggestion mode.. if not it gets really hard for me to review and understand changes

**Comment by danieloh30** [comment]
Great idea! 100% agree with the necessity since I got the same feedback and requests from many community app developers and architects at KubeCon and open source conferences in the past.

**Comment by ealeyner** [comment]
Would love to be of value to the group!

**Comment by rynowak** [comment]
I'd love to participate in this!

**Comment by akankshakumari393** [comment]
Great initiative!! I would love to contribute here

**Comment by Riaankl** [comment]
/cc @kgamanji @linsun

As TOC Liaisons

**Comment by graz-dev** [comment]
I would like to join the working group if you have a room for one more!

**Comment by lianmakesthings** [comment]
Hi everyone,
fantastic to see so many folks interested in this ❤️ 

To contribute, please join us on the CNCF Slack #wg-app-development

**Comment by lianmakesthings** [comment]
The new charter and README template: https://docs.google.com/document/d/1ut60KmkIwggpnF0Wtb8-qoECnB9W0qq8nihqKxYQ_a0/edit

**Comment by salaboy** [comment]
Folks, the nomination process for chairs of the group is open: https://github.com/cncf/tag-app-delivery/issues/627 

Can you folks please nominate someone, self-nominate, or vote for the current nominees (with some thumbs up)?

**Comment by thschue** [comment]
As the WG is now established, this issue will be closed.

Thanks to everyone for making this happen and looking forward to the work of the WG.
