### ISSUE TITLE
Platform Maturity Model website defaulting to Spanish

### ISSUE THREAD

**Issue by krumware** [cncf/tag-app-delivery#600]
It looks like the Platform Maturity Model website is now defaulting to Spanish language. Tested on multiple devices and incognito mode. This may be related to the recent Spanish translation additions in #594 

Visiting https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/ will likely show menu items in Spanish. This doesn't look to affect the Whitepaper or overhead TAG site.

**Comment by guillermotti** [comment]
Hey @krumware, my apologies on this as I copied some symlinks from the English folder with website content into the Spanish folder. 

This should be solved in https://github.com/cncf/tag-app-delivery/pull/599.

The above PR should also translate the `Glossary` into Spanish. I tried locally and everything looks fine now. Double check locally if possible just in case 🙏🏽

**Comment by krumware** [comment]
Tested and working. Thank you for the diligence!
