### ISSUE TITLE
Stepping down as TAG App Delivery Co-Chair

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/tag-app-delivery#609]
I am stepping down as the Co-Chair of TAG App Delivery. I have seen the TAG - back then SIG - grow from it's inception and through ups and downs (and a pandemic).

I am glad to see that people with a lot of drive and enthusiasm have joined the TAG and want to give them to step in their responsibility.  I have also seen that due to other commitments I do no longer find the time to properly support the evolution of the TAG on an organisational level. 

I will still support the process of finding a new TAG Co-Chair and help transition over the leadership.

**Comment by thschue** [comment]
Thank you @AloisReitbauer, for your dedication and your work for the TAG!

**Comment by angellk** [comment]
Thank you for everything @AloisReitbauer - your insights and expertise are incredibly valuable. Very much hope you continue to stay involved.

**Comment by lianmakesthings** [comment]
Thank you for your work and guidance on the TAG, @AloisReitbauer

**Comment by abangser** [comment]
I will echo what the others have said @AloisReitbauer, you have been a welcoming face for me joining this TAG and an absolute legend at joining dots across the CNCF for support. 

Thanks for everything and looking forward to continued collaboration in different roles.

**Comment by roberthstrand** [comment]
Thank you for all the hard work, @AloisReitbauer!

**Comment by angellk** [comment]
Want to make sure it is captured here that @AloisReitbauer stepped down as TAG App Delivery Co-Chair, however, is moving to TAG App Delivery Co-Tech Lead.

**Comment by roberthstrand** [comment]
I'm closing this issue, as it has been open for a while. Again, thank you so much for everything, and I am happy to see that you will continue to help out when time allows.
