### ISSUE TITLE
Proposing Lian Li as new Co-Chair of the TAG App Delivery

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#610]
Hello!

As @AloisReitbauer[ steps down as co-chair](https://github.com/cncf/tag-app-delivery/issues/609), I propose @lianmakesthings as a new co-chair for the TAG App Delivery.

Lian has been serving as a Tech Lead for the last half year. She drives many initiatives, chops wood, and carries water for the TAG a lot. She is very active in TAG meetings, and her drive and dedication make her instrumental for the TAG.

**Bio**
Lian always wanted to save the world

After dropping out of law school, she decided to work with computers instead. While in Web Dev, she started attending and speaking at tech events, and soon fell in love with the tech community. In her roles as Developer, Consultant and Developer Advocate, Lian combined technical knowledge with an understanding of the human condition.

Currently, Lian lives in Amsterdam, where she serves as Tech Lead for the CNCF TAG app-delivery. She can also be seen on stage at various English-speaking musical theatre productions, doing standup comedy and improv theatre.

**Action requested:** This issue is to ask TAG App Delivery's leaders, TOC Liaisons, and WG Leads (@kgamanji, @joshgav, @angellk, @roberthstrand, @abangser, @sabre1041, @krumware, @rchincha) for their support in nominating her as a Co-Chair. Please add a +1 to indicate your support. After the majority has agreed, I will forward the proposal to the TOC.

**Comment by lianmakesthings** [comment]
Thank you, @thschue. Love working with this amazing and dedicated community and excited to make it even better ❤️

**Comment by abangser** [comment]
Absolute plus 1 from me!

Lian has been taking on more and more actions recently and been a really great support to me as a WG lead. Looking forward to even more collaboration in the new role!

**Comment by krumware** [comment]
I thought Lian was already a co-chair! 🤯. Obvious support from me!

**Comment by roberthstrand** [comment]
Huge +1 from me, that makes a lot of sense 👍

**Comment by angellk** [comment]
+1 @lianmakesthings has been a consistent contributor and leader in the TAG. Looking forward to seeing it made official.

**Comment by kgamanji** [comment]
+1 binding

**Comment by Riaankl** [comment]
The proposal has pass with a majority vote in favor of the nomination and no objections have been raised.

Congratulations to Lian Li as a new co-chair of TAG App Delivery.

 

Please summit a pull request update the records.

**Comment by lianmakesthings** [comment]
@angellk already started on a PR https://github.com/cncf/tag-app-delivery/pull/624 🙏

**Comment by lianmakesthings** [comment]
additional PRs opened against cncf/toc and cncf/people
https://github.com/cncf/toc/pull/1305
https://github.com/cncf/people/pull/412
