### ISSUE TITLE
[Community] Encourage blogs surrounding product thinking in regards to platforms

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#616]
### Contribution Description

There is a hypothesis that "platform as a product" may benefit from some baseline discussions around product thinking in general.

This will track one or more blog that we see our community start to put out around their experiences in this area.

### Related Working Group (WG)

Platforms

### Contribution type

Blog (Default)

### Why TAG App Delivery?

We want to encourage more community discussion which requires lowering the barrier of entry for both understanding what we are working on (product thinking in my situation) and being a contributor (writing blogs vs full blown white papers in this situation)

### Related projects/technologies

Platform-as-a-Product research in the WG

### Affiliation disclosure

This is encouraging multiple blogs, each author will need to complete this accordingly.

### Additional collaborators

David, Michael, Dominik, Atul, Budha

**Comment by Rotfuks** [comment]
Thanks for opening this issue @abangser!

The first outline we worked on for a blog article is about "Why Talking to Users Matters" - Identifying users, talking to users, focusing on problems instead on solutions and why you should care about all that.

**Comment by earth2marsh** [comment]
I'm interested in the topic, too, and I am happy to help!

**Comment by bryanrossUK** [comment]
I've written a [few](https://platformengineering.org/blog/platforms-as-a-superpower) [blogs](https://newsletter.bryanross.me/p/transformation-without-belief-is) on this topic, and I would love to help on this.

**Comment by abangser** [comment]
Glad to hear there is excitement here! I think the goal behind blogs is that they are lower barriers to entry for content and for authors. And that they don't require as many reviewers / soak time as something that is more formally published. Nor do they need to be fully unique as different ways of writing/perspectives can be welcome. With that in mind @Rotfuks @earth2marsh @bryanrossUK while you are welcome to collaborate, I would recommend also feeling free to write your own blog that you think brings value to the TAG readers!

**Comment by bryanrossUK** [comment]
Hey @abangser - will these be publish these on the [CNCF blog](https://www.cncf.io/blog/) or just via our own platforms?  If it's our own platforms, what's the best way to promote the CNCF WG in the blog post?  It would be good to be able to tie the post to the WG in some way, but I'm not sure what's required in terms of comms guidelines for the CNCF.

I've got outlines for two blog posts that I'll draft and share here this/next week.

**Comment by abangser** [comment]
Hi @bryanrossUK, great question and idea to be wider in our reach! So we only have full control over our own blog, so I think it is fair to say that posting there is our number one objective. That being said, raising the profile of this WG to the CNCF blog would be great and if we have some key points we want to share there we may be able to add them.

**Comment by dgem** [comment]
fyi, just posted a brief [Linkedin article on this topic](https://www.linkedin.com/posts/dgem_devops-productthinking-platformengineering-activity-7198616646746292224--IwD)

**Comment by abangser** [comment]
Thanks for sharing @dgem!

Would you like to see that on the TAG website? I think it has a bit of a social media vibe to it, but some really small updates to intro/outro would make it a good fit if you'd like!

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic (or create an associated blog post).

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
