### ISSUE TITLE
Website formatting around text wrapping

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#618]
Hi all, we got a report in a community slack about how the whitepaper was difficult to read due to word wrapping.

Specifically:
> I found it amusing (and harder to read) when there were 3 out of 5 lines with the last word hyphenated. I used DevTools to remove the hyphens: auto styling on the p element which then left the words whole and I found it much easier to read.

Before screenshot:
![image](https://github.com/cncf/tag-app-delivery/assets/1557346/62dad0d1-9495-4add-b691-9d0932406a09)

After screenshot:
![image](https://github.com/cncf/tag-app-delivery/assets/1557346/4930628d-dde2-447f-b595-1598fd52b484)

Is this something we have seen/heard elsewhere? @cjyabraham may have insights?

**Comment by cjyabraham** [comment]
We had regular paragraph text set to wrap words with hyphens. This isn't actually normal and I traced the style to something we inherited from another CNCF subsite. I've created [a PR to turn this off](https://github.com/cncf/tag-app-delivery/pull/619). 

Note, the site will still wrap words occasionally on links. We did this at one point to avoid urls that are links from pushing out the page width. If we find this is a problem I can turn it off too.
