### ISSUE TITLE
Announcing the Platform Engineering Maturity Model / Website Link not working

### ISSUE THREAD

**Issue by myfear** [cncf/tag-app-delivery#626]
The link to download via PDF works, the link to the website returns a 404.

`"Download now as a [PDF](https://github.com/cncf/tag-app-delivery/raw/main/platforms-maturity-model/v1/assets/platform-eng-maturity-model-v1.0.pdf) or view it on our [website](https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/)."`

**Comment by abangser** [comment]
Thank you so much for reporting this! We are aware and expect #625 to solve this.

**Comment by loujaybee** [comment]
+1 if we can fix this soon, as we are linking out to this in quite a few places—it'd be hard to find all those places to update.
