### ISSUE TITLE
Process to get approval for use of Platform Engineering WP / Capabilities Overview Picture 

### ISSUE THREAD

**Issue by myfear** [cncf/tag-app-delivery#630]
Hi,

I want to write a blog post and publish it on developers.redhat.com explaining the core traits of Cloud Native Platforms referencing the great work done by this TAG. 
The image https://www.cncf.io/wp-content/uploads/2023/04/pasted-image-0-2023-04-30T182736.471.png in the blog post https://www.cncf.io/blog/2023/04/11/announcing-a-white-paper-on-platforms-for-cloud-native-computing/ has no copyright attached and I am assuming full copyrights apply. 
I've reached out to trademarks at linuxfoundation via email. Wondering if there is a quicker way to get official approval when using it, given that I reference the source and the original work.

Thanks for a quick answer,
Markus

**Comment by abangser** [comment]
Hey @myfear, thanks for reaching out to ask about this! As far as I am aware, everything in this repository follows the [top level Apache 2 license](https://github.com/cncf/tag-app-delivery/blob/main/LICENSE) thereby making it absolutely fine to reference the image.

Please do report back if the team at the Linux Foundation comes back with any other recommendations which we can implement to make this more clear/easier to use.

**Comment by abangser** [comment]
I am going to close this for now as I think that this is covered, but if there are any additional issues please re-open here or a new issue. Thanks!
