### ISSUE TITLE
[Platforms] KubeCon EU 2024 Recap Blog Post

### ISSUE THREAD

**Issue by techmaharaj** [cncf/tag-app-delivery#632]
### Contribution Description

The idea was to recap everything that happened at KubeCon EU 2024 and make this post as the go-to post for all things platform engineering that happened at KubeCon. I've tried to cover all the aspects of the event.

Draft: https://docs.google.com/document/d/1_oc5Xy7gory3jUTku090K7JrjOaVlcQWHT4m3bc-rVc/edit?usp=sharing

Open to feedback, suggestions and comments. If there's anything that I've missed (_For eg: photos and updates from the TAG-App Delivery booth_) please suggest them in the document and I'll accept them. 

Thanks in advance :) 

_PS: I know this is delayed but I was traveling and then was caught up with work._

### Related Working Group (WG)

Platforms

### Contribution type

Blog (Default)

### Why TAG App Delivery?

Since the updates are closely related to the activities that we do as part of the Platforms Working Group, the blog post fits well here.

**Comment by akelity** [comment]
LGTM :)

**Comment by abangser** [comment]
This is great @techmaharaj , thanks for taking a stab at this! I can see a lot of great work happening on the google doc, what kind of timeline do you have in mind for this and what support do you need to get it over the line? Would love to see this published as it showcases how great Paris was for the group 🎉

**Comment by techmaharaj** [comment]
Hi @abangser, I know a few folks have reviewed it, was hoping to review it early this week, giving time to folks to review it over the weekend. I plan to make the changes and raise a PR with the final doc tomorrow end of the day.

**Comment by abangser** [comment]
That is perfect, thanks @techmaharaj !

**Comment by techmaharaj** [comment]
@abangser I made all the changes and updated whatever I could. There are a couple of things on which I'm waiting for Marsh and Mathieu to revert, once that is done, we should be GTG.

**Comment by abangser** [comment]
Fantastic @techmaharaj, as we spoke about in slack, please just open a PR at your convenience, and happy to work with you on this if it is helpful!
