### ISSUE TITLE
[Community] Link to Platforms Definition White Paper broken in the Platform Engineering Maturity Model

### ISSUE THREAD

**Issue by tiagodolphine** [cncf/tag-app-delivery#633]
### Contribution Description

When reading the `Platform Engineering Maturity Model` it was noticed the link that references the `Platforms Definition` White Paper is not found.

For example:
https://github.com/cncf/tag-app-delivery/blob/b279406f83ead64de25572014ab421ddf26b76c7/platforms-maturity-model/v1/index.md?plain=1#L33

### Related Working Group (WG)

Platforms

### Contribution type

White paper

### Why TAG App Delivery?

This is a suggestion to fix a link that currently is not found.

**Comment by lianmakesthings** [comment]
Hi @tiagodolphine, thanks for opening the issue and PR. This should be fixed in https://github.com/cncf/tag-app-delivery/pull/625

**Comment by tiagodolphine** [comment]
Hi @lianmakesthings thanks for pointing out the fix.
So, all good I'll close this one.
