### ISSUE TITLE
[VOTE] Proposing Roberth Strand as Tech Lead of the TAG App Delivery

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#642]
Hello!

As discussed with the TAG Leadership and Platforms WG, I propose @roberthstrand as a new Tech Lead for the TAG App Delivery.

Roberth was a founding member of the Cooperative Delivery (now Platforms) Working Group and maintainer of OpenGitOps. He has been an active member of the TAG for many years, and with his broad knowledge and technical leadership capability, he would definitely be a valuable addition to the TAG Leadership Team. 

**Bio**
Roberth is a self-proclaimed "cloud automator", and works at Sopra Steria as Principal Cloud Native Architect. He has several honorary titles, like Microsoft MVP in the Azure category, CNCF Ambassador, and was previously a HashiCorp Ambassador. Roberth has been involved with TAG App Delivery for years, since he joined the GitOps WG and helped create the GitOps Principles. He currently serves as maintainer on the OpenGitOps project and is one of the co-chairs of the Platforms WG.

**Action requested:** This issue is to ask TAG App Delivery's leaders, TOC Liaisons, and WG Leads (@kgamanji, @linsun, @joshgav, @lianmakesthings, @AloisReitbauer, @angellk, @roberthstrand, @abangser, @sabre1041, @krumware, @rchincha) for their support in nominating him as a Co-Chair. Please add a +1 to indicate your support. After the majority has agreed, I will forward the proposal to the TOC.

**Comment by abangser** [comment]
Roberth has been a long time lead for the WG Platforms and will be able to add a lot of context about the WG progress during TAG meetings. I look forward to creating this more aligned structure within the TAG!

**Comment by lianmakesthings** [comment]
Roberth has been a constant and reliable contributor to the TAG and its WGs.
Thanks again for stepping in, we can scale up operations and enable even more volunteers for the TAG 🙏

**Comment by krumware** [comment]
I'd vote yes twice if I could 👍 👍

**Comment by angellk** [comment]
+1 .. welcome Roberth!

**Comment by thschue** [comment]
Opened up the issue for the voting, therefore closing this ticket. Congrats, Roberth!
