### ISSUE TITLE
Platform Engineering Maturity Model

### ISSUE THREAD

**Issue by Lacoz** [cncf/tag-app-delivery#650]
Just noticed  that 4. Optimizing phase of Interfaces has title 'Integrated services' and on detail section is labeled : 'Level 4, Optimizing — Managed services'

**Comment by hhiroshell** [comment]
I'm fixing it with a PR below 👍  :

- https://github.com/cncf/tag-app-delivery/pull/660

**Comment by krumware** [comment]
Housekeeping: This was merged, should it be closed?

**Comment by thschue** [comment]
Done with #660
