### ISSUE TITLE
Inconsistent tagging practices on community posts

### ISSUE THREAD

**Issue by earth2marsh** [cncf/tag-app-delivery#663]
At the moment we have two similar tags in use:
![image](https://github.com/cncf/tag-app-delivery/assets/54582/990f5e10-46f8-4a9b-94aa-e5ae44794e53)

This issue proposes deprecating the `Community Contribution` tag that pre-dates the community blog process that introduced the `Community` tag. This would require changes to these three posts:

1. [Enterprise IDPs must mature fast...]([Enterprise IDPs must mature fast. Here’s how infrastructure optimization can help](https://tag-app-delivery.cncf.io/blog/enterprise-idp-maturity-hack/)) - Add `Community` tag and remove `Community Contribution` tag
2. [Platform Engineering at KubeCon...](https://tag-app-delivery.cncf.io/blog/platform-engineering-at-kubecon-eu-2024-recap/) - Add `Community` tag, which seems to have been missed?
3. [Clusters for all cloud tenants](https://tag-app-delivery.cncf.io/blog/clusters-for-all-cloud-tenants/) - remove `Community Contribution` tag (I don't think it is appropriate to add a `Community` tag, since it pre-dates the community post concepts.)

**Comment by earth2marsh** [comment]
@abangser fyi

**Comment by abangser** [comment]
Great catch @earth2marsh , we should definitely combine on one and my bad on creating the duplication with the new process!

While we are doing the work, just want to confirm why we would pick one over the other as we can go either way. 

`community` is shorter but with `contribution` do we get any more clarity? 

Wdyt?

**Comment by abangser** [comment]
I'm happy with that solution @earth2marsh! Have assigned you and really appreciate your initiative here!
