### ISSUE TITLE
Fix CodeOwners

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#668]
In perusing the repo, I noticed a warning on the GitHub page for our code owners. It calls into attention two code owners for the repo that may not have necessary access any more. For example I recognise @AloisReitbauer as having [recently been added but as a TL](https://github.com/cncf/tag-app-delivery/pull/644/files).

<img width="1069" alt="image" src="https://github.com/cncf/tag-app-delivery/assets/1557346/4168d408-be1f-4430-a496-277617bea16a">

I wonder if the issue is not in the file, but in the repo permissions?

**Comment by roberthstrand** [comment]
This is indeed because the users do not have the correct permissions on the repository. This is something someone with the admin role on the repo can fix, like @lianmakesthings or possibly @thschue?

**Comment by lianmakesthings** [comment]
Yes I recently stumbled across that too. I already invited all these people with the right permissions, it's on them to accept the invitations now...

**Comment by lianmakesthings** [comment]
https://github.com/cncf/people/pull/502 This was the missing link
