### ISSUE TITLE
Stepping back

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#696]
It has been my pleasure to serve CNCF these past few years as a leader of TAG App Delivery and WG Platforms. I'm pleased and proud of all we've accomplished together. For personal reasons I need to step back from leadership at this time. I look forward to others stepping up and continuing the great work we have underway. 

Thank you all for your support!

**Comment by krumware** [comment]
You're a legend, Josh!

**Comment by abangser** [comment]
Appreciate everything you've done for this community Josh! 

You paved the way for what is consistently called one of the most welcoming groups people have tried to join in OSS space. 

While you may be stepping away from leadership right now, your stamp is real and I look forward to many more years collaboration. Wishing you well my friend.

**Comment by sabre1041** [comment]
Your efforts within the TAG has helped shape what it has become today!

Take time away as necessary, but know that the community is here whenever you need it

**Comment by thschue** [comment]
Thank you for all the work you put into and the initiatives you drove for the TAG and the Platforms WG. 

All the best!

**Comment by lianmakesthings** [comment]
Thank you for all your hard work, Josh! You've kept the TAG running and were managing so many WGs and activities in parallel. I'm glad you're taking a well deserved break.
Whenever you feel up for it, we will be more than happy to welcome you back! ❤️

**Comment by techmaharaj** [comment]
Thanks Josh for all the help to the group. My first ever in-person KubeCon was our meeting in Chicago, it'll always be special. Looking forward to seeing you around and crossing paths.

**Comment by roberthstrand** [comment]
With #740 in review, and with no other technical issues to fix, I am closing this issue.
