### ISSUE TITLE
Proposing Roberth Strand as a Co-Chair of the TAG App Delivery

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#699]
Hello!

As @joshgav [steps back as a Co-Chair](https://github.com/cncf/tag-app-delivery/issues/696) of the TAG App Delivery, the current Chairs (@lianmakesthings and I) propose @roberthstrand as a new co-chair for the TAG App Delivery.

Roberth has been serving the TAG as a Co-Chair of the Platforms Working Group for a long time, was a very active member of the GitOps Working Group and stepped up as a Tech Lead recently. His industry insights, technical expertise and leadership capabilities are very valuable to the TAG Leadership Team.

**Bio**
Roberth is a self-proclaimed "cloud automator", and works at Sopra Steria as Principal Cloud Native Architect. He has several honorary titles, like Microsoft MVP in the Azure category, CNCF Ambassador, and was previously a HashiCorp Ambassador. Roberth has been involved with TAG App Delivery for years, since he joined the GitOps WG and helped create the GitOps Principles. He currently serves as maintainer on the OpenGitOps project and is one of the co-chairs of the Platforms WG. 

**Action requested**: This issue is to ask TAG App Delivery's leaders, TOC Liaisons, and WG Leads (@kgamanji, @linsun, @AloisReitbauer @abangser, @sabre1041, @krumware, @rchincha, @danieloh30, @salaboy, @ThomasVitale) for their support in nominating him as a Co-Chair. Please add a +1 to indicate your support. After the majority has agreed, I will forward the proposal to the TOC.

**Comment by lianmakesthings** [comment]
Hooray! @roberthstrand has been a long standing contributor to the Tag and various WGs. Very very excited to welcome Roberth as a co-chair! 🚀

**Comment by abangser** [comment]
Absolutely 🙌 just want to make sure all that Roberth does with the WG is back filled as well. But I know he is on that so I'm sure we will figure it out 💪

**Comment by linsun** [comment]
+100, thank you Roberth for stepping in! Look forward to working with you!

**Comment by krumware** [comment]
+100!

**Comment by ThomasVitale** [comment]
+100!

**Comment by ThomasVitale** [comment]
+100!

**Comment by danieloh30** [comment]
Definitely vote on Roberth!

**Comment by kgamanji** [comment]
+1!

**Comment by rchincha** [comment]
+1

Thanks @roberthstrand

**Comment by roberthstrand** [comment]
Closing this, as the TOC vote is done. Thank you all for your support!
