### ISSUE TITLE
Write an overview about KUDO

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#72]
This section should include an overview what KUDO is and how it could help 

Should be located in a doc 052_kudo.md

**Comment by thschue** [comment]
Talked to Ken Sipe an he'll take care of KUDO

**Comment by kensipe** [comment]
I have the assignment

**Comment by thschue** [comment]
@kensipe: Have you got any news on this chapter?

**Comment by thschue** [comment]
It will be closed for now. If someone intends to add this section to the whitepaper, simply re-open or create another issue.
