### ISSUE TITLE
[AppDev] Project Map - Introduction

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#722]
Review and finalize "Introduction" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#introduction

**Comment by lechnerc77** [comment]
You can assign this to me as representative from the working group.

**Comment by ThomasVitale** [comment]
@lechnerc77 do you have any inputs for updating/improving this section? It's fine to say no :) we are trying to wrap up this round of review and we want to make sure we are not missing out on any improvement. Thanks!

**Comment by lechnerc77** [comment]
@ThomasVitale I think this section is good to go and the content can be merged into the final document.

**Comment by ThomasVitale** [comment]
Perfect, thanks
