### ISSUE TITLE
[AppDev] Project Map - Projects Classification Criteria

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#724]
Review and finalize "Projects Classification Criteria" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#projects-classification-criteria

**Comment by ThomasVitale** [comment]
@salaboy @danieloh30 do you have any inputs on this part? Anything we should change/update?

**Comment by danieloh30** [comment]
LGTM! Plz go ahead!

**Comment by ThomasVitale** [comment]
Closing this for now as we wrapped up iteration 1. We are starting a second iteration on the deliverable, and we'll have a second look at each section for further improvements.
