### ISSUE TITLE
[AppDev] Project Map - NATS

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#726]
Review and finalize "NATS" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#nats

**Comment by cerebro1** [comment]
Adding myself here.

**Comment by ThomasVitale** [comment]
@cerebro1 thanks! Do you have any inputs for updating/improving this section? It's fine to say no :) we are trying to wrap up this round of review and we want to make sure we are not missing out on any improvement. Thanks!

**Comment by ThomasVitale** [comment]
Closing this for now as we wrapped up iteration 1. We are starting a second iteration on the deliverable, and we'll have a second look at each section for further improvements.
