### ISSUE TITLE
[AppDev] Project Map - gRPC

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#729]
Review and finalize "gRPC" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#grpc

**Comment by ThomasVitale** [comment]
@salaboy @danieloh30 any input on this section?

**Comment by danieloh30** [comment]
Looks good to me even though there're still TODO (empty) sections. We can fill them out after the merge!

**Comment by ThomasVitale** [comment]
I'll close this, then, and will address that in the next iteration. Thanks!
