### ISSUE TITLE
[AppDev] Project Map - Buildpacks

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#730]
Review and finalize "Buildpacks" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#buildpacks

**Comment by cerebro1** [comment]
Since I added the answers for this, I will take it.

**Comment by ThomasVitale** [comment]
Thanks @cerebro1! Did you get any answer from the Buildpacks team? In case, let me know, and I can try reach out to them to see if they have any feedback on this section, thanks!

**Comment by ThomasVitale** [comment]
Closing this for now as we wrapped up iteration 1. We are starting a second iteration on the deliverable, and we'll have a second look at each section for further improvements.
