### ISSUE TITLE
[AppDev] Project Map - Knative Functions

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#731]
Review and finalize "Knative Functions" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#knative-functions

**Comment by lkingland** [comment]
This is looking good.
I am working with @salaboy; providing a little additional feedback.

**Comment by ThomasVitale** [comment]
Thanks @lkingland! Do you have any inputs for updating/improving this section? It's fine to say no :) we are trying to wrap up this round of review and we want to make sure we are not missing out on any improvement. Thanks!

@salaboy how about you?

**Comment by ThomasVitale** [comment]
Closing this for now as we wrapped up iteration 1. We are starting a second iteration on the deliverable, and we'll have a second look at each section for further improvements.
