### ISSUE TITLE
[AppDev] Project Map - Dapr

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#732]
Review and finalize "Dapr" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#dapr

**Comment by yaron2** [comment]
Dapr maintainer here: reviewing this!

**Comment by ThomasVitale** [comment]
Thanks @yaron2! Do you have any inputs for updating/improving this section? It's fine to say no :) we are trying to wrap up this round of review and we want to make sure we are not missing out on any improvement. Thanks!

@salaboy how about you?

**Comment by ThomasVitale** [comment]
Closing this for now as we wrapped up iteration 1. We are starting a second iteration on the deliverable, and we'll have a second look at each section for further improvements.
