### ISSUE TITLE
[AppDev] Project Map - Backstage

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#733]
Review and finalize "Backstage" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#backstage

**Comment by colinjlacy** [comment]
I'll take this one

**Comment by ThomasVitale** [comment]
Thanks! PR approved and merged!
