### ISSUE TITLE
[AppDev] Project Map - Jaeger UI

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#734]
Review and finalize "Jaeger UI" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#jaeger-ui

**Comment by cerebro1** [comment]
I can take this.

**Comment by yurishkuro** [comment]
> What challenges make developers adopt/use this project?

When a microservices-based system handles multitude of requests, it is difficult to know how each individual distributed request execution is shaped, as the other traditional monitoring tools mostly provide single-node visibility into aggregate behavior.

**Comment by cerebro1** [comment]
@salaboy @ThomasVitale @danieloh30 I reached out to Jaeger maintainers on their Slack channel they responded promptly. Thanks, @yurishkuro and @jkowall for creating and reviewing the PR. We will have a look and get it merged ASAP.

**Comment by ThomasVitale** [comment]
Merged in https://github.com/cncf/tag-app-delivery/pull/764
