### ISSUE TITLE
[AppDev] Project Map - Glossary

### ISSUE THREAD

**Issue by ThomasVitale** [cncf/tag-app-delivery#735]
Review and finalize "Glossary" section of Project Map Document: https://github.com/cncf/tag-app-delivery/blob/wg-app-dev-map-review/app-development-map/v1alpha1/index.md#glossary

**Comment by lechnerc77** [comment]
You can assign this to me as representative from the working group.

**Comment by lechnerc77** [comment]
@ThomasVitale I think this section is good to go and for the first version we should add it to the document. On the mid-term it might make sense to extract it and move it to the CNCF glossary

**Comment by ThomasVitale** [comment]
Perfect, thank you!
