### ISSUE TITLE
[Platforms-WG] Nominate and elect Atulpriya Sharma as co-chair of WG Platforms

### ISSUE THREAD

**Issue by krumware** [cncf/tag-app-delivery#738]
**Background**: The Platforms WG has an established group of 3 co-chairs with planned rotation. Unfortunately, there was an unexpected (but amazing!) change with @roberthstrand moving up to the position of Tech Lead for TAG App Delivery. This leaves a vacant position for the third co-chair of the Platforms WG.

**Request**: Current WG leaders @roberthstrand, @abangser and @krumware have nominated @techmaharaj (Atulpriya Sharma) for this role in recognition of his contributions to the group, active participation in community events and Kubecons, and his positive and spirited interaction with others in the group. While the timing of the regular meetings has been difficult for @techmaharaj to attend recently due to timezone, he has expressed availability and commitment to the existing hosting rotation schedule established by the current chairs. I believe the nomination will also greatly improve the availability of support for members in the Asia/Pacific timezones.

@techmaharaj please feel free to share further qualifications of yours in a comment on this issue! We've checked with Atul and he has graciously accepted the nomination; and have also asked TAG App Delivery's leaders for initial approval of his election.

**Action requested**: This issue is to make Atul's nomination official and ask TAG App Delivery's leaders (@thschue, @roberthstrand, @lianmakesthings, @angellk) to approve it. Please add a 👍 to this post or comment with a +1 to indicate your support. We will finalize Atul's election with a PR adding him to relevant groups and listings.

Thanks for your support!

**Comment by lianmakesthings** [comment]
+10000 @techmaharaj has been an active and valued member for the WG and TAG for quite some time. Really glad to see Atul taking a step into leadership 💪

**Comment by techmaharaj** [comment]
Thanks @krumware for nominating me, would be an honour to assist the group.

A quick intro about me:
I am a CNCF ambassador and have been a developer advocate for the last 3 years with software engineering and project management experience of over 7 years before my current role.  I have been involved with the Platforms-WG for over a year. I joined the group when I first learnt about the [Platform White Paper](https://tag-app-delivery.cncf.io/whitepapers/platforms/) that was published which was my gateway to the world of platforms. Later, I participated and contributed to the [Platform Maturity Model](https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/), focusing on the interface side of things. 

Further, I also presented a [talk on workload specifications at the Platforms-WG project meeting at KubeCon Chicago 2023](https://www.youtube.com/live/NZCmYRVziGY?si=BEs-kOZAh5nF0tcI&t=10943) and was also on the [panel on Platform Engineering at the OpenShift Commons gathering at KubeCon Paris 2024](https://youtu.be/PfrUObDwvyQ?si=N_9jLeMlxRtdRYYx). I've also written about platform engineering on various platforms and spoken at different events including [PlatformCon 2024](https://youtu.be/r6kOlzlVL0o?si=SZVTU53t9FjuJrXe), KCD Kerala and KCD Pune to name a few. Apart from that, I've assisted the group on outreach at KubeCons and blog posts.

I'm excited to take up this role and help the group with two major aspects apart from operational things:
- generating awareness about what we do at Platform WG - _at events, on social media platforms, blogs etc._
- streamlining blog post publishing and other governance, and operational aspects reducing the friction.

Check out me [LinkedIn](https://www.linkedin.com/in/atulpriyasharma/) and [Twitter](http://twitter.com/thetechmaharaj) to know what I'm up to!


> +10000 @techmaharaj has been an active and valued member for the WG and TAG for quite some time. Really glad to see Atul taking a step into leadership 💪

Thanks a lot @lianmakesthings for showing the confidence in me :)

**Comment by thschue** [comment]
+1 for making @techmaharaj a chair of the WG. He's a precious member of the WG, and I'm very excited to see him step up.

**Comment by abangser** [comment]
Very excited to have @techmaharaj aboard. Have appreciated all of his support and ideas during the white paper and the maturity model. And looking forward to finding more overlap on our meetings!

**Comment by roberthstrand** [comment]
+♾️

He has done a lot of work for the working group already, and I know he will fit right into the leadership team.

**Comment by abangser** [comment]
With the merging of https://github.com/cncf/tag-app-delivery/pull/743 we are complete! Congrats @techmaharaj and looking forward to collaborating!
