### ISSUE TITLE
[VOTE] Proposing Sarah Christoff as Tech Lead of the TAG App Delivery

### ISSUE THREAD

**Issue by roberthstrand** [cncf/tag-app-delivery#739]
Hey y'all,

Sarah has been going through a trial-run as tech lead for the past couple of months, and she has been doing a great job. I would like to propose that we vote for Sarah to officially get the role of tech lead.

**Bio**
Sarah Christoff is a software engineer at Defense Unicorns. She is a maintainer of Porter, a CNCF sandbox project, and leads the Zarf team which is donated to the OpenSSF. Sarah has been involved in TAG App Delivery as a member for the past year. 

**Action requested:** This issue is to ask TAG App Delivery's leaders, TOC Liaisons, and WG Leads (@kgamanji, @linsun, @lianmakesthings, @thschue, @abangser, @sabre1041, @krumware, @rchincha, @salaboy, @danieloh30, @ThomasVitale) for their support in nominating her as tech lead. Please add a +1 to indicate your support. After the majority has agreed, I will forward the proposal to the TOC.

**Comment by lianmakesthings** [comment]
YESSSSS 👏  So excited for @schristoff to join the team officially! She's been doing a lot since coming on as TL "on probation". Super happy and grateful to have her ❤️

**Comment by thschue** [comment]
+1 from my side and happy to have her in the boat!

**Comment by krumware** [comment]
Yes from me!

**Comment by salaboy** [comment]
+1 for me too

 - Blog: http://salaboy.com <http://salaboy.wordpress.com>
 - Github user: http://github.com/salaboy
 - Twitter: http://twitter.com/salaboy

 - Mauricio "Salaboy" Salatino -

**Comment by ThomasVitale** [comment]
+1 also for me

**Comment by joshuabezaleel** [comment]
This was a joyful surprise seeing Sarah @schristoff being mentioned here, when I browse over the available issues on the TAG App Delivery.

I may neither have the voting rights to give +1 on this nor the most active member of the WG Platform and overall TAG as well, but I just want to give a shoutout on how I believe you folks will be lucky to have her as Tech Lead. 

I contributed to Porter back then (which unfortunately for now have no such time commitment to do so 😞 ) when Carolyn was still the maintainer, and I can see that Sarah continue to bring the passed baton forward of the Porter impressively. We had a chat on Porter booth on KubeCon North America 2023 Chicago and her thoughtfulness is what would make her an indispensable member of any open source community, that's what we need more people to have. 

So, fully rooting for Sarah! 💪

**Comment by roberthstrand** [comment]
Closing this as the TOC vote was a success 🎉
