### ISSUE TITLE
Write about testing operators

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#74]
This section(s) might include some best practices for testing operators and mention kuttl (and/or other tools if applicable)

**Comment by thschue** [comment]
Ken Sipe will take care of this section(s).

**Comment by kensipe** [comment]
I have the assignment!

**Comment by thschue** [comment]
@kensipe: Have you got any news on this chapter?

**Comment by thschue** [comment]
As there is currently no progress on this issue and the first version of the white paper is done, it will be closed. If someone intends to add this to a future version, simply reopen this issue or create another one.
