### ISSUE TITLE
[Community] Update Platform Working Group Meeting Schedule

### ISSUE THREAD

**Issue by manish-jangra** [cncf/tag-app-delivery#786]
### Contribution Description

The Platform Working Group meeting schedule listed on https://tag-app-delivery.cncf.io/wgs/platforms/ needs an update.

## Proposed Fix
I want to update the schedule to reflect the correct meeting times and details.

### Related Working Group (WG)

Platforms

### Contribution type

Blog (Default)

### Why TAG App Delivery?

This contribution ensures accurate meeting schedules for the Platform Working Group, which falls under the TAG App Delivery umbrella.

**Comment by krumware** [comment]
Thank you!
